/**
 * Đợt 3, lô A — ưu tiên 1: hai kỹ năng nhật ký lớp 10–12/09 gắn cho bài đang học mà chưa có bài.
 *  - VIET.VIET.VIET_TU_VAN — bài 13 "U u, Ư ư", mục 3 Tô và viết (SGK tr.38–39).
 *  - ESL.GR.PREPOSITIONS_IN_ON_UNDER — nhật ký gắn cho Unit 1 Review; theo Global Stage là Unit 5.
 *
 *   node scripts/content-gen/dot3-a.mjs
 */
import { sentencePack } from "./lib-en.mjs";
import { writingPack } from "./lib-vi.mjs";

writingPack({
  code: "VIET.VIET.VIET_TU_VAN",
  prefix: "viet-viettu",
  unit: "KNTT-TV1-T1-B13",
  lessonRefs: ["KNTT-TV1-T1-B13"],
  src: "SGK Tiếng Việt 1 tập một, Bài 13 tr.38–39 (mục 3 Tô và viết)",
  note: "Viết tiếng và từ trong phạm vi bài 13. Ô sai là cách viết sai thật: quên dấu (bi / bí), nhầm dấu (cà / cá), nhìn nhầm con chữ (le / lê, đo / do). Mã lỗi tính theo đúng tiếng bị viết sai.",
  copies: [
    ["bà", "bé", "bố"],
    ["cá", "cờ", "cô"],
    ["hồ", "hổ", "lá"],
    ["lê", "li", "bí"],
    ["cú", "củ", "dù"],
    ["đu đủ"],
    ["cá cờ"],
    ["bí đỏ", "lá cờ"],
    ["hồ cá", "bể cá"],
    ["bà cụ", "bó cỏ"],
    ["bờ đê", "đò cũ"],
    ["Bé có đu đủ."],
  ],
  words: [
    { w: "bí", pic: "🎃", gloss: "quả bí", wrongs: ["bi", "bì"] },
    { w: "cá", pic: "🐟", gloss: "con cá", wrongs: ["ca", "cà"] },
    { w: "cờ", pic: "🚩", gloss: "lá cờ", wrongs: ["cơ", "cớ"] },
    { w: "hổ", pic: "🐯", gloss: "con hổ", wrongs: ["hồ", "hô"] },
    { w: "lá", pic: "🍃", gloss: "chiếc lá", wrongs: ["la", "là"] },
    { w: "lê", pic: "🍐", gloss: "quả lê", wrongs: ["le", "lề"] },
    { w: "dù", pic: "☂️", gloss: "cái dù", wrongs: ["du", "dụ"] },
    { w: "cú", pic: "🦉", gloss: "con cú", wrongs: ["cu", "củ"] },
    { w: "đò", pic: "🛶", gloss: "con đò", wrongs: ["đo", "do"] },
    { w: "đu đủ", pic: "🍈", gloss: "quả đu đủ", wrongs: ["đu đu", "đủ đủ"] },
    { w: "bí đỏ", say: "bí đỏ", wrongs: ["bí đo", "bi đỏ"] },
    { w: "cô bé", pic: "👧", gloss: "cô bé", wrongs: ["cô be", "co bé"] },
  ],
  builds: [
    ["c", "á", "cá", "b"],
    ["h", "ồ", "hồ", "l"],
    ["l", "á", "lá", "c"],
    ["b", "í", "bí", "l"],
    ["c", "ờ", "cờ", "b"],
    ["d", "ù", "dù", "h"],
  ],
  reads: ["hồ cá", "Bé có đu đủ", "Bà có lá cờ", "cá cờ ở hồ"],
});

sentencePack({
  dir: "esl",
  subject: "ESL",
  code: "ESL.GR.PREPOSITIONS_IN_ON_UNDER",
  prefix: "esl-prep",
  src: "Global Stage 1 Language Book Unit 5 (GS1-LB.U5) — nhật ký lớp gắn cho Unit 1 Review; chưa chụp trang sách",
  note: "Giới từ in / on / under / next to / behind. Tranh emoji không vẽ được vị trí, nên câu nào cần biết vị trí đều kèm nghĩa tiếng Việt trong ngoặc — nếu không, câu nào cũng đúng ngữ pháp và bài có ba đáp án.",
  items: [
    {
      q: "Which word means 'ở dưới'?",
      right: "under",
      wrongs: [["on"], ["in"]],
      d: 1,
      hint: "Think of a ball below a chair.",
    },
    {
      q: "Which word means 'ở trong'?",
      right: "in",
      wrongs: [["on"], ["under"]],
      d: 1,
      hint: "A toy inside a box.",
    },
    {
      q: "Which word means 'ở trên'?",
      right: "on",
      wrongs: [["in"], ["behind"]],
      d: 1,
      hint: "A cup on top of a table.",
    },
    {
      q: "Which word means 'bên cạnh'?",
      right: "next to",
      wrongs: [["under"], ["in"]],
      d: 2,
      hint: "Two friends side by side.",
    },
    {
      q: "Which word means 'đằng sau'?",
      right: "behind",
      wrongs: [["next to"], ["on"]],
      d: 2,
      hint: "Hiding at the back.",
    },
    {
      q: "The cat is ___ the bed. (ở dưới)",
      right: "under",
      wrongs: [["on"], ["in"]],
      pic: "🐈",
      d: 2,
      hint: "'Ở dưới' means under.",
    },
    {
      q: "The ball is ___ the box. (ở trong)",
      right: "in",
      wrongs: [["on"], ["behind"]],
      pic: "⚽",
      d: 2,
      hint: "'Ở trong' means in.",
    },
    {
      q: "The book is ___ the desk. (ở trên)",
      right: "on",
      wrongs: [["under"], ["next to"]],
      pic: "📖",
      d: 3,
      hint: "'Ở trên' means on.",
    },
    {
      q: "The dog is ___ the tree. (đằng sau)",
      right: "behind",
      wrongs: [["in"], ["on"]],
      pic: "🐕",
      d: 3,
      hint: "'Đằng sau' means behind.",
    },
    {
      q: "The bag is ___ the chair. (bên cạnh)",
      right: "next to",
      wrongs: [["under"], ["in"]],
      pic: "🎒",
      d: 4,
      hint: "'Bên cạnh' means next to.",
    },
    {
      q: "Quả bóng ở trên bàn. Which sentence?",
      right: "The ball is on the table.",
      wrongs: [["The ball is in the table."], ["The ball is under the table."]],
      d: 4,
      hint: "Find the word for 'ở trên'.",
    },
    {
      q: "Con mèo ở trong hộp. Which sentence?",
      right: "The cat is in the box.",
      wrongs: [["The cat is on the box."], ["The cat is behind the box."]],
      d: 5,
      hint: "Find the word for 'ở trong'.",
    },
  ],
  listens: [
    { say: "under", right: "ở dưới", wrongs: [["ở trên"], ["ở trong"]], d: 1 },
    { say: "on", right: "ở trên", wrongs: [["ở dưới"], ["bên cạnh"]], d: 1 },
    { say: "behind", right: "đằng sau", wrongs: [["ở trong"], ["ở trên"]], d: 2 },
    { say: "next to", right: "bên cạnh", wrongs: [["đằng sau"], ["ở dưới"]], d: 2 },
    {
      say: "The cat is in the box.",
      right: "Con mèo ở trong hộp.",
      wrongs: [["Con mèo ở trên hộp."], ["Con mèo ở dưới hộp."]],
      d: 3,
    },
    {
      say: "The ball is under the bed.",
      right: "Quả bóng ở dưới giường.",
      wrongs: [["Quả bóng ở trên giường."], ["Quả bóng ở cạnh giường."]],
      d: 4,
    },
    {
      say: "The book is on the desk.",
      right: "Quyển sách ở trên bàn.",
      wrongs: [["Quyển sách ở dưới bàn."], ["Quyển sách ở sau bàn."]],
      d: 4,
    },
    {
      say: "The dog is behind the door.",
      right: "Con chó ở sau cửa.",
      wrongs: [["Con chó ở trong cửa."], ["Con chó ở trên cửa."]],
      d: 5,
    },
  ],
  builds: [
    "The ball is in my bag.",
    "My book is on a desk.",
    "A cat is under my bed.",
    "My bag is behind the door.",
    "The pen is next to my cup.",
  ],
  sorts: [
    {
      q: "Place words or things? Sort them.",
      zones: ["Place words", "Things"],
      a: ["in", "under"],
      b: ["box", "bed"],
      d: 2,
    },
    {
      q: "Sort the cards into two baskets.",
      zones: ["Place words", "Things"],
      a: ["on", "behind"],
      b: ["desk", "door"],
      d: 3,
    },
    {
      q: "Which cards tell us where?",
      zones: ["Place words", "Things"],
      a: ["next to", "in"],
      b: ["chair", "cup"],
      d: 4,
    },
  ],
  reads: [
    "The cat is under the bed.",
    "The ball is in the box.",
    "My book is on the desk.",
    "The dog is behind the tree.",
    "The bag is next to the chair.",
  ],
  writes: [
    ["Draw a ball under a chair. Write: under.", "under"],
    ["Write: The cat is in the box.", "The cat is in the box."],
    ["Draw your bag. Where is it? Write one word.", "on"],
  ],
});
