/**
 * Pha 6c, lô A3 — English Maths: 10 kỹ năng trống của tuần 13–18. Trường chưa có giáo trình English
 * Maths (MATH NOTES Volume 1 chỉ tới Unit 4, chưa chạm các chủ đề này) — nguồn CCSS ghi trong bản đồ.
 *
 * Toán bắt mọi câu MCQ/LISTEN_CHOOSE có ô nhiễu mang mã lỗi đúng nghĩa, tính ra từ đáp án như
 * emath-dot3a.mjs: dem_thieu_1/dem_thua_1 = đáp án ∓ 1, nham_cong_tru = làm ngược phép tính,
 * lap_lai_tong = chép lại một số có sẵn trong đề, khong_hieu_de_loi_van = hiểu sai câu hỏi lời văn.
 *
 *   node scripts/content-gen/emath-dot4.mjs
 */
import { sentencePack } from "./lib-en.mjs";

const base = { dir: "emath", subject: "EMATH" };
const CCSS = (std, topic) => `CCSS ${std} (${topic}) — chưa có giáo trình English Maths của trường`;

function N(ans, kinds, g = {}) {
  const out = [];
  for (const k of kinds) {
    const v = {
      dem_thieu_1: ans - 1,
      dem_thua_1: ans + 1,
      nham_cong_tru: g.opp,
      lap_lai_tong: g.rep,
    }[k];
    if (v == null || v < 0 || v === ans || out.some(([t]) => t === String(v))) continue;
    out.push([String(v), k]);
    if (out.length === 2) break;
  }
  if (!out.length) out.push([String(ans + 1), "dem_thua_1"]);
  return out;
}
const DT = ["dem_thieu_1", "dem_thua_1"];
const TD = ["dem_thua_1", "dem_thieu_1"];
const Q = (q, ans, kinds, d, hint, extra = {}) => ({
  q,
  right: String(ans),
  wrongs: N(ans, kinds, extra.g),
  d,
  hint,
  ...extra,
});
const L = (say, ans, kinds, d, g, q) => ({
  say,
  right: String(ans),
  wrongs: N(ans, kinds, g),
  d,
  ...(q ? { q } : {}),
});

// ═══════════════════════════════════════════════════════════════ make ten ═════════════════════
sentencePack({
  ...base,
  code: "EMATH.OA.MAKE_TEN",
  prefix: "emath-maketen",
  src: CCSS("1.OA.C.6", "make-ten strategy"),
  note: "Tách một số để làm tròn 10 trước (8+5 = 8+2+3 = 10+3). Ô nhiễu: hụt/dư một, cộng ngược, chép lại số trong đề.",
  items: [
    Q(
      "Make ten: 8 + 2 = 10. Then + 3 = ?",
      13,
      [...DT, "lap_lai_tong"],
      2,
      "8 needs 2 more to make 10. 5 is 2 and 3.",
      { g: { rep: 5 } },
    ),
    Q(
      "Make ten: 9 + 1 = 10. Then + 3 = ?",
      13,
      [...TD, "lap_lai_tong"],
      2,
      "9 needs 1 more. 4 is 1 and 3.",
      { g: { rep: 4 } },
    ),
    Q(
      "Make ten: 7 + 3 = 10. Then + 3 = ?",
      13,
      [...DT, "lap_lai_tong"],
      3,
      "7 needs 3 more. 6 is 3 and 3.",
      { g: { rep: 6 } },
    ),
    Q(
      "Make ten: 8 + 2 = 10. Then + 4 = ?",
      14,
      [...TD, "lap_lai_tong"],
      3,
      "8 needs 2 more. 6 is 2 and 4.",
      { g: { rep: 6 } },
    ),
    Q(
      "Make ten: 9 + 1 = 10. Then + 6 = ?",
      16,
      [...DT, "lap_lai_tong"],
      3,
      "9 needs 1 more. 7 is 1 and 6.",
      { g: { rep: 7 } },
    ),
    Q("6 + 8 = ?", 14, DT, 3, "Make ten with the 8: 6 + 4 = 10, plus 4 more."),
    Q("9 + 9 = ?", 18, TD, 4, "9 + 1 = 10, then 10 + 8."),
    Q("8 + 9 = ?", 17, DT, 4, "8 + 2 = 10, then 10 + 7."),
    Q("8 + 5: split 5 into 2 and ?", 3, [...DT, "lap_lai_tong"], 2, "2 + 3 = 5.", {
      g: { rep: 2 },
    }),
    Q("9 + 6: split 6 into 1 and ?", 5, [...TD, "lap_lai_tong"], 2, "1 + 5 = 6.", {
      g: { rep: 1 },
    }),
    Q("7 + 5: split 5 into 3 and ?", 2, DT, 3, "3 + 2 = 5."),
    Q("9 + 8 = ?", 17, DT, 4, "9 + 1 = 10, then 10 + 7."),
    Q("6 + 7 = ?", 13, TD, 4, "Make ten with the 7: 6 + 4 = 10, plus 3 more."),
    Q("8 + 4 = ?", 12, DT, 3, "8 + 2 = 10, then 10 + 2."),
    Q("7 + 8 = ?", 15, DT, 4, "7 + 3 = 10, then 10 + 5."),
    Q("9 + 6: how many more does 9 need to make ten?", 1, TD, 5, "9 is only 1 away from 10."),
    Q(
      "5 + 9 = ?",
      14,
      [...DT, "lap_lai_tong"],
      3,
      "Make ten with the 9: 5 + 5 = 10, plus 4 more.",
      { g: { rep: 5 } },
    ),
    Q(
      "6 + 9 = ?",
      15,
      [...TD, "lap_lai_tong"],
      3,
      "Make ten with the 9: 6 + 4 = 10, plus 5 more.",
      { g: { rep: 6 } },
    ),
    Q("4 + 8 = ?", 12, DT, 2, "Make ten with the 8: 4 + 6 = 10, plus 2 more."),
    Q("3 + 9 = ?", 12, DT, 2, "Make ten with the 9: 3 + 7 = 10, plus 2 more."),
    Q("7 + 6: split 6 into 3 and ?", 3, [...DT, "lap_lai_tong"], 2, "3 + 3 = 6.", {
      g: { rep: 3 },
    }),
    Q("6 + 8: split 8 into 4 and ?", 4, [...TD, "lap_lai_tong"], 3, "4 + 4 = 8.", {
      g: { rep: 4 },
    }),
    Q("9 + 5 = ?", 14, DT, 3, "9 + 1 = 10, then 10 + 4."),
    Q("8 + 7 = ?", 15, TD, 4, "8 + 2 = 10, then 10 + 5."),
    {
      q: "Which number needs only 1 more to make ten?",
      right: "9",
      wrongs: [["8", "dem_thieu_1"], ["7"]],
      d: 2,
      hint: "9 + 1 = 10.",
    },
    {
      q: "Which number needs 2 more to make ten?",
      right: "8",
      wrongs: [["9", "dem_thua_1"], ["6"]],
      d: 2,
      hint: "8 + 2 = 10.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} says a sum. Tap the answer!",
    "Listen carefully, then choose.",
    "What is the answer? Tap it.",
    "Listen again and pick a number.",
    "Make ten, then tap the sum.",
  ],
  listens: [
    L("8 plus 5. Make ten first.", 13, DT, 2),
    L("9 plus 7. Make ten first.", 16, TD, 3),
    L("5 plus 9. Make ten first.", 14, DT, 3),
    L("4 plus 8. Make ten first.", 12, TD, 2),
    L("7 plus 6. Make ten first.", 13, DT, 3),
    L("8 plus 9. Make ten first.", 17, DT, 4),
    L("6 plus 8. Make ten first.", 14, TD, 3),
    L("9 plus 9. Make ten first.", 18, DT, 4),
  ],
  places: [
    {
      q: "8 + 5: drag the missing part to make ten.",
      items: [["2"], ["1"], ["3"]],
      zones: [["8 + ? = 10"]],
      key: { 0: [0] },
      d: 2,
      hint: "8 needs 2 more to make 10.",
      why: "8 + 2 = 10.",
    },
    {
      q: "9 + 4: drag the missing part to make ten.",
      items: [["2"], ["1"], ["4"]],
      zones: [["9 + ? = 10"]],
      key: { 0: [1] },
      d: 2,
      hint: "9 needs 1 more to make 10.",
      why: "9 + 1 = 10.",
    },
    {
      q: "7 + 6: drag the missing part to make ten.",
      items: [["3"], ["2"], ["1"]],
      zones: [["7 + ? = 10"]],
      key: { 0: [0] },
      d: 3,
      hint: "7 needs 3 more to make 10.",
      why: "7 + 3 = 10.",
    },
    {
      q: "Drag the sum: 8 + 6 =",
      items: [["14"], ["13"], ["15"]],
      zones: [["8 + 6"]],
      key: { 0: [0] },
      d: 3,
      hint: "8 + 2 = 10, then + 4.",
      why: "8 + 6 = 14.",
    },
    {
      q: "Drag the sum: 9 + 6 =",
      items: [["15"], ["14"], ["16"]],
      zones: [["9 + 6"]],
      key: { 0: [0] },
      d: 4,
      hint: "9 + 1 = 10, then + 5.",
      why: "9 + 6 = 15.",
    },
  ],
  counts: [
    ["ten-frame dots (first row)", "🔵", 8, "Count the filled dots. Tap each one."],
    ["ten-frame dots (second row)", "🔴", 5, "Count these dots too. Tap each one."],
  ],
});

// ═══════════════════════════════════════════════════════════════ use tools / draw a model ═════
sentencePack({
  ...base,
  code: "EMATH.MP.USE_TOOLS_DRAW_MODEL",
  prefix: "emath-tool",
  src: CCSS("MP.5", "use appropriate tools strategically"),
  note: "Chọn công cụ phù hợp (ten frame, tia số, vẽ vòng tròn) để giải bài; không có mã lỗi cho 'chọn sai công cụ' nên trắc nghiệm chọn công cụ để untagged, còn ô đếm số chấm/số bước dùng dem_thieu_1/dem_thua_1.",
  items: [
    {
      q: "Mai draws circles for 6 + 3. How many for 6?",
      right: "6",
      wrongs: N(6, DT),
      d: 1,
      hint: "One circle for each unit in 6.",
    },
    {
      q: "Ben draws 9 circles, crosses out 4. How many left?",
      right: "5",
      wrongs: N(5, DT, { opp: 13 }),
      d: 3,
      hint: "9 circles, cross out 4, count what's left.",
    },
    {
      q: "On a ten frame showing 7, how many empty boxes are left?",
      right: "3",
      wrongs: N(3, DT),
      d: 3,
      hint: "A ten frame has 10 boxes total.",
    },
    {
      q: "On a ten frame showing 4, how many empty boxes are left?",
      right: "6",
      wrongs: N(6, DT),
      d: 2,
      hint: "10 minus 4 empty boxes.",
    },
    {
      q: "A number line jump from 5 to 5+4. Where do you land?",
      right: "9",
      wrongs: N(9, DT),
      d: 3,
      hint: "Jump 4 steps forward from 5.",
    },
    {
      q: "A number line jump from 10 back 3. Where do you land?",
      right: "7",
      wrongs: N(7, DT),
      d: 4,
      hint: "Jump 3 steps backward from 10.",
    },
    {
      q: "Ten frame: 10 full dots plus 2 loose. What number?",
      right: "12",
      wrongs: N(12, DT),
      d: 3,
      hint: "10 and 2 more.",
    },
    {
      q: "Ten frame: 10 full dots plus 5 loose. What number?",
      right: "15",
      wrongs: N(15, DT),
      d: 3,
      hint: "10 and 5 more.",
    },
    {
      q: "A number line jump from 8 to 8+5. Where do you land?",
      right: "13",
      wrongs: N(13, DT),
      d: 3,
      hint: "Jump 5 steps forward from 8.",
    },
    {
      q: "A number line jump from 15 back 6. Where do you land?",
      right: "9",
      wrongs: N(9, DT),
      d: 4,
      hint: "Jump 6 steps backward from 15.",
    },
    {
      q: "Lan draws 12 circles, crosses out 5. How many left?",
      right: "7",
      wrongs: N(7, DT, { opp: 17 }),
      d: 3,
      hint: "Draw 12, cross out 5, count what's left.",
    },
    {
      q: "Ten frame: 10 full dots plus 8 loose. What number?",
      right: "18",
      wrongs: N(18, DT),
      d: 3,
      hint: "10 and 8 more.",
    },
    {
      q: "On a ten frame showing 9, how many empty boxes are left?",
      right: "1",
      wrongs: N(1, DT),
      d: 2,
      hint: "10 minus 9 empty boxes.",
    },
    {
      q: "Drawing circles to solve 9 + 6, how many circles for 9?",
      right: "9",
      wrongs: N(9, DT),
      d: 1,
      hint: "One circle for each unit in 9.",
    },
    {
      q: "Number line jump from 7 to 7+8. Where do you land?",
      right: "15",
      wrongs: N(15, DT),
      d: 4,
      hint: "Jump 8 steps forward from 7.",
    },
    {
      q: "On a ten frame showing 6, how many empty boxes are left?",
      right: "4",
      wrongs: N(4, DT),
      d: 2,
      hint: "10 minus 6 empty boxes.",
    },
    {
      q: "On a ten frame showing 3, how many empty boxes are left?",
      right: "7",
      wrongs: N(7, DT),
      d: 2,
      hint: "10 minus 3 empty boxes.",
    },
    {
      q: "A number line jump from 6 to 6+7. Where do you land?",
      right: "13",
      wrongs: N(13, DT),
      d: 3,
      hint: "Jump 7 steps forward from 6.",
    },
    {
      q: "Ten frame: 10 full dots plus 4 loose. What number?",
      right: "14",
      wrongs: N(14, DT),
      d: 2,
      hint: "10 and 4 more.",
    },
    {
      q: "Drawing circles to solve 8 + 5, how many circles for 5?",
      right: "5",
      wrongs: N(5, DT),
      d: 1,
      hint: "One circle for each unit in 5.",
    },
    {
      q: "On a ten frame showing 8, how many empty boxes are left?",
      right: "2",
      wrongs: N(2, DT),
      d: 2,
      hint: "10 minus 8 empty boxes.",
    },
  ],
  builds: [],
  places: [
    {
      q: "Match the problem to the best tool.",
      items: [["8 + 5"], ["12, 15, or 18?"]],
      zones: [["ten frame"], ["number line"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "Ten frame for making ten, number line for comparing.",
      why: "8 + 5 uses make-ten; comparing numbers uses a number line.",
    },
    {
      q: "Drag the number that matches: ten frame full + 3 loose dots.",
      items: [["13"], ["10"], ["3"]],
      zones: [["Answer"]],
      key: { 0: [0] },
      d: 2,
      hint: "10 and 3 more.",
      why: "10 + 3 = 13.",
    },
    {
      q: "Drag the number that matches: ten frame full + 6 loose dots.",
      items: [["16"], ["6"], ["10"]],
      zones: [["Answer"]],
      key: { 0: [0] },
      d: 3,
      hint: "10 and 6 more.",
      why: "10 + 6 = 16.",
    },
    {
      q: "Order the steps to solve 9 + 4 with a drawing.",
      items: [["Count all the circles."], ["Draw 9 circles, then 4 more."], ["Write the total."]],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [1], 1: [0], 2: [2] },
      d: 4,
      hint: "Draw first, then count, then write.",
      why: "Draw, count, write the answer.",
    },
    {
      q: "Match each problem to the best model.",
      items: [["Compare 9 and 13"], ["Make ten with 8 + 6"]],
      zones: [["number line"], ["ten frame"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "Comparing needs a number line; make-ten needs a ten frame.",
      why: "Number line for comparing, ten frame for make-ten.",
    },
    {
      q: "Drag the number that matches: ten frame full + 9 loose dots.",
      items: [["19"], ["9"], ["10"]],
      zones: [["Answer"]],
      key: { 0: [0] },
      d: 3,
      hint: "10 and 9 more.",
      why: "10 + 9 = 19.",
    },
    {
      q: "Match each problem to the best tool.",
      items: [["'how many more' between 6 and 14"], ["8 + 5 by making ten"]],
      zones: [["number line"], ["ten frame"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "Number line for comparing distance, ten frame for make-ten.",
      why: "Comparing uses a number line; make-ten uses a ten frame.",
    },
    {
      q: "Which model matches each grouping?",
      items: [["3 equal groups of 4"], ["4 equal groups of 3"]],
      zones: [["3 circles with 4 dots each"], ["4 circles with 3 dots each"]],
      key: { 0: [0], 1: [1] },
      d: 5,
      hint: "Each group needs its own circle.",
      why: "One circle drawn per group.",
    },
    {
      q: "Order the steps to solve 8 + 7 with a model.",
      items: [["Write the total."], ["Draw 8 dots, then 7 more."], ["Count all the dots."]],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [2], 1: [0], 2: [1] },
      d: 3,
      hint: "Draw first, then count, then write.",
      why: "Draw, count, write the answer.",
    },
  ],
  sorts: [
    {
      q: "Sort each problem by the best tool.",
      zones: ["Ten frame", "Number line"],
      a: ["8 + 5 (make ten)", "find 7 + 6 fast"],
      b: ["counting on from 12 to 15", "compare 12 and 15"],
      d: 4,
      hint: "Ten frame for make-ten, number line for order and comparing.",
    },
  ],
  counts: [
    ["circles drawn for 6 + 3", "⚪", 9, "Count all the circles Mai drew. Tap each one."],
    ["dots on the number line jumps", "🔵", 5, "Count the jump marks. Tap each one."],
  ],
  writes: [
    [
      "Draw a ten frame to show 8 + 4. Write the total.",
      "12",
      ["Ten frame đúng 10 ô", "Tổng đúng 12"],
    ],
    [
      "Draw a number line jump: 6 to 6+5. Where do you land?",
      "11",
      ["Vẽ đủ 5 bước nhảy", "Đáp số đúng 11"],
    ],
    [
      "Draw circles to solve 10 - 3. Write the answer.",
      "7",
      ["Vẽ 10 vòng tròn, gạch 3", "Đáp số đúng 7"],
    ],
  ],
});

// ═══════════════════════════════════════════════════════════════ add within 20 ════════════════
sentencePack({
  ...base,
  code: "EMATH.OA.ADD_WITHIN_20",
  prefix: "emath-add20",
  src: CCSS("1.OA.C.6", "add within 20"),
  note: "Cộng hai số có tổng đến 20 bằng make ten, doubles, counting on. Ô nhiễu: hụt/dư một (đặc biệt lỗi qua 10), chép lại một số trong đề.",
  items: [
    Q("9 + 7 = ?", 16, [...DT, "lap_lai_tong"], 2, "Make ten: 9 + 1 = 10, then 10 + 6.", {
      g: { rep: 7 },
    }),
    Q("8 + 8 = ?", 16, DT, 2, "Double 8 is 16."),
    Q("6 + 9 = ?", 15, [...TD, "lap_lai_tong"], 3, "Make ten with the 9.", { g: { rep: 6 } }),
    Q("7 + 7 = ?", 14, DT, 2, "Double 7 is 14."),
    Q("5 + 9 = ?", 14, [...DT, "lap_lai_tong"], 3, "Make ten with the 9.", { g: { rep: 5 } }),
    Q("8 + 6 = ?", 14, TD, 3, "Make ten with the 8."),
    Q("9 + 9 = ?", 18, DT, 3, "Double 9 is 18."),
    Q("7 + 8 = ?", 15, DT, 3, "Make ten with the 8."),
    Q("6 + 6 = ?", 12, TD, 2, "Double 6 is 12."),
    Q("4 + 9 = ?", 13, [...DT, "lap_lai_tong"], 3, "Make ten with the 9.", { g: { rep: 4 } }),
    Q("9 + 8 = ?", 17, DT, 4, "Make ten: 9 + 1, then + 7."),
    Q("7 + 9 = ?", 16, TD, 4, "Make ten with the 9."),
    Q("3 + 9 = ?", 12, DT, 3, "Make ten with the 9."),
    Q("8 + 7 = ?", 15, TD, 4, "Make ten with the 8."),
    Q("9 + 6 = ?", 15, DT, 4, "Make ten with the 9."),
    Q("5 + 8 = ?", 13, [...DT, "lap_lai_tong"], 3, "Make ten with the 8.", { g: { rep: 5 } }),
    Q("6 + 7 = ?", 13, TD, 3, "Make ten with the 7."),
    Q("4 + 8 = ?", 12, DT, 2, "Make ten with the 8."),
    Q("5 + 7 = ?", 12, TD, 3, "Make ten with the 7."),
    Q("2 + 3 = ?", 5, DT, 1, "Count on 3 from 2."),
    Q("4 + 2 = ?", 6, TD, 1, "Count on 2 from 4."),
    Q("9 + 4 + 3 = ?", 16, DT, 5, "9 + 1 = 10 first, then + 3, then + 3 more."),
    Q("8 + 5 + 4 = ?", 17, TD, 5, "8 + 2 = 10 first, then + 3, then + 4 more."),
  ],
  listenPrompts: [
    "Listen and tap the answer.",
    "{ban} says a sum. Tap the answer!",
    "Listen carefully, then choose.",
    "What is the answer? Tap it.",
    "Listen again and pick a number.",
    "Tap the number you worked out.",
  ],
  listens: [
    L("Nine plus seven.", 16, DT, 2),
    L("Eight plus eight.", 16, DT, 2),
    L("Seven plus eight.", 15, TD, 3),
    L("Nine plus nine.", 18, DT, 3),
    L("Six plus nine.", 15, DT, 3),
    L("Eight plus six.", 14, TD, 3),
    L("Nine plus six.", 15, DT, 4),
    L("Five plus eight.", 13, DT, 3),
    L("Six plus seven.", 13, TD, 3),
    L("Two plus three.", 5, DT, 1),
  ],
  builds: [],
  places: [
    {
      q: "Drag the sum: 9 + 7 =",
      items: [["16"], ["17"], ["15"]],
      zones: [["9 + 7"]],
      key: { 0: [0] },
      d: 2,
      hint: "Make ten first.",
      why: "9 + 7 = 16.",
    },
    {
      q: "Drag the sum: 8 + 6 =",
      items: [["14"], ["15"], ["13"]],
      zones: [["8 + 6"]],
      key: { 0: [0] },
      d: 3,
      hint: "Make ten first.",
      why: "8 + 6 = 14.",
    },
    {
      q: "Drag the sum: 7 + 9 =",
      items: [["16"], ["15"], ["17"]],
      zones: [["7 + 9"]],
      key: { 0: [0] },
      d: 4,
      hint: "Make ten first.",
      why: "7 + 9 = 16.",
    },
    {
      q: "Drag the sum: 9 + 4 + 3 =",
      items: [["16"], ["15"], ["17"]],
      zones: [["9 + 4 + 3"]],
      key: { 0: [0] },
      d: 5,
      hint: "Make ten first, then add the rest.",
      why: "9 + 4 + 3 = 16.",
    },
  ],
  reads: [
    "Nine plus six is fifteen.",
    "Eight plus eight is sixteen.",
    "Nine plus eight is seventeen.",
    "Nine plus nine is eighteen.",
    "Nine plus seven is sixteen.",
  ],
});

// ═══════════════════════════════════════════════════════════════ 3D shapes ════════════════════
const SHAPE3D = { cube: "🎲", sphere: "⚽", cone: "🍦", cylinder: "🥫", prism: "📦" };
sentencePack({
  ...base,
  code: "EMATH.G.NAME_3D_SHAPES",
  prefix: "emath-3dshape",
  src: CCSS("K.G.A.2", "identifying 3D shapes"),
  note: "Không có mã lỗi cho 'gọi nhầm tên hình khối', nên theo đúng cách EMATH.G.NAME_2D_SHAPES đã làm: MCQ/LISTEN_CHOOSE chỉ hỏi thứ đếm được (số mặt phẳng, số góc) — nơi dem_thieu_1/dem_thua_1 nói đúng lỗi; gọi tên hình đi bằng kéo-thả (không cần mã lỗi).",
  items: [
    Q("How many flat faces does a cube have?", 6, DT, 1, "Count the top, bottom, and four sides."),
    Q("How many corners does a cube have?", 8, TD, 2, "Touch each corner of the dice."),
    Q(
      "How many flat faces does a rectangular prism have?",
      6,
      DT,
      1,
      "Count every flat side of the box.",
    ),
    Q("How many corners does a rectangular prism have?", 8, TD, 3, "Touch each corner of the box."),
    Q(
      "How many flat faces does a cylinder have?",
      2,
      DT,
      2,
      "Only the top and bottom of a can are flat.",
    ),
    {
      q: "How many corners does a cylinder have?",
      right: "0",
      wrongs: [["1", "dem_thua_1"], ["2"]],
      d: 4,
      hint: "A can has no sharp corners.",
    },
    Q("How many flat faces does a cone have?", 1, DT, 3, "Only the round base is flat."),
    {
      q: "How many points does a cone have?",
      right: "1",
      wrongs: [
        ["0", "dem_thieu_1"],
        ["2", "dem_thua_1"],
      ],
      d: 3,
      hint: "A cone comes to one point at the top.",
    },
    {
      q: "How many flat faces does a sphere have?",
      right: "0",
      wrongs: [["1", "dem_thua_1"], ["6"]],
      d: 4,
      hint: "A sphere is round all over.",
    },
    {
      q: "How many corners does a sphere have?",
      right: "0",
      wrongs: [["1", "dem_thua_1"], ["8"]],
      d: 5,
      hint: "A sphere has no corners at all.",
    },
    Q("How many corners does a cone have?", 1, TD, 4, "A cone has one point at the top."),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} asks about a shape. Tap it!",
    "Listen carefully, then choose.",
    "How many? Tap the number.",
    "Listen again and pick one.",
    "Think of the shape, then tap.",
  ],
  listens: [
    L("How many flat faces on a cube?", 6, DT, 1),
    L("How many corners on a rectangular prism?", 8, TD, 2),
    L("How many flat faces on a cylinder?", 2, DT, 3),
    L("How many flat faces on a cone?", 1, DT, 4),
    L("How many corners on a cube?", 8, TD, 2),
    L("How many flat faces on a sphere?", 0, DT, 5),
  ],
  builds: [],
  sorts: [
    {
      q: "Sort the objects: round shapes or shapes with flat faces?",
      zones: ["Round (sphere/cone/cylinder)", "All flat faces (cube/prism)"],
      a: ["ball", "can"],
      b: ["dice", "book"],
      d: 3,
      hint: "Does it roll, or does it only slide?",
    },
    {
      q: "Sort the shapes: rolls, or does not roll?",
      zones: ["Rolls", "Does not roll"],
      a: ["sphere", "cylinder"],
      b: ["cube", "rectangular prism"],
      d: 4,
      hint: "Flat faces stop a shape from rolling.",
    },
  ],
  places: [
    {
      q: "Drag each object to its 3D shape name.",
      items: [
        [null, "⚽"],
        [null, "🎲"],
        [null, "🥫"],
      ],
      zones: [["sphere"], ["cube"], ["cylinder"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 3,
      hint: "Round ball, square-faced dice, can with flat ends.",
      why: "⚽ sphere, 🎲 cube, 🥫 cylinder.",
    },
    {
      q: "Drag each object to its 3D shape name.",
      items: [
        [null, "🍦"],
        [null, "📦"],
      ],
      zones: [["cone"], ["rectangular prism"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "One comes to a point, one is box-shaped.",
      why: "🍦 cone, 📦 rectangular prism.",
    },
    {
      q: "Match each 3D shape to a real object.",
      items: [
        [null, "🎲"],
        [null, "⚽"],
        [null, "🍦"],
      ],
      zones: [["a die"], ["a ball"], ["an ice-cream cone"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 4,
      hint: "Think about which real object matches each shape.",
      why: "Cube-die, sphere-ball, cone-ice-cream.",
    },
    {
      q: "Drag each real object to its shape.",
      items: [
        [null, "🥫"],
        [null, "📦"],
      ],
      zones: [["cylinder"], ["rectangular prism"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "One is round with flat ends, one is box-shaped.",
      why: "🥫 cylinder, 📦 rectangular prism.",
    },
    {
      q: "Match all five 3D shapes to their names.",
      items: [
        [null, "🎲"],
        [null, "⚽"],
        [null, "🍦"],
        [null, "🥫"],
        [null, "📦"],
      ],
      zones: [["cube"], ["sphere"], ["cone"], ["cylinder"], ["rectangular prism"]],
      key: { 0: [0], 1: [1], 2: [2], 3: [3], 4: [4] },
      d: 5,
      hint: "Think about faces, points and round parts.",
      why: "🎲 cube, ⚽ sphere, 🍦 cone, 🥫 cylinder, 📦 rectangular prism.",
    },
    {
      q: "Drag each real object to its shape.",
      items: [
        [null, "⚽"],
        [null, "🍦"],
      ],
      zones: [["sphere"], ["cone"]],
      key: { 0: [0], 1: [1] },
      d: 2,
      hint: "One is round all over, one comes to a point.",
      why: "⚽ sphere, 🍦 cone.",
    },
  ],
  counts: [
    ["balls (spheres)", "⚽", 6, "Count the balls. Tap each one."],
    ["cans (cylinders)", "🥫", 5, "Count the cans. Tap each one."],
  ],
  reads: [
    "A cube has six flat faces.",
    "A sphere has no flat faces.",
    "A cone has one point.",
    "A cylinder has two flat faces.",
    "A rectangular prism has eight corners.",
    "A cylinder has no corners.",
  ],
  writes: [
    [
      "Find a cube-shaped object at home. Draw it.",
      "a dice",
      ["Vẽ vật hình khối lập phương", "Có ghi tên vật"],
    ],
    [
      "Find a cylinder-shaped object at home. Draw it.",
      "a can",
      ["Vẽ vật hình trụ", "Có ghi tên vật"],
    ],
  ],
});

// ═══════════════════════════════════════════════════════════════ three addends ════════════════
sentencePack({
  ...base,
  code: "EMATH.OA.THREE_ADDENDS",
  prefix: "emath-3add",
  src: CCSS("1.OA.A.2", "adding three whole numbers"),
  note: "Cộng ba số có tổng đến 20, chọn cặp làm 10 trước. Ô nhiễu: quên số thứ ba (dem_thieu_1 nếu hụt đúng giá trị số đó không khớp, nên dùng lap_lai_tong cho 'chỉ cộng hai số đầu'), hụt/dư một.",
  items: [
    Q("4 + 6 + 3 = ?", 13, [...DT, "lap_lai_tong"], 2, "4 + 6 = 10 first, then + 3.", {
      g: { rep: 10 },
    }),
    Q("2 + 8 + 5 = ?", 15, [...TD, "lap_lai_tong"], 3, "2 + 8 = 10 first, then + 5.", {
      g: { rep: 10 },
    }),
    Q("7 + 3 + 4 = ?", 14, [...DT, "lap_lai_tong"], 2, "7 + 3 = 10 first, then + 4.", {
      g: { rep: 10 },
    }),
    Q("1 + 9 + 6 = ?", 16, [...TD, "lap_lai_tong"], 3, "1 + 9 = 10 first, then + 6.", {
      g: { rep: 10 },
    }),
    Q("5 + 5 + 4 = ?", 14, DT, 3, "5 + 5 = 10 first, then + 4."),
    Q("6 + 4 + 7 = ?", 17, TD, 4, "6 + 4 = 10 first, then + 7."),
    Q("3 + 7 + 8 = ?", 18, DT, 4, "3 + 7 = 10 first, then + 8."),
    Q("2 + 2 + 5 = ?", 9, TD, 2, "Add in any order: 2 + 2 = 4, then + 5."),
    Q("4 + 4 + 4 = ?", 12, DT, 3, "4 + 4 = 8, then + 4."),
    Q("8 + 2 + 9 = ?", 19, [...TD, "lap_lai_tong"], 5, "8 + 2 = 10 first, then + 9.", {
      g: { rep: 10 },
    }),
    Q("3 + 3 + 3 = ?", 9, DT, 2, "3 + 3 = 6, then + 3."),
    Q("9 + 1 + 8 = ?", 18, [...DT, "lap_lai_tong"], 4, "9 + 1 = 10 first, then + 8.", {
      g: { rep: 10 },
    }),
    Q("5 + 6 + 2 = ?", 13, TD, 4, "Add any two first, then the third."),
    Q("6 + 5 + 5 = ?", 16, DT, 3, "5 + 5 = 10 first, then + 6."),
    Q("7 + 7 + 1 = ?", 15, TD, 3, "7 + 7 = 14, then + 1."),
    Q(
      "2 + 9 + 4 = ?",
      15,
      [...DT, "lap_lai_tong"],
      4,
      "9 + 1 hides inside 2 + 9: try 9 + 4 = 13 first, then + 2.",
      { g: { rep: 9 } },
    ),
    Q("8 + 8 + 2 = ?", 18, DT, 4, "8 + 2 = 10 first, then + 8."),
    Q("1 + 6 + 9 = ?", 16, [...TD, "lap_lai_tong"], 3, "1 + 9 = 10 first, then + 6.", {
      g: { rep: 9 },
    }),
    Q("3 + 3 + 2 = ?", 8, DT, 1, "Add in any order: 3 + 3 = 6, then + 2."),
    Q("2 + 3 + 4 = ?", 9, TD, 1, "Add in any order: 2 + 3 = 5, then + 4."),
    Q("5 + 2 + 2 = ?", 9, DT, 2, "Add in any order: 5 + 2 = 7, then + 2."),
    Q("6 + 1 + 3 = ?", 10, TD, 2, "Add in any order: 6 + 1 = 7, then + 3."),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} says three numbers. Tap the total!",
    "Listen carefully, then choose.",
    "What is the total? Tap it.",
    "Listen again and pick one.",
    "Add all three, then tap.",
  ],
  listens: [
    L("Four plus six plus three.", 13, DT, 2),
    L("Two plus eight plus five.", 15, TD, 3),
    L("Seven plus three plus four.", 14, DT, 3),
    L("Six plus four plus seven.", 17, TD, 4),
    L("Three plus seven plus eight.", 18, DT, 4),
    L("Six plus five plus five.", 16, DT, 3),
    L("Eight plus eight plus two.", 18, TD, 4),
  ],
  builds: [],
  places: [
    {
      q: "Order the steps for 4 + 6 + 3.",
      items: [
        ["Add the third number."],
        ["Find a pair that makes 10."],
        ["Add that pair together."],
      ],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [2], 1: [0], 2: [1] },
      d: 4,
      hint: "Find the pair first, then add it, then add the last number.",
      why: "Find pair, add pair, add third number.",
    },
    {
      q: "Drag the sum: 5 + 5 + 4 =",
      items: [["14"], ["13"], ["15"]],
      zones: [["5 + 5 + 4"]],
      key: { 0: [0] },
      d: 3,
      hint: "5 + 5 = 10, then + 4.",
      why: "5 + 5 + 4 = 14.",
    },
    {
      q: "Drag the sum: 6 + 4 + 7 =",
      items: [["17"], ["16"], ["18"]],
      zones: [["6 + 4 + 7"]],
      key: { 0: [0] },
      d: 4,
      hint: "6 + 4 = 10, then + 7.",
      why: "6 + 4 + 7 = 17.",
    },
    {
      q: "Drag the sum: 9 + 1 + 8 =",
      items: [["18"], ["17"], ["19"]],
      zones: [["9 + 1 + 8"]],
      key: { 0: [0] },
      d: 4,
      hint: "9 + 1 = 10, then + 8.",
      why: "9 + 1 + 8 = 18.",
    },
    {
      q: "Drag the sum: 2 + 8 + 5 =",
      items: [["15"], ["14"], ["16"]],
      zones: [["2 + 8 + 5"]],
      key: { 0: [0] },
      d: 3,
      hint: "2 + 8 = 10, then + 5.",
      why: "2 + 8 + 5 = 15.",
    },
    {
      q: "Match each problem to its make-ten pair.",
      items: [["4 + 6 + 3"], ["2 + 8 + 5"]],
      zones: [["4 + 6"], ["2 + 8"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "Look for the pair that makes 10 first.",
      why: "4+6=10 and 2+8=10.",
    },
    {
      q: "Match each problem to its make-ten pair.",
      items: [["6 + 4 + 7"], ["9 + 1 + 8"]],
      zones: [["6 + 4"], ["9 + 1"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "Look for the pair that makes 10 first.",
      why: "6+4=10 and 9+1=10.",
    },
    {
      q: "3+4+5 has no make-ten pair. Order the steps.",
      items: [
        ["Add the result plus the third number."],
        ["Add any two numbers first."],
        ["Read all three numbers."],
      ],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [2], 1: [1], 2: [0] },
      d: 5,
      hint: "Even with no make-ten pair, add step by step.",
      why: "Read, add two, add the third.",
    },
  ],
  counts: [
    ["red counters", "🔴", 4, "Count the red counters. Tap each one."],
    ["blue counters", "🔵", 6, "Count the blue counters. Tap each one."],
    ["green counters", "🟢", 3, "Count the green counters. Tap each one."],
  ],
});

// ═══════════════════════════════════════════════════════════════ position words ═══════════════
sentencePack({
  ...base,
  code: "EMATH.G.POSITION_WORDS",
  prefix: "emath-position",
  src: CCSS("K.G.A.1", "describing position"),
  note: "Không có mã lỗi cho nhầm above/below/beside/between/behind/in front of, nên vốn từ vị trí luyện chủ yếu bằng kéo-thả (không cần mã lỗi). Vì EMATH luôn bắt buộc ≥6 bài có mã lỗi (docs/04 §11.2), MCQ/LISTEN_CHOOSE ở đây là bài toán lời văn cộng/trừ có bối cảnh dùng đúng từ vị trí — có đáp số thật nên hụt/dư một nói đúng lỗi.",
  items: [
    Q("5 birds are above the tree. 3 more join them.", 8, DT, 1, "Join means add."),
    Q("6 fish swim below the boat. 2 swim away.", 4, TD, 1, "Swim away means take away."),
    Q("4 apples are beside the basket. 3 more are added.", 7, DT, 2, "Added means add."),
    Q("7 cars are in front of the house. 2 drive away.", 5, TD, 2, "Drive away means take away."),
    Q("9 kids stand behind the teacher. 4 walk away.", 5, TD, 3, "Walk away means take away."),
    Q("3 sheep are between two fences. 5 more join them.", 8, DT, 3, "Join means add."),
    Q("8 birds sit above the nest. 3 fly away.", 5, TD, 3, "Fly away means take away."),
    Q("6 toys are beside the bed. 6 more are added.", 12, DT, 4, "Added means add."),
    Q("10 fish swim below the boat. 4 swim away.", 6, TD, 4, "Swim away means take away."),
    Q("5 kids stand in front of the class. 5 more join.", 10, DT, 4, "Join means add."),
    Q("7 cars are behind the truck. 8 more park behind.", 15, DT, 5, "Park behind means add."),
    Q("4 balls are between two chairs. 9 more roll in.", 13, DT, 5, "Roll in means add."),
  ],
  listenPrompts: [
    "Listen to the story, then tap the answer.",
    "{ban} tells a maths story. Tap the answer!",
    "Listen carefully, then choose.",
    "How many? Tap it.",
    "Listen to the whole story first.",
    "Listen again and pick one.",
  ],
  listens: [
    L("Five birds are above the tree. Three more join them.", 8, DT, 1),
    L("Six fish swim below the boat. Two swim away.", 4, TD, 2),
    L("Four apples are beside the basket. Three more are added.", 7, DT, 2),
    L("Nine kids stand behind the teacher. Four walk away.", 5, TD, 3),
    L("Three sheep are between two fences. Five more join them.", 8, DT, 4),
    L("Six toys are beside the bed. Six more are added.", 12, DT, 4),
  ],
  builds: [],
  places: [
    {
      q: "Drag each picture to the right position word.",
      items: [["🐦 above the tree"], ["🐱 below the table"]],
      zones: [["above"], ["below"]],
      key: { 0: [0], 1: [1] },
      d: 1,
      hint: "One is higher up, one is lower down.",
      why: "Bird is above, cat is below.",
    },
    {
      q: "Drag each picture to the right position word.",
      items: [["🐶 beside the box"], ["🍎 between two fruits"]],
      zones: [["beside"], ["between"]],
      key: { 0: [0], 1: [1] },
      d: 1,
      hint: "One is next to, one is in the middle.",
      why: "Dog is beside, apple is between.",
    },
    {
      q: "Drag each picture to the right position word.",
      items: [["🚗 behind the bus"], ["🐇 in front of the turtle"]],
      zones: [["behind"], ["in front of"]],
      key: { 0: [0], 1: [1] },
      d: 1,
      hint: "One is at the back, one is ahead.",
      why: "Car is behind, rabbit is in front.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["picture hangs above the door"], ["shoes are below the bed"]],
      zones: [["above"], ["below"]],
      key: { 0: [0], 1: [1] },
      d: 2,
      hint: "One is higher, one is underneath.",
      why: "Picture is above, shoes are below.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["lamp is beside the sofa"], ["apple is between banana and orange"]],
      zones: [["beside"], ["between"]],
      key: { 0: [0], 1: [1] },
      d: 2,
      hint: "One is next to, one is in the middle.",
      why: "Lamp is beside, apple is between.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["dog hides behind the sofa"], ["stand in front of the line"]],
      zones: [["behind"], ["in front of"]],
      key: { 0: [0], 1: [1] },
      d: 2,
      hint: "One is at the back, one is ahead.",
      why: "Dog is behind, standing first is in front.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["clock hangs above the shelf"], ["rug is below the table"]],
      zones: [["above"], ["below"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "One is higher, one is underneath.",
      why: "Clock is above, rug is below.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["bike is beside the car"], ["bear stands between rabbit and fox"]],
      zones: [["beside"], ["between"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "One is next to, one is in the middle.",
      why: "Bike is beside, bear is between.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["backpack is behind the chair"], ["teacher stands in front of the class"]],
      zones: [["behind"], ["in front of"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "One is at the back, one faces ahead.",
      why: "Backpack is behind, teacher is in front.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["bird flies above the clouds"], ["fish swims below the boat"]],
      zones: [["above"], ["below"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "One is higher up, one is lower down.",
      why: "Bird is above, fish is below.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["fish swims between two rocks"], ["elephant walks behind the monkey"]],
      zones: [["between"], ["behind"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "One is in the middle, one is at the back.",
      why: "Fish is between, elephant is behind.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["moon is above the mountains"], ["roots are below the ground"]],
      zones: [["above"], ["below"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "One is high in the sky, one is underneath.",
      why: "Moon is above, roots are below.",
    },
    {
      q: "Match all six pictures to their position words.",
      items: [
        ["bird above the tree"],
        ["cat below the table"],
        ["dog beside the box"],
        ["apple between two fruits"],
        ["car behind the bus"],
        ["rabbit in front of the turtle"],
      ],
      zones: [["above"], ["below"], ["beside"], ["between"], ["behind"], ["in front of"]],
      key: { 0: [0], 1: [1], 2: [2], 3: [3], 4: [4], 5: [5] },
      d: 5,
      hint: "Think carefully about each picture.",
      why: "Each picture matches one position word.",
    },
    {
      q: "Match all six pictures to their position words.",
      items: [
        ["picture above the door"],
        ["shoes below the bed"],
        ["lamp beside the sofa"],
        ["bear between rabbit and fox"],
        ["backpack behind the chair"],
        ["teacher in front of the class"],
      ],
      zones: [["above"], ["below"], ["beside"], ["between"], ["behind"], ["in front of"]],
      key: { 0: [0], 1: [1], 2: [2], 3: [3], 4: [4], 5: [5] },
      d: 5,
      hint: "Think carefully about each picture.",
      why: "Each picture matches one position word.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["🐘 behind 🐒"], ["🚲 beside 🚗"]],
      zones: [["behind"], ["beside"]],
      key: { 0: [0], 1: [1] },
      d: 2,
      hint: "One is at the back, one is right next to.",
      why: "Elephant is behind, bike is beside.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["🐟 between two rocks"], ["🐻 between 🐰 and 🦊"]],
      zones: [["between"], ["between"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "Both pictures show something in the middle.",
      why: "Fish and bear are both between two things.",
    },
    {
      q: "Drag each picture to the right word.",
      items: [["🌙 above the mountains"], ["🌱 roots below the ground"]],
      zones: [["above"], ["below"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "One is high, one is underneath.",
      why: "Moon is above, roots are below.",
    },
  ],
  counts: [
    ["birds sitting above the branch", "🐦", 7, "Count the birds above the branch."],
    ["fish swimming below the boat", "🐟", 6, "Count the fish below the boat."],
    ["cars parked beside the road", "🚗", 5, "Count the cars beside the road."],
  ],
  reads: [
    "The bird sits above the tree.",
    "The cat is below the table.",
    "The lamp is beside the sofa.",
    "The apple is between the banana and the orange.",
    "The car is behind the bus.",
    "The rabbit is in front of the turtle.",
    "The clock hangs above the shelf.",
    "The bike is parked beside the car.",
    "The backpack is behind the chair.",
    "The teacher stands in front of the class.",
    "The moon is above the mountains.",
    "The roots are below the ground.",
  ],
  writes: [
    [
      "Draw a picture with something above and something below.",
      "a bird above, a cat below",
      ["Có tranh", "Đúng above và below"],
    ],
    [
      "Draw a picture with something beside and something between.",
      "a lamp beside, an apple between",
      ["Có tranh", "Đúng beside và between"],
    ],
    [
      "Draw a picture with something behind and something in front.",
      "a dog behind, a rabbit in front",
      ["Có tranh", "Đúng behind và in front of"],
    ],
  ],
});

// ═══════════════════════════════════════════════════════════════ subtract within 20 ═══════════
sentencePack({
  ...base,
  code: "EMATH.OA.SUB_WITHIN_20",
  prefix: "emath-sub20",
  src: CCSS("1.OA.C.6", "subtract within 20"),
  note: "Trừ trong phạm vi 20 bằng đếm lùi, trừ về 10, hoặc nghĩ phép cộng. Ô nhiễu: hụt/dư một, làm ngược phép tính (cộng thay vì trừ).",
  items: [
    Q("15 - 8 = ?", 7, [...DT, "nham_cong_tru"], 2, "Think: 8 + ? = 15.", { g: { opp: 23 } }),
    Q(
      "13 - 5 = ?",
      8,
      [...TD, "nham_cong_tru"],
      2,
      "Subtract to 10 first: 13 - 3 = 10, then - 2.",
      { g: { opp: 18 } },
    ),
    Q("16 - 9 = ?", 7, [...DT, "nham_cong_tru"], 3, "Think: 9 + ? = 16.", { g: { opp: 25 } }),
    Q(
      "14 - 6 = ?",
      8,
      [...TD, "nham_cong_tru"],
      3,
      "Subtract to 10 first: 14 - 4 = 10, then - 2.",
      { g: { opp: 20 } },
    ),
    Q("12 - 7 = ?", 5, [...DT, "nham_cong_tru"], 2, "Think: 7 + ? = 12.", { g: { opp: 19 } }),
    Q("17 - 8 = ?", 9, TD, 3, "Subtract to 10 first, then subtract more."),
    Q("18 - 9 = ?", 9, DT, 3, "Think: 9 + ? = 18."),
    Q("11 - 4 = ?", 7, TD, 2, "Subtract to 10 first: 11 - 1 = 10, then - 3."),
    Q("15 - 7 = ?", 8, DT, 3, "Think: 7 + ? = 15."),
    Q("13 - 9 = ?", 4, TD, 4, "Think: 9 + ? = 13."),
    Q("14 - 8 = ?", 6, DT, 4, "Subtract to 10 first: 14 - 4 = 10, then - 4."),
    Q("16 - 7 = ?", 9, TD, 4, "Think: 7 + ? = 16."),
    Q("19 - 9 = ?", 10, DT, 3, "Think: 9 + ? = 19."),
    Q("12 - 5 = ?", 7, TD, 3, "Subtract to 10 first: 12 - 2 = 10, then - 3."),
    Q("17 - 9 = ?", 8, DT, 4, "Think: 9 + ? = 17."),
    {
      q: "13 - 5: which fact helps you check?",
      right: "5 + 8 = 13",
      wrongs: [
        ["5 - 8 = 13", "nham_cong_tru"],
        ["13 + 5 = 18", "nham_cong_tru"],
      ],
      d: 5,
      hint: "Subtraction and addition are related.",
    },
    Q(
      "13 - 6 = ?",
      7,
      [...DT, "nham_cong_tru"],
      3,
      "Subtract to 10 first: 13 - 3 = 10, then - 3.",
      { g: { opp: 19 } },
    ),
    Q("15 - 9 = ?", 6, [...TD, "nham_cong_tru"], 3, "Think: 9 + ? = 15.", { g: { opp: 24 } }),
    Q("11 - 5 = ?", 6, DT, 2, "Subtract to 10 first: 11 - 1 = 10, then - 4."),
    Q("18 - 8 = ?", 10, TD, 3, "Subtract to 10 first: 18 - 8 = 10."),
    Q("16 - 8 = ?", 8, DT, 3, "Think: 8 + ? = 16."),
    Q("17 - 6 = ?", 11, TD, 4, "Think: 6 + ? = 17."),
    Q("5 - 2 = ?", 3, DT, 1, "Count back 2 from 5."),
    Q("6 - 3 = ?", 3, TD, 1, "Count back 3 from 6."),
  ],
  listenPrompts: [
    "Listen and tap the answer.",
    "{ban} says a subtraction. Tap the answer!",
    "Listen carefully, then choose.",
    "What is the answer? Tap it.",
    "Listen again and pick a number.",
    "Tap the number you worked out.",
  ],
  listens: [
    L("Fifteen minus eight.", 7, DT, 2),
    L("Thirteen minus five.", 8, TD, 2),
    L("Sixteen minus nine.", 7, DT, 3),
    L("Fourteen minus six.", 8, TD, 3),
    L("Eighteen minus nine.", 9, DT, 3),
    L("Seventeen minus eight.", 9, TD, 3),
    L("Nineteen minus nine.", 10, DT, 4),
    L("Thirteen minus six.", 7, DT, 3),
    L("Eighteen minus eight.", 10, TD, 3),
    L("Five minus two.", 3, DT, 1),
  ],
  builds: [],
  places: [
    {
      q: "Drag the answer: 15 - 8 =",
      items: [["7"], ["8"], ["6"]],
      zones: [["15 - 8"]],
      key: { 0: [0] },
      d: 2,
      hint: "Think: 8 + ? = 15.",
      why: "15 - 8 = 7.",
    },
    {
      q: "Drag the answer: 14 - 6 =",
      items: [["8"], ["9"], ["7"]],
      zones: [["14 - 6"]],
      key: { 0: [0] },
      d: 3,
      hint: "Subtract to 10 first.",
      why: "14 - 6 = 8.",
    },
    {
      q: "Drag the answer: 16 - 7 =",
      items: [["9"], ["8"], ["10"]],
      zones: [["16 - 7"]],
      key: { 0: [0] },
      d: 4,
      hint: "Think: 7 + ? = 16.",
      why: "16 - 7 = 9.",
    },
    {
      q: "Drag the answer: 13 - 9 =",
      items: [["4"], ["5"], ["3"]],
      zones: [["13 - 9"]],
      key: { 0: [0] },
      d: 4,
      hint: "Think: 9 + ? = 13.",
      why: "13 - 9 = 4.",
    },
  ],
  counts: [
    ["stars left after crossing some out", "⭐", 7, "Count the stars still left. Tap each one."],
    ["apples left on the tree", "🍎", 5, "Count the apples still left. Tap each one."],
  ],
});

// ═══════════════════════════════════════════════════════════════ equal sign meaning ═══════════
sentencePack({
  ...base,
  code: "EMATH.OA.EQUAL_SIGN_MEANING",
  prefix: "emath-eqsign",
  src: CCSS("1.OA.D.7", "understanding the equal sign"),
  note: "Dấu = nghĩa là 'bằng nhau' hai vế. Không có mã lỗi cho 'hiểu sai dấu bằng' nên câu true/false (chấm đúng-sai, không phải số) chuyển hết sang kéo-thả (DRAG_DROP không cần mã lỗi); MCQ/LISTEN_CHOOSE chỉ dùng cho dạng 'tìm số còn thiếu' — có đáp số thật, hụt/dư một nói đúng lỗi.",
  items: [
    Q("? + 2 = 3 + 4", 5, DT, 3, "3 + 4 = 7, so ? + 2 must also be 7."),
    Q("6 = ? - 2", 8, DT, 3, "? - 2 must equal 6."),
    Q("4 + 3 = 2 + ?", 5, DT, 3, "4 + 3 = 7, so 2 + ? must also be 7."),
    Q("9 = ? + 4", 5, DT, 3, "? + 4 must equal 9."),
    Q("? + 3 = 5 + 5", 7, DT, 4, "5 + 5 = 10, so ? + 3 must also be 10."),
    Q("10 = ? + 6", 4, DT, 3, "? + 6 must equal 10."),
    Q("? + 4 = 7 + 2", 5, DT, 4, "7 + 2 = 9, so ? + 4 must also be 9."),
    Q("12 = ? + 7", 5, DT, 5, "? + 7 must equal 12."),
    Q("? + 5 = 6 + 6", 7, DT, 5, "6 + 6 = 12, so ? + 5 must also be 12."),
    Q("? + 1 = 2 + 3", 4, DT, 1, "2 + 3 = 5, so ? + 1 must also be 5."),
    Q("4 = ? + 1", 3, DT, 2, "? + 1 must equal 4."),
    Q("? + 3 = 8 + 1", 6, DT, 4, "8 + 1 = 9, so ? + 3 must also be 9."),
  ],
  listenPrompts: [
    "Listen, then tap the missing number.",
    "{ban} says a number sentence. Tap the missing number!",
    "Listen carefully, then choose.",
    "What number is missing? Tap it.",
    "Listen again and pick one.",
    "Work out both sides, then tap.",
  ],
  listens: [
    L("Three plus four equals what plus two?", 5, DT, 3),
    L("Six equals what minus two?", 8, DT, 3),
    L("Nine equals what plus four?", 5, DT, 3),
    L("Ten equals what plus six?", 4, DT, 3),
    L("Two plus three equals what plus one?", 4, DT, 1),
    L("Seven plus two equals what plus four?", 5, DT, 4),
  ],
  builds: [],
  places: [
    {
      q: "Sort the equations: true or false?",
      items: [["6 = 6"], ["7 = 8 - 1"], ["6 + 3 = 10"]],
      zones: [["true"], ["true"], ["false"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 1,
      hint: "Work out both sides of each equation.",
      why: "6=6 true, 8-1=7 true, 6+3=9 not 10.",
    },
    {
      q: "Sort the equations: true or false?",
      items: [["5 + 2 = 2 + 5"], ["10 - 4 = 5"], ["4 + 1 = 5 + 0"]],
      zones: [["true"], ["false"], ["true"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 2,
      hint: "Work out both sides of each equation.",
      why: "5+2=2+5 true, 10-4=6 not 5, both sides equal 5.",
    },
    {
      q: "Sort the equations: true or false?",
      items: [["12 = 6 + 6"], ["4 + 4 = 9"], ["7 + 0 = 7"]],
      zones: [["true"], ["false"], ["true"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 3,
      hint: "Work out both sides of each equation.",
      why: "6+6=12 true, 4+4=8 not 9, 7+0=7 true.",
    },
    {
      q: "Sort the equations: true or false?",
      items: [["8 = 3 + 5"], ["9 - 2 = 3 + 4"], ["3 + 4 = 4 + 3"]],
      zones: [["true"], ["true"], ["true"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 3,
      hint: "Work out both sides of each equation.",
      why: "8=3+5, 9-2=7=3+4, both sides always equal 7.",
    },
    {
      q: "Sort the equations: true or false?",
      items: [["2 + 6 = 6 + 2"], ["9 = 9 + 0"], ["15 - 5 = 10"]],
      zones: [["true"], ["true"], ["true"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 3,
      hint: "Work out both sides of each equation.",
      why: "All three equations are true.",
    },
    {
      q: "Sort the equations: true or false?",
      items: [["8 - 3 = 4 + 1"], ["2 + 3 + 1 = 6"], ["10 = 4 + 5"]],
      zones: [["true"], ["true"], ["false"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 4,
      hint: "Work out both sides of each equation.",
      why: "8-3=5=4+1, 2+3+1=6, but 4+5=9 not 10.",
    },
    {
      q: "Sort the equations: true or false?",
      items: [["11 = 5 + 6"], ["3 + 6 = 8"], ["14 = 20 - 6"]],
      zones: [["true"], ["false"], ["true"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 4,
      hint: "Work out both sides of each equation.",
      why: "5+6=11 true, 3+6=9 not 8, 20-6=14 true.",
    },
    {
      q: "Sort the equations: true or false?",
      items: [["4 + 1 = 5 + 0"], ["6 + 3 = 10"], ["10 - 4 = 5"]],
      zones: [["true"], ["false"], ["false"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 2,
      hint: "Work out both sides of each equation.",
      why: "4+1=5=5+0 true, 6+3=9 not 10, 10-4=6 not 5.",
    },
  ],
  reads: [
    "Six equals six.",
    "Seven equals eight minus one.",
    "Five plus two equals two plus five.",
    "Eight equals three plus five.",
    "Nine equals nine plus zero.",
    "Twelve equals six plus six.",
    "Eleven equals five plus six.",
    "Fourteen equals twenty minus six.",
    "Three plus four equals four plus three.",
  ],
});

// ═══════════════════════════════════════════════════════════════ unknown in equation ══════════
sentencePack({
  ...base,
  code: "EMATH.OA.UNKNOWN_IN_EQUATION",
  prefix: "emath-unknown",
  src: CCSS("1.OA.D.8", "determine the unknown number"),
  note: "Tìm số chưa biết ở bất kỳ vị trí nào trong phép tính. Ô nhiễu: cộng hai số đã cho thay vì tìm số thiếu (nham_cong_tru), hụt/dư một.",
  items: [
    Q("8 + ? = 11", 3, [...DT, "nham_cong_tru"], 2, "Think: what plus 8 makes 11?", {
      g: { opp: 19 },
    }),
    Q("? - 3 = 6", 9, [...TD, "nham_cong_tru"], 3, "Think: what number, minus 3, is 6?", {
      g: { opp: 3 },
    }),
    Q("5 = ? - 2", 7, [...DT, "nham_cong_tru"], 3, "Think: what number, minus 2, is 5?", {
      g: { opp: 3 },
    }),
    Q("7 + ? = 10", 3, [...TD, "nham_cong_tru"], 2, "Think: what plus 7 makes 10?", {
      g: { opp: 17 },
    }),
    Q("? + 4 = 9", 5, [...DT, "nham_cong_tru"], 2, "Think: what plus 4 makes 9?", {
      g: { opp: 13 },
    }),
    Q("12 - ? = 5", 7, [...TD, "nham_cong_tru"], 4, "Think: 12 minus what is 5?", {
      g: { opp: 17 },
    }),
    Q("? + 6 = 14", 8, [...DT, "nham_cong_tru"], 4, "Think: what plus 6 makes 14?", {
      g: { opp: 20 },
    }),
    Q("9 = 5 + ?", 4, TD, 3, "Think: 5 plus what makes 9?"),
    Q("6 + ? = 13", 7, DT, 3, "Think: what plus 6 makes 13?"),
    Q("? - 5 = 8", 13, TD, 4, "Think: what number, minus 5, is 8?"),
    Q("14 = ? + 8", 6, DT, 4, "Think: 8 plus what makes 14?"),
    Q("10 - ? = 4", 6, TD, 3, "Think: 10 minus what is 4?"),
    Q("? + 9 = 15", 6, DT, 4, "Think: what plus 9 makes 15?"),
    {
      q: "8 + ? = 11. What is the first step?",
      right: "think what plus 8 makes 11",
      wrongs: [["add 8 and 11", "nham_cong_tru"], ["subtract 8 from itself"]],
      d: 4,
      hint: "You need the missing part, not the total.",
    },
    {
      q: "Which fact matches ? - 3 = 6?",
      right: "9 - 3 = 6",
      wrongs: [
        ["6 - 3 = 3", "nham_cong_tru"],
        ["3 - 9 = 6", "nham_cong_tru"],
      ],
      d: 5,
      hint: "Try the answer choices in place of the blank.",
    },
    Q("? + 7 = 12", 5, [...DT, "nham_cong_tru"], 3, "Think: what plus 7 makes 12?", {
      g: { opp: 19 },
    }),
    Q("15 = ? + 9", 6, [...TD, "nham_cong_tru"], 4, "Think: 9 plus what makes 15?", {
      g: { opp: 24 },
    }),
    Q("? - 4 = 7", 11, DT, 3, "Think: what number, minus 4, is 7?"),
    Q("13 - ? = 8", 5, TD, 4, "Think: 13 minus what is 8?"),
    Q("? + 3 = 8", 5, DT, 2, "Think: what plus 3 makes 8?"),
    Q("16 - ? = 9", 7, TD, 4, "Think: 16 minus what is 9?"),
    {
      q: "13 - ? = 8. What is the first step?",
      right: "think what plus 8 makes 13",
      wrongs: [["subtract 13 and 8", "nham_cong_tru"], ["add 13 and 8"]],
      d: 5,
      hint: "Turn it into an addition question.",
    },
    Q("? + 2 = 5", 3, DT, 1, "Think: what plus 2 makes 5?"),
    Q("4 + ? = 6", 2, TD, 1, "Think: what plus 4 makes 6?"),
  ],
  listenPrompts: [
    "Listen, then tap the missing number.",
    "{ban} says a number sentence. Tap the missing number!",
    "Listen carefully, then choose.",
    "What number is missing? Tap it.",
    "Listen again and pick one.",
    "Find the missing number, then tap.",
  ],
  listens: [
    L("What number plus two makes five?", 3, DT, 1),
    L("Eight plus what number makes eleven?", 3, DT, 2),
    L("What number minus three is six?", 9, TD, 3),
    L("Seven plus what number makes ten?", 3, DT, 2),
    L("What number plus four makes nine?", 5, TD, 2),
    L("Twelve minus what number is five?", 7, DT, 4),
    L("What number plus six makes fourteen?", 8, TD, 4),
    L("What number plus seven makes twelve?", 5, DT, 3),
    L("Fifteen minus what number is nine?", 6, TD, 4),
  ],
  builds: [],
  places: [
    {
      q: "Drag the missing number: 8 + ? = 11",
      items: [["3"], ["4"], ["19"]],
      zones: [["8 + ? = 11"]],
      key: { 0: [0] },
      d: 2,
      hint: "What plus 8 makes 11?",
      why: "8 + 3 = 11.",
    },
    {
      q: "Drag the missing number: ? - 3 = 6",
      items: [["9"], ["3"], ["6"]],
      zones: [["? - 3 = 6"]],
      key: { 0: [0] },
      d: 3,
      hint: "What number, minus 3, is 6?",
      why: "9 - 3 = 6.",
    },
    {
      q: "Drag the missing number: 7 + ? = 10",
      items: [["3"], ["17"], ["7"]],
      zones: [["7 + ? = 10"]],
      key: { 0: [0] },
      d: 2,
      hint: "What plus 7 makes 10?",
      why: "7 + 3 = 10.",
    },
    {
      q: "Drag the missing number: 12 - ? = 5",
      items: [["7"], ["17"], ["5"]],
      zones: [["12 - ? = 5"]],
      key: { 0: [0] },
      d: 4,
      hint: "12 minus what is 5?",
      why: "12 - 7 = 5.",
    },
    {
      q: "Drag the missing number: ? + 6 = 14",
      items: [["8"], ["20"], ["6"]],
      zones: [["? + 6 = 14"]],
      key: { 0: [0] },
      d: 4,
      hint: "What plus 6 makes 14?",
      why: "8 + 6 = 14.",
    },
  ],
  counts: [
    ["counters needed to reach 12", "🟡", 5, "Count how many more counters make 12. Tap each one."],
    ["counters needed to reach 9", "🟢", 4, "Count how many more counters make 9. Tap each one."],
  ],
});

// ═══════════════════════════════════════════════════════════════ word problems add/sub ════════
sentencePack({
  ...base,
  code: "EMATH.OA.WORD_PROBLEMS_ADD_SUB",
  prefix: "emath-wordadd",
  src: CCSS("1.OA.A.1", "add to, take from, put together, take apart"),
  note: "Bài toán lời văn cộng/trừ trong phạm vi 20 (add to, take from, put together, take apart). Ô nhiễu: chọn phép ngược (nham_cong_tru), chép lại số trong đề (lap_lai_tong), hiểu sai từ khoá (khong_hieu_de_loi_van).",
  items: [
    Q(
      "Sam has 6 cars. He gets 3 more. How many cars now?",
      9,
      ["lap_lai_tong", "dem_thieu_1"],
      1,
      "Gets more means add.",
      { g: { rep: 6 } },
    ),
    Q(
      "Mia has 14 stickers. She gives away 5. How many left?",
      9,
      ["lap_lai_tong", "dem_thua_1"],
      2,
      "Gives away means take away.",
      { g: { rep: 14 } },
    ),
    Q(
      "There are 8 ducks. 5 more come. How many ducks now?",
      13,
      ["lap_lai_tong", "dem_thieu_1"],
      2,
      "More come means add.",
      { g: { rep: 8 } },
    ),
    Q(
      "16 cookies. We eat 7. How many are left?",
      9,
      ["lap_lai_tong", "dem_thua_1"],
      3,
      "Eat means take away.",
      { g: { rep: 16 } },
    ),
    Q(
      "6 red fish and 8 gold fish. How many fish in all?",
      14,
      ["lap_lai_tong", "dem_thieu_1"],
      3,
      "Put both groups together.",
      { g: { rep: 8 } },
    ),
    Q(
      "15 kids play. 6 go home. How many still play?",
      9,
      ["lap_lai_tong", "dem_thua_1"],
      4,
      "Go home means take away.",
      { g: { rep: 15 } },
    ),
    Q(
      "Ben has 12 stickers. Ann has 7. How many more has Ben?",
      5,
      ["lap_lai_tong", "dem_thua_1"],
      5,
      "How many more: find the difference.",
      { g: { rep: 7 } },
    ),
    Q(
      "9 birds sit. 3 fly away, then 2 more. How many left?",
      4,
      ["dem_thua_1", "lap_lai_tong"],
      5,
      "Take away 3, then take away 2.",
      { g: { rep: 9 } },
    ),
    Q(
      "9 apples. Some are eaten. 4 are left. How many eaten?",
      5,
      ["lap_lai_tong", "dem_thua_1"],
      5,
      "Think: 9 take away what leaves 4?",
      { g: { rep: 9 } },
    ),
    Q(
      "5 red balls and some blue balls make 13. How many blue?",
      8,
      ["lap_lai_tong", "dem_thua_1"],
      5,
      "Think: 5 plus what makes 13?",
      { g: { rep: 5 } },
    ),
    {
      q: "'How many are left?' What do you do?",
      right: "take away",
      wrongs: [
        ["add", "nham_cong_tru"],
        ["count the words", "khong_hieu_de_loi_van"],
      ],
      d: 2,
      hint: "Left means some went away.",
    },
    {
      q: "'How many in all?' What do you do?",
      right: "add",
      wrongs: [
        ["take away", "nham_cong_tru"],
        ["pick the biggest number", "khong_hieu_de_loi_van"],
      ],
      d: 2,
      hint: "In all means put together.",
    },
    {
      q: "'How many more' means you should...",
      right: "find the difference",
      wrongs: [
        ["add both numbers", "nham_cong_tru"],
        ["repeat the bigger number", "khong_hieu_de_loi_van"],
      ],
      d: 4,
      hint: "Compare the two amounts by subtracting.",
    },
    {
      q: "Sam has 6 cars. He gets 3 more. What is the question?",
      right: "How many cars now?",
      wrongs: [
        ["He gets 3 more.", "khong_hieu_de_loi_van"],
        ["Sam has 6 cars.", "khong_hieu_de_loi_van"],
      ],
      d: 3,
      hint: "The question ends with a question mark.",
    },
    {
      q: "16 cookies. We eat 7. Which numbers do you use?",
      right: "16 and 7",
      wrongs: [
        ["16 and 23", "nham_cong_tru"],
        ["7 and 9", "khong_hieu_de_loi_van"],
      ],
      d: 4,
      hint: "Find the numbers in the story.",
    },
    {
      q: "Mia has 14 stickers. She gives 5 away. Which fact?",
      right: "14 - 5 = 9",
      wrongs: [
        ["14 + 5 = 19", "nham_cong_tru"],
        ["5 - 14 = 9", "nham_thu_tu_so"],
      ],
      d: 4,
      hint: "Gives away means take away.",
    },
    {
      q: "6 cats and 3 more come. Which fact?",
      right: "6 + 3 = 9",
      wrongs: [
        ["6 - 3 = 3", "nham_cong_tru"],
        ["6 + 3 = 8", "dem_thieu_1"],
      ],
      d: 5,
      hint: "More come means add.",
    },
    Q(
      "There are 7 apples and 6 oranges. How many fruits in all?",
      13,
      ["lap_lai_tong", "dem_thieu_1"],
      3,
      "Put both groups together.",
      { g: { rep: 7 } },
    ),
    Q(
      "A shelf has 18 books. 9 are borrowed. How many are left?",
      9,
      ["lap_lai_tong", "dem_thua_1"],
      4,
      "Borrowed means taken away.",
      { g: { rep: 18 } },
    ),
    Q(
      "Lan has 8 candies. She gets 9 more. How many now?",
      17,
      ["lap_lai_tong", "dem_thieu_1"],
      3,
      "Gets more means add.",
      { g: { rep: 8 } },
    ),
    {
      q: "'She gives some away' means you should...",
      right: "subtract",
      wrongs: [
        ["add", "nham_cong_tru"],
        ["multiply", "khong_hieu_de_loi_van"],
      ],
      d: 2,
      hint: "Giving away means some are taken.",
    },
    {
      q: "A shelf has 18 books, 9 are borrowed. Which fact?",
      right: "18 - 9 = 9",
      wrongs: [
        ["18 + 9 = 27", "nham_cong_tru"],
        ["9 - 18 = 9", "nham_thu_tu_so"],
      ],
      d: 4,
      hint: "Borrowed means take away.",
    },
    Q(
      "Farmer has 9 hens and 8 ducks. How many birds in all?",
      17,
      ["lap_lai_tong", "dem_thieu_1"],
      3,
      "Put both groups together.",
      { g: { rep: 9 } },
    ),
  ],
  listenPrompts: [
    "Listen to the story, then tap the answer.",
    "{ban} tells a maths story. Tap the answer!",
    "Listen carefully, then choose.",
    "How many? Tap it.",
    "Listen to the whole story first.",
    "Listen again and pick one.",
  ],
  listens: [
    L(
      "Tom has eight apples. He gets five more. How many apples now?",
      13,
      ["lap_lai_tong", "dem_thieu_1"],
      2,
      { rep: 8 },
    ),
    L(
      "There are fourteen frogs. Six jump away. How many are left?",
      8,
      ["lap_lai_tong", "dem_thua_1"],
      3,
      { rep: 6 },
    ),
    L(
      "Seven girls and six boys play. How many children in all?",
      13,
      ["lap_lai_tong", "dem_thieu_1"],
      3,
      { rep: 6 },
    ),
    L(
      "Sixteen balloons. Nine pop. How many balloons are left?",
      7,
      ["lap_lai_tong", "dem_thua_1"],
      4,
      { rep: 9 },
    ),
    L(
      "Lily reads eight books on Monday and five on Tuesday. How many books?",
      13,
      ["lap_lai_tong", "dem_thua_1"],
      3,
      { rep: 5 },
    ),
    L(
      "Twelve bees. Five fly to a flower. How many are not on the flower?",
      7,
      ["lap_lai_tong", "dem_thua_1"],
      4,
      { rep: 5 },
    ),
    L(
      "Nine red cars and eight blue cars. How many cars in all?",
      17,
      ["lap_lai_tong", "dem_thieu_1"],
      4,
      { rep: 8 },
    ),
  ],
  builds: [],
  places: [
    {
      q: "Match the story to the right operation.",
      items: [["He gets 3 more."], ["She gives 5 away."]],
      zones: [["add"], ["subtract"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "Getting more is add; giving away is subtract.",
      why: "Gets more = add, gives away = subtract.",
    },
    {
      q: "Match the story to the right operation.",
      items: [["Two groups put together."], ["Some go away, how many are left?"]],
      zones: [["add"], ["subtract"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "Putting together is add; how many left is subtract.",
      why: "Put together = add, left = subtract.",
    },
    {
      q: "Match the story to the right operation.",
      items: [["9 are borrowed from the shelf."], ["Lan gets 9 more candies."]],
      zones: [["subtract"], ["add"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "Borrowed means gone; gets more means add.",
      why: "Borrowed = subtract, gets more = add.",
    },
  ],
  writes: [
    [
      "Write your own word problem where the answer is 9.",
      "I had 5 balloons. I got 4 more. How many now?",
      ["Có đủ hai số", "Câu hỏi rõ ràng", "Đáp số đúng 9"],
    ],
    [
      "Write your own word problem where you subtract.",
      "I had 12 candies. I ate 4. How many are left?",
      ["Có tình huống trừ", "Đáp số đúng"],
    ],
  ],
});
