/**
 * Đợt 3, lô E2 — English Maths: hình phẳng (gọi tên, đặc điểm, ghép hình), quy luật, từ vựng toán,
 * đọc đề toán tiếng Anh. Nguồn: chuẩn CCSS trong bản đồ kỹ năng — trường chưa có giáo trình.
 *
 * Bộ mã lỗi toán không có mã "gọi nhầm tên hình", nên nhận dạng hình đi bằng kéo-thả thẻ tranh
 * (không in tên hình trên thẻ), còn trắc nghiệm hỏi thứ đếm được: số cạnh, số góc, số hình ghép —
 * nơi dem_thieu_1 / dem_thua_1 nói đúng lỗi. Không có hình thang (trapezoid): emoji không vẽ được.
 *
 *   node scripts/content-gen/emath-dot3b.mjs
 */
import { sentencePack } from "./lib-en.mjs";

const base = { dir: "emath", subject: "EMATH" };
const CCSS = (std, topic) => `CCSS ${std} (${topic}) — chưa có giáo trình English Maths của trường`;
function N(ans, kinds, g = {}) {
  const out = [];
  for (const k of kinds) {
    const v = {
      dem_thieu_1: ans - 1,
      dem_thua_1: ans + 1,
      nham_cong_tru: g.opp,
      lap_lai_tong: g.rep,
    }[k];
    if (v == null || v < 0 || v === ans || out.some(([t]) => t === String(v))) continue;
    out.push([String(v), k]);
    if (out.length === 2) break;
  }
  if (!out.length) out.push([String(ans + 1), "dem_thua_1"]);
  return out;
}
const DT = ["dem_thieu_1", "dem_thua_1"];
const TD = ["dem_thua_1", "dem_thieu_1"];
const Q = (q, ans, kinds, d, hint, extra = {}) => ({
  q,
  right: String(ans),
  wrongs: N(ans, kinds, extra.g),
  d,
  hint,
  ...extra,
});
const L = (say, ans, kinds, d, q, g) => ({
  say,
  right: String(ans),
  wrongs: N(ans, kinds, g),
  d,
  ...(q ? { q } : {}),
});
const SH = { circle: "🔴", square: "🟦", triangle: "🔺", rectangle: "▬", hexagon: "⬢", star: "⭐" };

// ─────────────────────────────────────────────────────────── gọi tên hình ────────────────────
sentencePack({
  ...base,
  code: "EMATH.G.NAME_2D_SHAPES",
  prefix: "emath-shapename",
  src: CCSS("K.G.A.2", "naming shapes"),
  note: "Gọi tên circle, square, triangle, rectangle, hexagon. Nhận dạng bằng kéo thẻ tranh (thẻ không in tên) vào ô tên hình; trắc nghiệm đếm số hình, số cạnh. Không có trapezoid: emoji không vẽ được, sẽ bổ sung khi có tranh.",
  items: [
    Q("How many triangles?", 3, DT, 1, "Touch each triangle as you count.", {
      pic: [SH.triangle, 3],
    }),
    Q("How many circles?", 5, TD, 1, "Touch each circle as you count.", { pic: [SH.circle, 5] }),
    Q("How many squares?", 4, DT, 2, "Touch each square as you count.", { pic: [SH.square, 4] }),
    Q("How many hexagons?", 2, TD, 2, "Touch each hexagon as you count.", { pic: [SH.hexagon, 2] }),
    Q("How many rectangles?", 6, DT, 3, "Touch each rectangle as you count.", {
      pic: [SH.rectangle, 6],
    }),
    Q("How many sides does a triangle have?", 3, TD, 2, "Tri means three."),
    Q("How many sides does a square have?", 4, DT, 2, "Trace each side with your finger."),
    Q("How many sides does a hexagon have?", 6, DT, 3, "Hex means six."),
    Q("How many corners does a rectangle have?", 4, TD, 3, "Touch each corner."),
    Q("How many corners does a hexagon have?", 6, TD, 4, "Touch each corner."),
    Q("How many triangles?", 7, DT, 4, "Count in a line, one by one.", { pic: [SH.triangle, 7] }),
    Q(
      "A triangle is turned upside down. How many sides now?",
      3,
      DT,
      5,
      "Turning a shape does not change its sides.",
    ),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} asks about a shape. Tap it!",
    "Listen carefully, then choose.",
    "How many? Tap the number.",
    "Listen again and pick one.",
    "Think of the shape, then tap.",
  ],
  listens: [
    L("How many sides does a triangle have?", 3, DT, 1),
    L("How many corners does a square have?", 4, TD, 1),
    L("How many sides does a rectangle have?", 4, DT, 2),
    L("How many corners does a triangle have?", 3, TD, 2),
    L("How many sides does a hexagon have?", 6, DT, 3),
    L("How many corners does a hexagon have?", 6, TD, 4),
    L("Two triangles. How many sides in all?", 6, DT, 5),
    L("A square and a triangle. How many corners in all?", 7, TD, 5),
  ],
  places: [
    {
      q: "Drag the triangle to its name.",
      items: [
        [null, SH.triangle],
        [null, SH.circle],
        [null, SH.square],
      ],
      zones: [["triangle"]],
      key: { 0: [0] },
      d: 1,
      hint: "A triangle has 3 sides.",
      why: "🔺 is a triangle.",
    },
    {
      q: "Drag the circle to its name.",
      items: [
        [null, SH.square],
        [null, SH.circle],
        [null, SH.hexagon],
      ],
      zones: [["circle"]],
      key: { 0: [1] },
      d: 1,
      hint: "A circle is round, with no corners.",
      why: "🔴 is a circle.",
    },
    {
      q: "Match each shape to its name.",
      items: [
        [null, SH.square],
        [null, SH.rectangle],
      ],
      zones: [["square"], ["rectangle"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "A square has 4 equal sides.",
      why: "🟦 is a square and ▬ is a rectangle.",
    },
    {
      q: "Match each shape to its name.",
      items: [
        [null, SH.hexagon],
        [null, SH.triangle],
      ],
      zones: [["hexagon"], ["triangle"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "Count the sides.",
      why: "⬢ has 6 sides, 🔺 has 3.",
    },
    {
      q: "Drag the hexagon to its name.",
      items: [
        [null, SH.star],
        [null, SH.hexagon],
        [null, SH.circle],
      ],
      zones: [["hexagon"]],
      key: { 0: [1] },
      d: 4,
      hint: "A hexagon has 6 sides.",
      why: "⬢ is a hexagon.",
    },
    {
      q: "Match each shape to its name.",
      items: [
        [null, SH.circle],
        [null, SH.square],
        [null, SH.triangle],
      ],
      zones: [["circle"], ["square"], ["triangle"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 5,
      hint: "Round, 4 equal sides, 3 sides.",
      why: "🔴 circle, 🟦 square, 🔺 triangle.",
    },
  ],
  counts: [
    ["triangles", SH.triangle, 5, "How many triangles? Tap each one."],
    ["circles", SH.circle, 6, "Count the circles. Tap each one."],
    ["squares", SH.square, 4, "How many squares? Tap each one."],
    ["hexagons", SH.hexagon, 3, "Count the hexagons. Tap each one."],
  ],
  reads: [
    "A triangle has three sides.",
    "A square has four equal sides.",
    "A hexagon has six sides.",
  ],
  writes: [
    [
      "Draw a triangle, a square and a circle. Label them.",
      "triangle, square, circle",
      ["Vẽ đúng ba hình", "Ghi đúng tên dưới mỗi hình"],
    ],
    [
      "Find a rectangle at home. Draw it.",
      "a door",
      ["Vẽ vật có dạng hình chữ nhật", "Có ghi tên vật"],
    ],
    ["Draw a hexagon. Count and write its sides.", "6", ["Hình có 6 cạnh", "Viết số 6"]],
  ],
});

// ─────────────────────────────────────────────────────────── đặc điểm hình ───────────────────
sentencePack({
  ...base,
  code: "EMATH.G.SHAPE_ATTRIBUTES",
  prefix: "emath-shapeattr",
  src: CCSS("1.G.A.1", "defining attributes"),
  note: "Đặc điểm xác định hình (số cạnh, số góc, khép kín) khác đặc điểm không xác định (màu, hướng, to nhỏ). Câu 'hình to và hình nhỏ có mấy cạnh' nhắm lỗi 'hình xoay/đổi cỡ là hình khác'.",
  items: [
    Q(
      "A big triangle and a tiny triangle. How many sides each?",
      3,
      TD,
      1,
      "Size does not change the sides.",
    ),
    Q(
      "A red square and a blue square. How many corners each?",
      4,
      DT,
      1,
      "Colour does not change the corners.",
    ),
    Q("I have 3 sides and 3 corners. How many sides?", 3, TD, 2, "Read the clue again."),
    Q("A rectangle has how many sides?", 4, DT, 2, "Trace each side."),
    Q(
      "How many corners does a circle have?",
      0,
      ["dem_thua_1"],
      3,
      "A circle is round all the way.",
    ),
    Q("How many sides does a hexagon have?", 6, DT, 3, "Count around the shape."),
    Q(
      "A square is turned on its corner. How many sides?",
      4,
      TD,
      3,
      "Turning does not change the sides.",
    ),
    Q("Two squares side by side. How many corners in all?", 8, DT, 4, "Each square has 4 corners."),
    Q("A triangle and a rectangle. How many sides in all?", 7, TD, 4, "3 sides and 4 sides."),
    Q("Three triangles. How many corners in all?", 9, DT, 5, "3 + 3 + 3."),
    Q("A hexagon and a triangle. How many sides in all?", 9, TD, 5, "6 sides and 3 sides."),
    Q(
      "I have 4 equal sides. How many corners do I have?",
      4,
      DT,
      4,
      "Every side meets another at a corner.",
    ),
    Q("How many sides do 2 rectangles have in all?", 8, TD, 5, "4 + 4."),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} gives a clue. Tap the number!",
    "Listen carefully, then choose.",
    "How many? Tap it.",
    "Listen again and pick one.",
    "Picture the shape, then tap.",
  ],
  listens: [
    L("How many sides does a big blue triangle have?", 3, DT, 1),
    L("How many corners does a tiny square have?", 4, TD, 1),
    L("How many corners does a rectangle have?", 4, DT, 2),
    L("How many sides does a hexagon have?", 6, TD, 3),
    L("How many corners do two triangles have in all?", 6, DT, 4),
    L("How many sides do a square and a hexagon have?", 10, TD, 5),
    L("How many corners does a circle have?", 0, ["dem_thua_1"], 3),
    L("How many sides do three squares have in all?", 12, DT, 5),
  ],
  sorts: [
    {
      q: "Does it tell the shape? Sort the clues.",
      zones: ["Tells the shape", "Does not"],
      a: ["3 sides", "4 corners"],
      b: ["red", "big"],
      d: 2,
      hint: "Colour and size do not make a shape.",
    },
    {
      q: "Sort the shapes by number of sides.",
      zones: ["3 sides", "4 sides"],
      a: ["triangle", "turned triangle"],
      b: ["square", "rectangle"],
      d: 3,
      hint: "Count the sides.",
    },
    {
      q: "Round or has corners? Sort them.",
      zones: ["No corners", "Has corners"],
      a: ["circle", "oval"],
      b: ["hexagon", "triangle"],
      d: 4,
      hint: "Corners are pointy.",
    },
  ],
  counts: [
    ["corners", "📐", 4, "Tap each corner card as you count."],
    ["sides", "📏", 6, "Tap each side card. How many sides?"],
    ["triangles", "🔺", 5, "How many triangles? Tap each one."],
    ["squares", "🟦", 3, "How many squares? Tap each one."],
  ],
  reads: [
    "A triangle has three sides and three corners.",
    "Colour does not change a shape.",
    "A circle has no corners.",
    "A square has four equal sides.",
  ],
  writes: [
    [
      "Draw a big and a small triangle. Write their sides.",
      "3 and 3",
      ["Hai tam giác to nhỏ khác nhau", "Ghi 3 cạnh cho cả hai"],
    ],
    ["Draw a shape with 4 corners. Name it.", "square", ["Hình có 4 góc", "Ghi tên đúng"]],
    [
      "Draw a closed shape and an open shape.",
      "closed square, open line",
      ["Có một hình khép kín", "Có một hình hở"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── ghép hình ───────────────────────
sentencePack({
  ...base,
  code: "EMATH.G.COMPOSE_SHAPES",
  prefix: "emath-compose",
  src: CCSS("1.G.A.2", "composing shapes"),
  note: "Ghép hình phẳng thành hình mới (2 tam giác → hình vuông, 6 tam giác → lục giác). Trắc nghiệm đếm số mảnh ghép (dem_thieu_1 là 'đếm thiếu mảnh', dem_thua_1 là 'dùng thừa hình'); kéo-thả chọn mảnh ghép bằng thẻ tranh.",
  items: [
    Q("How many triangles make one square?", 2, TD, 1, "Cut a square corner to corner."),
    Q("How many squares make a bigger square, 2 by 2?", 4, DT, 2, "Two on top, two below."),
    Q("How many triangles make a hexagon?", 6, DT, 3, "Pattern blocks: count around the middle."),
    Q("How many squares make a long rectangle of 3?", 3, TD, 2, "Put them in a row."),
    Q("How many half circles make a circle?", 2, TD, 2, "Two halves make a whole."),
    Q("How many triangles make two squares?", 4, DT, 3, "Each square needs 2."),
    Q("How many triangles make two hexagons?", 12, DT, 5, "Each hexagon needs 6."),
    Q("A house: 1 square and 1 triangle. How many shapes?", 2, TD, 1, "Count the shapes you used."),
    Q("A rocket: 3 rectangles and 2 triangles. How many shapes?", 5, DT, 4, "3 + 2."),
    Q("A robot: 4 squares and 4 rectangles. How many shapes?", 8, TD, 4, "4 + 4."),
    Q("How many small squares make a rectangle of 2 rows of 3?", 6, DT, 5, "3 + 3."),
    Q("How many quarter circles make a whole circle?", 4, TD, 3, "Four quarters make a whole."),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} builds a shape. How many pieces?",
    "Listen carefully, then choose.",
    "How many pieces? Tap it.",
    "Listen again and pick one.",
    "Picture the pieces, then tap.",
  ],
  listens: [
    L("Two triangles make one square. How many triangles for one square?", 2, TD, 1),
    L("How many squares make a two by two square?", 4, DT, 2),
    L("How many triangles make a hexagon?", 6, DT, 3),
    L("A boat is made of one triangle and two rectangles. How many shapes?", 3, TD, 3),
    L("How many halves make a whole circle?", 2, TD, 2),
    L("A flower is made of six circles and one square. How many shapes?", 7, DT, 4),
    L("How many triangles make three squares?", 6, DT, 5),
    L("How many squares make a row of five?", 5, TD, 4),
  ],
  places: [
    {
      q: "Drag the pieces that make a square.",
      items: [
        [null, "◤"],
        [null, "◢"],
        [null, "🔴"],
      ],
      zones: [["square"]],
      key: { 0: [0, 1] },
      d: 2,
      hint: "Two triangles fit together.",
      why: "◤ and ◢ make a square.",
    },
    {
      q: "Drag the shapes for a house: roof and walls.",
      items: [
        [null, "🔺"],
        [null, "🟦"],
        [null, "🔴"],
      ],
      zones: [["roof"], ["walls"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "A roof is pointy.",
      why: "🔺 roof, 🟦 walls.",
    },
    {
      q: "Drag the shapes for a snowman.",
      items: [
        [null, "⚪"],
        [null, "⚪"],
        [null, "🟦"],
      ],
      zones: [["snowman"]],
      key: { 0: [0, 1] },
      d: 3,
      hint: "A snowman is made of circles.",
      why: "Two circles make a snowman.",
    },
    {
      q: "Drag the shape that finishes the hexagon.",
      items: [
        [null, "🔺"],
        [null, "🟦"],
        [null, "🔴"],
      ],
      zones: [["missing piece"]],
      key: { 0: [0] },
      d: 4,
      hint: "A hexagon is made of triangles.",
      why: "The hexagon needs one more triangle.",
    },
    {
      q: "Drag the shapes for a rocket: body and nose.",
      items: [
        [null, "▬"],
        [null, "🔺"],
        [null, "🔴"],
      ],
      zones: [["body"], ["nose"]],
      key: { 0: [0], 1: [1] },
      d: 5,
      hint: "The nose is pointy.",
      why: "▬ body, 🔺 nose.",
    },
  ],
  counts: [
    ["triangles", "🔺", 6, "Tap each triangle in the hexagon."],
    ["squares", "🟦", 4, "Tap each small square."],
    ["pieces", "🧩", 5, "How many puzzle pieces? Tap each one."],
  ],
  reads: [
    "Two triangles make a square.",
    "Six triangles make a hexagon.",
    "I can build a house with shapes.",
  ],
  writes: [
    [
      "Draw a house with a square and a triangle.",
      "house",
      ["Có hình vuông và tam giác", "Ghép đúng: mái trên, tường dưới"],
    ],
    [
      "Draw a robot with shapes. Write how many you used.",
      "8 shapes",
      ["Vẽ được robot bằng hình", "Số hình ghi đúng"],
    ],
    [
      "Cut a paper square into 2 triangles. Draw it.",
      "2 triangles",
      ["Cắt chéo góc", "Hai tam giác bằng nhau"],
    ],
    [
      "Build a shape with 4 triangles. Draw it.",
      "a big triangle",
      ["Dùng đúng 4 tam giác", "Hình ghép khép kín"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── quy luật ────────────────────────
sentencePack({
  ...base,
  code: "EMATH.G.PATTERNS",
  prefix: "emath-pattern",
  src: CCSS("K.OA / 1.OA", "repeating and growing patterns"),
  note: "Quy luật lặp và quy luật đếm. Trắc nghiệm dùng dãy số để ô nhiễu có mã đúng nghĩa: bước hụt/dư một (dem_thieu_1/dem_thua_1), chọn nhầm vị trí trong đơn vị lặp (nham_thu_tu_so, đề có chữ 'order'). Quy luật màu và hình đi bằng kéo thẻ tranh.",
  items: [
    {
      q: "What comes next in the order? 1, 2, 1, 2, 1, ?",
      right: "2",
      wrongs: [
        ["1", "nham_thu_tu_so"],
        ["3", "dem_thua_1"],
      ],
      d: 1,
      hint: "Say it out loud: 1, 2, 1, 2…",
    },
    Q("2, 4, 6, ?", 8, DT, 2, "Count on by twos."),
    Q("5, 10, 15, ?", 20, DT, 3, "Count on by fives."),
    Q("10, 9, 8, ?", 7, ["dem_thieu_1", "lap_lai_tong"], 2, "Count back by ones.", {
      g: { rep: 8 },
    }),
    {
      q: "What comes next in the order? 3, 3, 4, 3, 3, ?",
      right: "4",
      wrongs: [
        ["3", "nham_thu_tu_so"],
        ["5", "dem_thua_1"],
      ],
      d: 3,
      hint: "The part that repeats is 3, 3, 4.",
    },
    Q("1, 3, 5, 7, ?", 9, TD, 4, "Jump by twos."),
    Q("10, 20, 30, ?", 40, DT, 3, "Count on by tens."),
    Q("20, 18, 16, ?", 14, TD, 5, "Count back by twos."),
    {
      q: "What comes next in the order? 1, 2, 3, 1, 2, ?",
      right: "3",
      wrongs: [
        ["1", "nham_thu_tu_so"],
        ["4", "dem_thua_1"],
      ],
      d: 4,
      hint: "The part that repeats is 1, 2, 3.",
    },
    Q("0, 5, 10, 15, ?", 20, TD, 4, "Count on by fives."),
    Q("3, 6, 9, ?", 12, DT, 5, "Count on by threes."),
    {
      q: "Next in the order? 7, 8, 8, 7, 8, 8, ?",
      right: "7",
      wrongs: [
        ["8", "nham_thu_tu_so"],
        ["6", "dem_thieu_1"],
      ],
      d: 5,
      hint: "The part that repeats is 7, 8, 8.",
    },
  ],
  listenPrompts: [
    "Listen to the pattern. What comes next?",
    "{ban} says a pattern. Tap what comes next!",
    "Listen carefully, then choose.",
    "What comes next? Tap it.",
    "Listen again and pick one.",
    "Say the pattern, then tap.",
  ],
  listens: [
    L("two, four, six, eight", 10, DT, 1, "What comes next?"),
    L("one, two, one, two, one", 2, ["dem_thua_1"], 1, "What comes next in the order?"),
    L("five, ten, fifteen", 20, TD, 2, "What comes next?"),
    L("ten, nine, eight, seven", 6, DT, 2, "What comes next?"),
    L("one, one, two, one, one", 2, ["dem_thua_1"], 3, "What comes next in the order?"),
    L("ten, twenty, thirty", 40, TD, 3, "What comes next?"),
    L("one, three, five, seven", 9, DT, 4, "What comes next?"),
    L("twelve, ten, eight", 6, TD, 5, "What comes next?"),
  ],
  places: [
    {
      q: "Red, blue, red, blue, … Drag what comes next.",
      items: [
        [null, "🔴"],
        [null, "🔵"],
        [null, "🟢"],
      ],
      zones: [["next"]],
      key: { 0: [0] },
      d: 1,
      hint: "Say the colours out loud.",
      why: "Red comes after blue.",
    },
    {
      q: "Star, heart, star, heart, … Drag what comes next.",
      items: [
        [null, "💛"],
        [null, "⭐"],
        [null, "🔺"],
      ],
      zones: [["next"]],
      key: { 0: [1] },
      d: 2,
      hint: "Say the pattern out loud.",
      why: "Star comes after heart.",
    },
    {
      q: "Circle, circle, square, circle, … Drag the next one.",
      items: [
        [null, "🔴"],
        [null, "🟦"],
        [null, "🔺"],
      ],
      zones: [["next"]],
      key: { 0: [0] },
      d: 3,
      hint: "The part that repeats is circle, circle, square.",
      why: "Another circle comes next.",
    },
    {
      q: "Cat, dog, dog, cat, dog, … Drag what comes next.",
      items: [
        [null, "🐕"],
        [null, "🐈"],
        [null, "🐟"],
      ],
      zones: [["next"]],
      key: { 0: [0] },
      d: 4,
      hint: "The part that repeats is cat, dog, dog.",
      why: "Dog comes next.",
    },
    {
      q: "Apple, banana, grape, apple, … Drag the next one.",
      items: [
        [null, "🍌"],
        [null, "🍇"],
        [null, "🍎"],
      ],
      zones: [["next"]],
      key: { 0: [0] },
      d: 4,
      hint: "The part that repeats has three things.",
      why: "Banana comes after apple.",
    },
    {
      q: "Sun, moon, moon, sun, moon, … Drag the next one.",
      items: [
        [null, "🌙"],
        [null, "☀️"],
        [null, "⭐"],
      ],
      zones: [["next"]],
      key: { 0: [0] },
      d: 5,
      hint: "The part that repeats is sun, moon, moon.",
      why: "Moon comes next.",
    },
  ],
  counts: [
    ["red beads", "🔴", 4, "Red, blue, red, blue… Tap the red beads."],
    ["stars", "⭐", 6, "Count the stars in the pattern."],
    ["hearts", "❤️", 5, "Tap each heart in the pattern."],
  ],
  reads: ["Red, blue, red, blue.", "Two, four, six, eight.", "The pattern repeats."],
  writes: [
    [
      "Make an AB pattern with two colours. Draw it.",
      "red blue red blue",
      ["Có ít nhất 6 hình", "Lặp đúng hai màu"],
    ],
    ["Continue the pattern: 5, 10, 15, _, _.", "20, 25", ["Viết 20 và 25", "Đếm thêm 5"]],
    [
      "Make an ABB pattern with shapes. Draw it.",
      "circle square square",
      ["Có ít nhất 6 hình", "Lặp đúng kiểu ABB"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── từ vựng toán ────────────────────
sentencePack({
  ...base,
  code: "EMATH.MP.MATH_VOCAB_EN",
  prefix: "emath-vocab",
  src: CCSS("MP6", "math vocabulary in English"),
  note: "Từ toán trong đề: plus, minus, sum, difference, altogether, in all, left, more than, fewer than. Ô nhiễu: làm phép ngược (nham_cong_tru — lỗi 'nhầm more/fewer', 'hiểu left là bên trái'), hụt/dư một, chép lại số trong đề.",
  items: [
    Q("What is the sum of 3 and 4?", 7, ["dem_thua_1", "lap_lai_tong"], 1, "Sum means add.", {
      g: { rep: 4 },
    }),
    Q("What is 9 minus 2?", 7, ["dem_thieu_1", "lap_lai_tong"], 1, "Minus means take away.", {
      g: { rep: 9 },
    }),
    Q("What is 5 more than 3?", 8, ["dem_thieu_1", "lap_lai_tong"], 2, "More than means add.", {
      g: { rep: 5 },
    }),
    Q(
      "What is 2 fewer than 6?",
      4,
      ["dem_thua_1", "lap_lai_tong"],
      2,
      "Fewer than means take away.",
      { g: { rep: 6 } },
    ),
    Q(
      "8 apples. 3 are eaten. How many are left?",
      5,
      ["lap_lai_tong", "dem_thua_1"],
      3,
      "Left means what is still there.",
      { g: { rep: 8 } },
    ),
    Q(
      "4 red and 5 blue cars. How many in all?",
      9,
      ["dem_thieu_1", "lap_lai_tong"],
      3,
      "In all means add them together.",
      { g: { rep: 5 } },
    ),
    Q(
      "What is the difference between 10 and 4?",
      6,
      ["lap_lai_tong", "dem_thua_1"],
      4,
      "Difference means take away.",
      { g: { rep: 4 } },
    ),
    Q(
      "6 birds and 6 more come. How many altogether?",
      12,
      ["dem_thieu_1", "lap_lai_tong"],
      4,
      "Altogether means add.",
      { g: { rep: 6 } },
    ),
    {
      q: "Which word means add?",
      right: "plus",
      wrongs: [
        ["minus", "nham_cong_tru"],
        ["left", "nham_cong_tru"],
      ],
      d: 1,
      hint: "Plus is +.",
    },
    {
      q: "Which word means take away?",
      right: "minus",
      wrongs: [
        ["sum", "nham_cong_tru"],
        ["altogether", "nham_cong_tru"],
      ],
      d: 2,
      hint: "Minus is -.",
    },
    {
      q: "'How many are left?' Which sign do you use?",
      right: "-",
      wrongs: [
        ["+", "nham_cong_tru"],
        ["=", "lap_lai_tong"],
      ],
      d: 3,
      hint: "Left means some went away.",
    },
    {
      q: "'How many in all?' Which sign do you use?",
      right: "+",
      wrongs: [
        ["-", "nham_cong_tru"],
        ["=", "lap_lai_tong"],
      ],
      d: 5,
      hint: "In all means put together.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} says a maths question. Tap it!",
    "Listen carefully, then choose.",
    "What is the answer? Tap it.",
    "Listen again and pick one.",
    "Listen to the maths word, then tap.",
  ],
  listens: [
    L("the sum of two and five", 7, DT, 1),
    L("eight minus three", 5, TD, 1),
    L("four more than four", 8, DT, 2),
    L("three fewer than ten", 7, TD, 2),
    L("six and three altogether", 9, DT, 3),
    L("the difference between nine and five", 4, TD, 4),
    L("Ten children. Four go home. How many are left?", 6, DT, 4),
    L("Seven cats and two dogs. How many in all?", 9, TD, 5),
  ],
  sorts: [
    {
      q: "Add words or take-away words? Sort them.",
      zones: ["Add", "Take away"],
      a: ["plus", "sum"],
      b: ["minus", "left"],
      d: 2,
      hint: "Does the number get bigger or smaller?",
    },
    {
      q: "Sort the maths words.",
      zones: ["Add", "Take away"],
      a: ["in all", "altogether"],
      b: ["difference", "fewer than"],
      d: 4,
      hint: "Does the number get bigger or smaller?",
    },
  ],
  places: [
    {
      q: "Drag each word to its sign.",
      items: [["plus"], ["minus"]],
      zones: [["+"], ["-"]],
      key: { 0: [0], 1: [1] },
      d: 1,
      hint: "Plus is add.",
      why: "plus is +, minus is -.",
    },
    {
      q: "Drag each word to its sign.",
      items: [["equals"], ["plus"]],
      zones: [["="], ["+"]],
      key: { 0: [0], 1: [1] },
      d: 2,
      hint: "Equals means the same as.",
      why: "equals is =, plus is +.",
    },
    {
      q: "Drag the word that means +.",
      items: [["altogether"], ["left"], ["fewer"]],
      zones: [["+"]],
      key: { 0: [0] },
      d: 3,
      hint: "Which word puts things together?",
      why: "Altogether means add.",
    },
    {
      q: "Drag the word that means -.",
      items: [["left"], ["sum"], ["in all"]],
      zones: [["-"]],
      key: { 0: [0] },
      d: 3,
      hint: "Which word takes things away?",
      why: "Left means take away.",
    },
    {
      q: "Match each word to its sign.",
      items: [["difference"], ["sum"]],
      zones: [["-"], ["+"]],
      key: { 0: [0], 1: [1] },
      d: 5,
      hint: "Sum is add.",
      why: "difference is -, sum is +.",
    },
  ],
  reads: [
    "Seven minus three equals four.",
    "Three plus four equals seven.",
    "The sum of two and three is five.",
    "Six minus two leaves four.",
    "How many are left?",
  ],
  writes: [
    [
      "Write a plus sentence with the word sum.",
      "The sum of 2 and 3 is 5.",
      ["Có từ sum", "Phép tính đúng"],
    ],
    ["Draw 7 balloons. 2 pop. Write how many are left.", "5", ["Vẽ đúng 7 bóng, gạch 2", "Viết 5"]],
    ["Write one add word and one take-away word.", "plus, minus", ["Một từ cộng", "Một từ trừ"]],
  ],
});

// ─────────────────────────────────────────────────────────── đọc đề toán ─────────────────────
sentencePack({
  ...base,
  code: "EMATH.MP.READ_WORD_PROBLEM_EN",
  prefix: "emath-wordprob",
  src: CCSS("MP1", "making sense of word problems"),
  note: "Đọc/nghe đề 2–3 câu, tìm số, từ khoá, câu hỏi. Ô nhiễu: chép lại số trong đề (lap_lai_tong — lỗi 'chỉ nhìn số rồi đoán'), làm phép ngược (nham_cong_tru), hụt/dư một. Đề ≤ 12 từ theo luật câu lệnh tiếng Anh.",
  items: [
    Q(
      "Sam has 5 balls. He gets 3 more. How many now?",
      8,
      ["lap_lai_tong", "dem_thieu_1"],
      1,
      "Gets more means add.",
      { g: { rep: 5 } },
    ),
    Q(
      "Mia has 9 pens. She gives away 4. How many left?",
      5,
      ["lap_lai_tong", "dem_thua_1"],
      2,
      "Gives away means take away.",
      { g: { rep: 9 } },
    ),
    Q(
      "There are 6 ducks. 6 more come. How many ducks?",
      12,
      ["lap_lai_tong", "dem_thieu_1"],
      2,
      "More come means add.",
      { g: { rep: 6 } },
    ),
    Q(
      "10 cookies. We eat 7. How many are left?",
      3,
      ["lap_lai_tong", "dem_thua_1"],
      3,
      "Eat means take away.",
      { g: { rep: 7 } },
    ),
    Q(
      "4 red fish and 7 gold fish. How many fish?",
      11,
      ["lap_lai_tong", "dem_thieu_1"],
      3,
      "Put both groups together.",
      { g: { rep: 7 } },
    ),
    Q(
      "12 kids play. 5 go home. How many still play?",
      7,
      ["lap_lai_tong", "dem_thua_1"],
      4,
      "Go home means take away.",
      { g: { rep: 5 } },
    ),
    Q(
      "Ben has 8 stickers. Ann has 3. How many more has Ben?",
      5,
      ["lap_lai_tong", "dem_thua_1"],
      5,
      "How many more: find the difference.",
      { g: { rep: 3 } },
    ),
    Q(
      "7 birds sit. 2 fly away, then 1 more. How many left?",
      4,
      ["dem_thua_1", "lap_lai_tong"],
      5,
      "Take away 2, then take away 1.",
      { g: { rep: 7 } },
    ),
    {
      q: "'How many are left?' What do you do?",
      right: "take away",
      wrongs: [
        ["add", "nham_cong_tru"],
        ["count the words", "khong_hieu_de_loi_van"],
      ],
      d: 2,
      hint: "Left means some went away.",
    },
    {
      q: "'How many in all?' What do you do?",
      right: "add",
      wrongs: [
        ["take away", "nham_cong_tru"],
        ["pick the biggest number", "khong_hieu_de_loi_van"],
      ],
      d: 2,
      hint: "In all means put together.",
    },
    {
      q: "Sam has 5 balls. He gets 3 more. What is the question?",
      right: "How many now?",
      wrongs: [
        ["He gets 3 more.", "khong_hieu_de_loi_van"],
        ["Sam has 5 balls.", "khong_hieu_de_loi_van"],
      ],
      d: 3,
      hint: "The question ends with a question mark.",
    },
    {
      q: "10 cookies. We eat 7. Which numbers do you use?",
      right: "10 and 7",
      wrongs: [
        ["10 and 17", "nham_cong_tru"],
        ["7 and 3", "khong_hieu_de_loi_van"],
      ],
      d: 4,
      hint: "Find the numbers in the story.",
    },
    {
      q: "Mia has 9 pens. She gives 4 away. Which fact?",
      right: "9 - 4 = 5",
      wrongs: [
        ["9 + 4 = 13", "nham_cong_tru"],
        ["4 - 9 = 5", "nham_thu_tu_so"],
      ],
      d: 4,
      hint: "Gives away means take away.",
    },
    {
      q: "4 cats and 2 more come. Which fact?",
      right: "4 + 2 = 6",
      wrongs: [
        ["4 - 2 = 2", "nham_cong_tru"],
        ["4 + 2 = 5", "dem_thieu_1"],
      ],
      d: 5,
      hint: "More come means add.",
    },
  ],
  listenPrompts: [
    "Listen to the story, then tap the answer.",
    "{ban} tells a maths story. Tap the answer!",
    "Listen carefully, then choose.",
    "How many? Tap it.",
    "Listen to the whole story first.",
    "Listen again and pick one.",
  ],
  listens: [
    L(
      "Tom has four apples. He gets two more. How many apples now?",
      6,
      ["lap_lai_tong", "dem_thieu_1"],
      1,
      null,
      { rep: 4 },
    ),
    L(
      "There are nine frogs. Three jump away. How many are left?",
      6,
      ["lap_lai_tong", "dem_thua_1"],
      2,
      null,
      { rep: 3 },
    ),
    L(
      "Five girls and five boys play. How many children in all?",
      10,
      ["lap_lai_tong", "dem_thieu_1"],
      2,
      null,
      { rep: 5 },
    ),
    L(
      "Eleven balloons. Two pop. How many balloons are left?",
      9,
      ["lap_lai_tong", "dem_thua_1"],
      3,
      null,
      { rep: 2 },
    ),
    L(
      "Lily reads three books on Monday and four on Tuesday. How many books?",
      7,
      ["lap_lai_tong", "dem_thua_1"],
      3,
      null,
      { rep: 4 },
    ),
    L(
      "Eight bees. Five fly to a flower. How many are not on the flower?",
      3,
      ["lap_lai_tong", "dem_thua_1"],
      4,
      null,
      { rep: 5 },
    ),
    L(
      "Ann has six stars. Ben has two. How many more does Ann have?",
      4,
      ["lap_lai_tong", "dem_thua_1"],
      5,
      null,
      { rep: 2 },
    ),
    L(
      "Ten ants. Four go in. Two come out. How many are outside?",
      8,
      ["dem_thua_1", "dem_thieu_1"],
      5,
    ),
  ],
  sorts: [
    {
      q: "Add story or take-away story? Sort them.",
      zones: ["Add", "Take away"],
      a: ["3 more come", "in all"],
      b: ["2 fly away", "how many left"],
      d: 3,
      hint: "Do the things get more or fewer?",
    },
    {
      q: "Sort the story words.",
      zones: ["Add", "Take away"],
      a: ["join", "altogether"],
      b: ["eat", "give away"],
      d: 4,
      hint: "Do the things get more or fewer?",
    },
  ],
  places: [
    {
      q: "Sam has 5 balls, gets 3 more. Drag the sign.",
      items: [["+"], ["-", null, "nham_cong_tru"]],
      zones: [["sign"]],
      key: { 0: [0] },
      d: 2,
      hint: "Gets more means add.",
      why: "5 + 3 = 8.",
    },
    {
      q: "9 pens, 4 given away. Drag the sign.",
      items: [["-"], ["+", null, "nham_cong_tru"]],
      zones: [["sign"]],
      key: { 0: [0] },
      d: 3,
      hint: "Given away means take away.",
      why: "9 - 4 = 5.",
    },
    {
      q: "Drag the question part of the story.",
      items: [["How many now?"], ["Sam has 5 balls."], ["He gets 3 more."]],
      zones: [["question"]],
      key: { 0: [0] },
      d: 4,
      hint: "It ends with a question mark.",
      why: "The question is: How many now?",
    },
    {
      q: "Drag the numbers from: 7 birds, 2 fly away.",
      items: [["7"], ["2"], ["9", null, "nham_cong_tru"]],
      zones: [["first number"], ["second number"]],
      key: { 0: [0], 1: [1] },
      d: 5,
      hint: "Find the numbers in the story.",
      why: "The numbers are 7 and 2.",
    },
  ],
  reads: [
    "Sam has five balls.",
    "He gets three more.",
    "How many does he have now?",
    "Read the question twice.",
  ],
  writes: [
    [
      "Write a story for 4 + 3. Draw it.",
      "4 cats, 3 more come",
      ["Câu chuyện có số 4 và 3", "Có tranh đúng"],
    ],
    [
      "Solve: 9 fish, 5 swim away. Write the fact.",
      "9 - 5 = 4",
      ["Viết đúng phép trừ", "Kết quả 4"],
    ],
    [
      "Circle the question in a story your parent reads.",
      "How many are left?",
      ["Tìm đúng câu hỏi", "Viết lại câu hỏi"],
    ],
  ],
});
