/**
 * Đợt 3, lô E1 — English Maths, mạch OA: number bonds, doubles, count on, count back, fact family,
 * tính giao hoán. Trường chưa đưa giáo trình English Maths, nguồn là chuẩn CCSS ghi trong bản đồ kỹ năng.
 *
 * Toán bắt mọi câu trắc nghiệm có ô nhiễu mang mã lỗi đúng nghĩa. Ô số tính ra từ đáp án (`N`):
 * dem_thieu_1 / dem_thua_1 = đáp án ∓ 1 (với count on / count back đó chính là lỗi "đếm cả số bắt đầu"),
 * lap_lai_tong = một số có trong đề, nham_cong_tru = làm phép ngược.
 *
 *   node scripts/content-gen/emath-dot3a.mjs
 */
import { sentencePack } from "./lib-en.mjs";

const EN = [
  "zero",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "eleven",
  "twelve",
  "thirteen",
  "fourteen",
  "fifteen",
  "sixteen",
  "seventeen",
  "eighteen",
  "nineteen",
  "twenty",
];
const base = { dir: "emath", subject: "EMATH" };
const CCSS = (std, topic) => `CCSS ${std} (${topic}) — chưa có giáo trình English Maths của trường`;

/** Hai ô sai quanh đáp án, mỗi ô mang đúng mã của con số đó. */
function N(ans, kinds, g = {}) {
  const out = [];
  for (const k of kinds) {
    const v = {
      dem_thieu_1: ans - 1,
      dem_thua_1: ans + 1,
      nham_cong_tru: g.opp,
      lap_lai_tong: g.rep,
    }[k];
    if (v == null || v < 0 || v === ans || out.some(([t]) => t === String(v))) continue;
    out.push([String(v), k]);
    if (out.length === 2) break;
  }
  if (!out.length) out.push([String(ans + 1), "dem_thua_1"]);
  return out;
}
const Q = (q, ans, kinds, g, d, hint, why) => ({
  q,
  right: String(ans),
  wrongs: N(ans, kinds, g),
  d,
  hint,
  why,
});
const L = (say, ans, kinds, g, d, q) => ({
  say,
  right: String(ans),
  wrongs: N(ans, kinds, g),
  d,
  ...(q ? { q } : {}),
});
const box = (q, ans, d, hint) => ({
  q,
  items: [
    [String(ans)],
    [String(ans - 1), null, "dem_thieu_1"],
    [String(ans + 1), null, "dem_thua_1"],
  ],
  zones: [["Answer"]],
  key: { 0: [0] },
  d,
  hint,
  why: `The answer is ${ans}.`,
});

// ─────────────────────────────────────────────────────────── number bonds ────────────────────
{
  const bonds = [
    [10, 6],
    [10, 3],
    [7, 4],
    [8, 5],
    [9, 2],
    [6, 1],
    [10, 8],
    [5, 3],
    [9, 6],
    [8, 2],
    [10, 5],
    [7, 7],
  ];
  const say = [
    (w, a) => `${w} is ${a} and ?`,
    (w, a) => `${a} and ? make ${w}.`,
    (w, a) => `Split ${w}: ${a} and how many?`,
  ];
  sentencePack({
    ...base,
    code: "EMATH.OA.NUMBER_BONDS_10",
    prefix: "emath-bonds",
    src: CCSS("1.OA.C.6", "part-part-whole to 10"),
    note: "Tách số đến 10 (part-part-whole). Ô nhiễu: chép lại phần đã cho (lap_lai_tong — lỗi 'nhầm phần và tổng') và hụt/dư một. Câu 'cặp nào làm thành 10' đặt cặp hụt một (6 and 3) làm ô nhiễu.",
    items: [
      ...bonds.map(([w, a], i) =>
        Q(
          say[i % 3](w, a),
          w - a,
          i % 2 ? ["dem_thieu_1", "lap_lai_tong"] : ["lap_lai_tong", "dem_thua_1"],
          { rep: a },
          1 + (i % 5),
          "Hold up the part you know, count on to the whole.",
          `${a} and ${w - a} make ${w}.`,
        ),
      ),
      {
        q: "Which pair makes 10?",
        right: "6 and 4",
        wrongs: [
          ["6 and 3", "dem_thieu_1"],
          ["6 and 5", "dem_thua_1"],
        ],
        d: 2,
        hint: "Count on from 6 to 10.",
      },
      {
        q: "Which pair makes 8?",
        right: "5 and 3",
        wrongs: [
          ["5 and 2", "dem_thieu_1"],
          ["5 and 4", "dem_thua_1"],
        ],
        d: 3,
        hint: "Count on from 5 to 8.",
      },
      {
        q: "Which pair makes 9?",
        right: "7 and 2",
        wrongs: [
          ["7 and 1", "dem_thieu_1"],
          ["7 and 3", "dem_thua_1"],
        ],
        d: 4,
        hint: "Count on from 7 to 9.",
      },
    ],
    listenPrompts: [
      "Listen, then tap the missing part.",
      "{ban} says a number bond. Tap the answer!",
      "Listen carefully, then choose.",
      "What is the missing part? Tap it.",
      "Listen again and pick one.",
      "Tap the number that completes it.",
    ],
    listens: [
      [10, 7],
      [8, 3],
      [9, 4],
      [6, 2],
      [10, 1],
      [7, 5],
      [5, 4],
      [10, 9],
    ].map(([w, a], i) =>
      L(
        `${EN[a]} and how many make ${EN[w]}?`,
        w - a,
        ["dem_thieu_1", "dem_thua_1"],
        {},
        1 + (i % 5),
      ),
    ),
    places: [
      box("10 is 6 and ?  Drag the part.", 4, 2, "Count on from 6 to 10."),
      box("7 is 3 and ?  Drag the part.", 4, 2, "Count on from 3 to 7."),
      box("9 is 5 and ?  Drag the part.", 4, 3, "Count on from 5 to 9."),
      box("8 is 6 and ?  Drag the part.", 2, 3, "Count on from 6 to 8."),
      box("10 is 2 and ?  Drag the part.", 8, 4, "Count on from 2 to 10."),
      box("6 is 3 and ?  Drag the part.", 3, 5, "Double 3 is 6."),
    ],
    counts: [
      ["dots", "🔵", 7, "Count all the dots. Tap each one."],
      ["stars", "⭐", 10, "How many stars in all? Tap each one."],
      ["apples", "🍎", 8, "Count the apples. Tap each one."],
    ],
    reads: [
      "Six and four make ten.",
      "Ten is three and seven.",
      "Eight is five and three.",
      "Nine is two and seven.",
    ],
    writes: [
      ["Write two ways to make 10.", "6 + 4, 7 + 3", ["Hai cách đều bằng 10", "Viết số rõ ràng"]],
      [
        "Draw a number bond for 8.",
        "8 = 5 and 3",
        ["Vẽ đủ tổng và hai phần", "Hai phần cộng lại đúng 8"],
      ],
      [
        "Write all the ways to make 5.",
        "0+5, 1+4, 2+3, 3+2, 4+1, 5+0",
        ["Có ít nhất 4 cách", "Mọi cách đều bằng 5"],
      ],
    ],
  });
}

// ─────────────────────────────────────────────────────────── doubles ─────────────────────────
sentencePack({
  ...base,
  code: "EMATH.OA.DOUBLES",
  prefix: "emath-doubles",
  src: CCSS("1.OA.C.6", "doubles and near doubles"),
  note: "Doubles và doubles + 1. Với near doubles, ô 'chỉ dùng double' (5 + 6 → 10) mang dem_thieu_1 — đúng lỗi 'không cộng thêm 1'; ô chép lại số trong đề mang lap_lai_tong.",
  items: [
    Q(
      "Double 4 is?",
      8,
      ["dem_thieu_1", "lap_lai_tong"],
      { rep: 4 },
      1,
      "Double means the same number twice.",
      "4 + 4 = 8.",
    ),
    Q(
      "3 + 3 = ?",
      6,
      ["dem_thua_1", "lap_lai_tong"],
      { rep: 3 },
      1,
      "Count on 3 from 3.",
      "3 + 3 = 6.",
    ),
    Q(
      "Double 5 is?",
      10,
      ["dem_thieu_1", "lap_lai_tong"],
      { rep: 5 },
      2,
      "Five fingers and five fingers.",
      "5 + 5 = 10.",
    ),
    Q("2 + 2 = ?", 4, ["dem_thua_1", "dem_thieu_1"], {}, 1, "Two and two more.", "2 + 2 = 4."),
    Q(
      "6 + 6 = ?",
      12,
      ["dem_thieu_1", "lap_lai_tong"],
      { rep: 6 },
      3,
      "Count on 6 from 6.",
      "6 + 6 = 12.",
    ),
    Q(
      "Double 7 is?",
      14,
      ["dem_thieu_1", "dem_thua_1"],
      {},
      4,
      "7 + 7: count on from 7.",
      "7 + 7 = 14.",
    ),
    Q(
      "4 + 5 = ?",
      9,
      ["dem_thieu_1", "dem_thua_1"],
      {},
      3,
      "4 + 4 is 8. One more is…",
      "4 + 4 = 8, and 1 more is 9.",
    ),
    Q(
      "5 + 6 = ?",
      11,
      ["dem_thieu_1", "dem_thua_1"],
      {},
      3,
      "5 + 5 is 10. One more is…",
      "5 + 5 = 10, and 1 more is 11.",
    ),
    Q(
      "3 + 4 = ?",
      7,
      ["dem_thieu_1", "dem_thua_1"],
      {},
      2,
      "3 + 3 is 6. One more is…",
      "3 + 3 = 6, and 1 more is 7.",
    ),
    Q(
      "6 + 7 = ?",
      13,
      ["dem_thieu_1", "dem_thua_1"],
      {},
      4,
      "6 + 6 is 12. One more is…",
      "6 + 6 = 12, and 1 more is 13.",
    ),
    Q(
      "7 + 8 = ?",
      15,
      ["dem_thieu_1", "dem_thua_1"],
      {},
      5,
      "7 + 7 is 14. One more is…",
      "7 + 7 = 14, and 1 more is 15.",
    ),
    Q(
      "Double 8 is?",
      16,
      ["dem_thieu_1", "lap_lai_tong"],
      { rep: 8 },
      5,
      "8 + 8: count on from 8.",
      "8 + 8 = 16.",
    ),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} says a double. Tap the answer!",
    "Listen carefully, then choose.",
    "What is the answer? Tap it.",
    "Listen again and pick one.",
    "Tap the number you need.",
  ],
  listens: [
    L("double three", 6, ["dem_thieu_1", "dem_thua_1"], {}, 1),
    L("double two", 4, ["dem_thua_1", "dem_thieu_1"], {}, 1),
    L("five plus five", 10, ["dem_thieu_1", "dem_thua_1"], {}, 2),
    L("double six", 12, ["dem_thieu_1", "dem_thua_1"], {}, 2),
    L("four plus five", 9, ["dem_thieu_1", "dem_thua_1"], {}, 3),
    L("double nine", 18, ["dem_thieu_1", "dem_thua_1"], {}, 4),
    L("six plus seven", 13, ["dem_thieu_1", "dem_thua_1"], {}, 4),
    L("eight plus nine", 17, ["dem_thieu_1", "dem_thua_1"], {}, 5),
  ],
  sorts: [
    {
      q: "Doubles or not doubles? Sort them.",
      zones: ["Doubles", "Not doubles"],
      a: ["3 + 3", "5 + 5"],
      b: ["3 + 4", "5 + 6"],
      d: 2,
      hint: "A double has the same number twice.",
    },
    {
      q: "Find the doubles. Sort the cards.",
      zones: ["Doubles", "Not doubles"],
      a: ["6 + 6", "2 + 2"],
      b: ["6 + 7", "1 + 2"],
      d: 3,
      hint: "A double has the same number twice.",
    },
  ],
  places: [
    {
      q: "Which double helps with 6 + 7? Drag it.",
      items: [["6 + 6"], ["7 + 8"], ["5 + 5"]],
      zones: [["helper"]],
      key: { 0: [0] },
      d: 4,
      hint: "Use the smaller number twice.",
      why: "6 + 6 = 12, then one more is 13.",
    },
    {
      q: "Which double helps with 4 + 5? Drag it.",
      items: [["4 + 4"], ["5 + 6"], ["3 + 3"]],
      zones: [["helper"]],
      key: { 0: [0] },
      d: 3,
      hint: "Use the smaller number twice.",
      why: "4 + 4 = 8, then one more is 9.",
    },
    box("Double 5 = ?  Drag the answer.", 10, 2, "Five fingers and five fingers."),
  ],
  counts: [
    ["dots", "🔵", 6, "Double 3: count all the dots."],
    ["socks", "🧦", 8, "Four pairs of socks. Count them all."],
    ["eyes", "👀", 10, "Five faces have two eyes each. Count."],
  ],
  reads: [
    "Double four is eight.",
    "Five plus five is ten.",
    "Six plus seven is thirteen.",
    "Double means twice.",
  ],
  writes: [
    [
      "Write the doubles from 1 + 1 to 5 + 5.",
      "1+1=2, 2+2=4, 3+3=6, 4+4=8, 5+5=10",
      ["Đủ 5 phép tính", "Kết quả đúng"],
    ],
    [
      "Draw a double with dots. Write the fact.",
      "3 + 3 = 6",
      ["Hai nhóm chấm bằng nhau", "Viết đúng phép tính"],
    ],
    [
      "Use a double to solve 7 + 8. Show your steps.",
      "7 + 7 = 14, 14 + 1 = 15",
      ["Có bước dùng double", "Kết quả 15"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── count on / count back ───────────
function countPack({ code, prefix, std, dir: way, facts, listens, counts, reads, writes, note }) {
  const on = way === "on";
  sentencePack({
    ...base,
    code,
    prefix,
    src: CCSS(std, on ? "counting on to add" : "counting back to subtract"),
    note,
    items: facts.map(([a, b], i) => {
      const ans = on ? a + b : a - b;
      const q = [
        `Start at ${a}, count ${way} ${b}. Where do you stop?`,
        `${a} ${on ? "+" : "-"} ${b} = ?  Count ${way} from ${a}.`,
        `Count ${way} ${b} from ${a}. What number?`,
      ][i % 3];
      // Đếm cả số bắt đầu: count on dừng sớm một (ans−1), count back dừng muộn một (ans+1).
      const kinds = on ? ["dem_thieu_1", "dem_thua_1"] : ["dem_thua_1", "dem_thieu_1"];
      return Q(
        q,
        ans,
        kinds,
        {},
        1 + (i % 5),
        `Say ${a} in your head, then count ${b} ${on ? "up" : "down"} on your fingers.`,
        `${a}… ${Array.from({ length: b }, (_, k) => (on ? a + k + 1 : a - k - 1)).join(", ")}. The answer is ${ans}.`,
      );
    }),
    listenPrompts: [
      "Listen, then tap where you stop.",
      "{ban} says where to start. Tap the answer!",
      "Listen carefully, then count.",
      "Where do you stop? Tap it.",
      "Listen again and pick one.",
      "Count in your head, then tap.",
    ],
    listens: listens.map(([a, b], i) =>
      L(
        `Start at ${EN[a]}. Count ${way} ${EN[b]}.`,
        on ? a + b : a - b,
        on ? ["dem_thieu_1", "dem_thua_1"] : ["dem_thua_1", "dem_thieu_1"],
        {},
        1 + (i % 5),
      ),
    ),
    places: facts
      .slice(0, 5)
      .map(([a, b], i) =>
        box(
          `Count ${way} ${b} from ${a}. Drag the stop.`,
          on ? a + b : a - b,
          2 + (i % 4),
          `Start at ${a}, then ${b} jumps.`,
        ),
      ),
    counts,
    reads,
    writes,
  });
}
countPack({
  code: "EMATH.OA.COUNT_ON",
  prefix: "emath-counton",
  std: "1.OA.C.5",
  dir: "on",
  note: "Đếm tiếp để cộng: bắt đầu từ số lớn, đếm thêm số nhỏ. Ô 'dừng sớm một' mang dem_thieu_1 — chính là lỗi đếm cả số bắt đầu (8, 9, 10 cho 8 + 3).",
  facts: [
    [8, 3],
    [5, 2],
    [7, 3],
    [9, 2],
    [6, 4],
    [4, 3],
    [10, 2],
    [12, 3],
    [15, 4],
    [11, 5],
    [13, 2],
    [9, 5],
  ],
  listens: [
    [7, 2],
    [5, 3],
    [9, 3],
    [6, 2],
    [10, 4],
    [12, 2],
    [14, 3],
    [8, 5],
  ],
  counts: [
    ["dots", "🔵", 8, "Count all the dots. Tap each one."],
    ["beads", "📿", 11, "Count all the beads. Tap each one."],
    ["apples", "🍎", 9, "Count every apple. Tap each one."],
    ["stars", "⭐", 12, "How many stars in all? Tap each one."],
  ],
  reads: [
    "Start at eight and count on three.",
    "Nine, ten, eleven.",
    "Start with the bigger number.",
    "Seven plus three is ten.",
  ],
  writes: [
    [
      "Show 8 + 3 by counting on. Write the numbers you say.",
      "9, 10, 11",
      ["Bắt đầu từ 8, viết 3 số tiếp theo", "Kết quả 11"],
    ],
    ["Draw a number line. Count on 4 from 6.", "6 → 10", ["Có tia số", "Bốn bước nhảy, dừng ở 10"]],
    [
      "Write three facts you can do by counting on.",
      "9 + 2, 7 + 3, 12 + 1",
      ["Ba phép cộng", "Số thêm vào nhỏ (1–3)"],
    ],
  ],
});
countPack({
  code: "EMATH.OA.COUNT_BACK",
  prefix: "emath-countback",
  std: "1.OA.C.5",
  dir: "back",
  note: "Đếm lùi để trừ. Ô 'dừng muộn một' mang dem_thua_1 — lỗi đếm cả số bắt đầu (10, 9 cho 10 − 2); ô dừng quá một bước mang dem_thieu_1.",
  facts: [
    [10, 2],
    [7, 3],
    [12, 3],
    [9, 4],
    [15, 2],
    [11, 3],
    [8, 5],
    [14, 4],
    [6, 2],
    [13, 5],
    [20, 3],
    [16, 4],
  ],
  listens: [
    [9, 2],
    [10, 3],
    [8, 4],
    [12, 2],
    [15, 3],
    [11, 4],
    [18, 2],
    [14, 5],
  ],
  counts: [
    ["birds left", "🐦", 7, "9 birds, 2 flew away. Tap the birds left."],
    ["balloons left", "🎈", 6, "8 balloons, 2 popped. Tap the ones left."],
    ["cookies left", "🍪", 5, "7 cookies, 2 eaten. Tap the ones left."],
    ["fish left", "🐟", 9, "12 fish, 3 swam away. Tap the ones left."],
  ],
  reads: [
    "Start at ten and count back two.",
    "Nine, eight.",
    "Twelve minus three is nine.",
    "Count back to take away.",
  ],
  writes: [
    [
      "Show 12 - 3 by counting back. Write the numbers you say.",
      "11, 10, 9",
      ["Bắt đầu từ 12, viết 3 số lùi", "Kết quả 9"],
    ],
    [
      "Draw a number line. Count back 4 from 10.",
      "10 → 6",
      ["Có tia số", "Bốn bước lùi, dừng ở 6"],
    ],
    [
      "Write three facts you can do by counting back.",
      "10 - 2, 9 - 1, 15 - 3",
      ["Ba phép trừ", "Số trừ nhỏ (1–3)"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── fact families ───────────────────
sentencePack({
  ...base,
  code: "EMATH.OA.RELATE_ADD_SUB",
  prefix: "emath-factfam",
  src: CCSS("1.OA.B.4", "subtraction as an unknown-addend problem"),
  note: "Quan hệ cộng – trừ (fact family). Ô nhiễu: chép lại số trong đề (lap_lai_tong), hụt/dư một, viết phép cộng thay phép trừ (nham_cong_tru, chỉ ở câu chọn phép tính — ở câu hai phép tính validator đọc phép đầu), và phép tính đảo chỗ số lớn–nhỏ ('4 - 10 = 6', nham_thu_tu_so) — lỗi của bản đồ kỹ năng.",
  items: [
    Q(
      "3 + 5 = 8. So 8 - 5 = ?",
      3,
      ["lap_lai_tong", "dem_thua_1"],
      { rep: 5 },
      1,
      "The parts are 3 and 5. The whole is 8.",
      "8 - 5 = 3.",
    ),
    Q(
      "4 + 6 = 10. So 10 - 6 = ?",
      4,
      ["lap_lai_tong", "dem_thua_1"],
      { rep: 6 },
      1,
      "Take one part away from the whole.",
      "10 - 6 = 4.",
    ),
    Q(
      "2 + 7 = 9. So 9 - 2 = ?",
      7,
      ["lap_lai_tong", "dem_thieu_1"],
      { rep: 2 },
      2,
      "Take one part away from the whole.",
      "9 - 2 = 7.",
    ),
    Q(
      "5 + 4 = 9. So 9 - 4 = ?",
      5,
      ["lap_lai_tong", "dem_thieu_1"],
      { rep: 4 },
      2,
      "The parts are 5 and 4.",
      "9 - 4 = 5.",
    ),
    Q(
      "7 - 3 = 4. So 4 + 3 = ?",
      7,
      ["lap_lai_tong", "dem_thua_1"],
      { rep: 3 },
      3,
      "Put the parts back together.",
      "4 + 3 = 7.",
    ),
    Q(
      "10 - 7 = 3. So 3 + 7 = ?",
      10,
      ["dem_thieu_1", "lap_lai_tong"],
      { rep: 7 },
      3,
      "Put the parts back together.",
      "3 + 7 = 10.",
    ),
    Q(
      "6 + 2 = 8. So 8 - 6 = ?",
      2,
      ["lap_lai_tong", "dem_thua_1"],
      { rep: 6 },
      3,
      "Take away the 6.",
      "8 - 6 = 2.",
    ),
    Q(
      "8 + 4 = 12. So 12 - 8 = ?",
      4,
      ["lap_lai_tong", "dem_thieu_1"],
      { rep: 8 },
      4,
      "Take away the 8.",
      "12 - 8 = 4.",
    ),
    Q(
      "7 + 7 = 14. So 14 - 7 = ?",
      7,
      ["dem_thieu_1", "dem_thua_1"],
      {},
      5,
      "The two parts are the same.",
      "14 - 7 = 7.",
    ),
    Q(
      "9 + 5 = 14. So 14 - 5 = ?",
      9,
      ["lap_lai_tong", "dem_thua_1"],
      { rep: 5 },
      5,
      "Take away the 5.",
      "14 - 5 = 9.",
    ),
    {
      q: "Which fact belongs with 4, 6 and 10?",
      right: "10 - 6 = 4",
      wrongs: [
        ["4 - 10 = 6", "nham_thu_tu_so"],
        ["6 + 10 = 4", "nham_cong_tru"],
      ],
      d: 3,
      hint: "Subtract from the biggest number.",
    },
    {
      q: "Which fact belongs with 3, 5 and 8?",
      right: "8 - 3 = 5",
      wrongs: [
        ["3 - 8 = 5", "nham_thu_tu_so"],
        ["8 + 3 = 5", "nham_cong_tru"],
      ],
      d: 4,
      hint: "Subtract from the biggest number.",
    },
    {
      q: "Which fact belongs with 2, 9 and 11?",
      right: "9 + 2 = 11",
      wrongs: [
        ["2 - 11 = 9", "nham_thu_tu_so"],
        ["11 + 2 = 9", "nham_cong_tru"],
      ],
      d: 4,
      hint: "The two small numbers add to the big one.",
    },
    {
      q: "Which fact belongs with 7, 1 and 8?",
      right: "8 - 7 = 1",
      wrongs: [
        ["7 - 8 = 1", "nham_thu_tu_so"],
        ["8 + 7 = 1", "nham_cong_tru"],
      ],
      d: 5,
      hint: "Subtract from the biggest number.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} says a fact. Tap the answer!",
    "Listen carefully, then choose.",
    "What is the answer? Tap it.",
    "Listen again and pick one.",
    "Use the first fact to help.",
  ],
  listens: [
    L(
      "Five plus three is eight. So eight minus three is?",
      5,
      ["lap_lai_tong", "dem_thua_1"],
      { rep: 3 },
      2,
    ),
    L(
      "Six plus four is ten. So ten minus four is?",
      6,
      ["lap_lai_tong", "dem_thieu_1"],
      { rep: 4 },
      2,
    ),
    L(
      "Two plus seven is nine. So nine minus seven is?",
      2,
      ["lap_lai_tong", "dem_thua_1"],
      { rep: 7 },
      3,
    ),
    L(
      "Eight minus five is three. So three plus five is?",
      8,
      ["lap_lai_tong", "dem_thieu_1"],
      { rep: 5 },
      3,
    ),
    L(
      "Nine plus three is twelve. So twelve minus nine is?",
      3,
      ["lap_lai_tong", "dem_thua_1"],
      { rep: 9 },
      4,
    ),
    L(
      "Seven plus six is thirteen. So thirteen minus six is?",
      7,
      ["lap_lai_tong", "dem_thieu_1"],
      { rep: 6 },
      5,
    ),
    L(
      "Ten minus two is eight. So eight plus two is?",
      10,
      ["lap_lai_tong", "dem_thieu_1"],
      { rep: 2 },
      4,
    ),
    L(
      "Four plus five is nine. So nine minus five is?",
      4,
      ["lap_lai_tong", "dem_thua_1"],
      { rep: 5 },
      5,
    ),
  ],
  sorts: [
    {
      q: "Is it in the family of 3, 4 and 7?",
      zones: ["In the family", "Not in the family"],
      a: ["3 + 4 = 7", "7 - 3 = 4"],
      b: ["7 + 3 = 10", "4 - 3 = 1"],
      d: 3,
      hint: "Every fact uses only 3, 4 and 7.",
    },
    {
      q: "Is it in the family of 2, 6 and 8?",
      zones: ["In the family", "Not in the family"],
      a: ["8 - 6 = 2", "6 + 2 = 8"],
      b: ["6 - 2 = 4", "8 + 2 = 10"],
      d: 4,
      hint: "Every fact uses only 2, 6 and 8.",
    },
  ],
  places: [
    {
      q: "Build 8 - 5 = 3 with the cards.",
      items: [["3"], ["8"], ["="], ["5"], ["-"]],
      zones: [["1"], ["2"], ["3"], ["4"], ["5"]],
      key: { 0: [1], 1: [4], 2: [3], 3: [2], 4: [0] },
      d: 2,
      hint: "Start with the whole, 8.",
      why: "8 - 5 = 3.",
    },
    {
      q: "Build 3 + 5 = 8 with the cards.",
      items: [["8"], ["+"], ["3"], ["="], ["5"]],
      zones: [["1"], ["2"], ["3"], ["4"], ["5"]],
      key: { 0: [2], 1: [1], 2: [4], 3: [3], 4: [0] },
      d: 3,
      hint: "Start with a part, 3.",
      why: "3 + 5 = 8.",
    },
    {
      q: "Build 10 - 4 = 6 with the cards.",
      items: [["6"], ["-"], ["10"], ["4"], ["="]],
      zones: [["1"], ["2"], ["3"], ["4"], ["5"]],
      key: { 0: [2], 1: [1], 2: [3], 3: [4], 4: [0] },
      d: 4,
      hint: "Start with the whole, 10.",
      why: "10 - 4 = 6.",
    },
    {
      q: "Build 4 + 6 = 10 with the cards.",
      items: [["="], ["10"], ["4"], ["+"], ["6"]],
      zones: [["1"], ["2"], ["3"], ["4"], ["5"]],
      key: { 0: [2], 1: [3], 2: [4], 3: [0], 4: [1] },
      d: 5,
      hint: "Start with a part, 4.",
      why: "4 + 6 = 10.",
    },
  ],
  reads: [
    "Three plus five is eight.",
    "Eight minus five is three.",
    "These facts are a family.",
    "Take a part from the whole.",
  ],
  writes: [
    [
      "Write the four facts for 4, 6 and 10.",
      "4+6=10, 6+4=10, 10-6=4, 10-4=6",
      ["Đủ 4 phép tính", "Không có phép 4 - 10"],
    ],
    [
      "Write the fact family for 2, 5 and 7.",
      "2+5=7, 5+2=7, 7-5=2, 7-2=5",
      ["Đủ 4 phép tính", "Mọi phép đúng"],
    ],
    [
      "Draw a bond for 9 = 6 + 3. Write two facts.",
      "6+3=9, 9-3=6",
      ["Vẽ đúng sơ đồ", "Một phép cộng, một phép trừ"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── commutative ─────────────────────
sentencePack({
  ...base,
  code: "EMATH.OA.PROPERTIES_COMMUTATIVE",
  prefix: "emath-commute",
  src: CCSS("1.OA.B.3", "properties of operations"),
  note: "Đổi chỗ các số hạng thì tổng không đổi; cộng theo thứ tự thuận (2 + 8 + 5 = 10 + 5). Ô nhiễu: tưởng đổi chỗ là đổi kết quả (dem_thua_1/dem_thieu_1), áp giao hoán cho phép trừ ('7 - 4' làm ô 'giống 4 + 7', nham_cong_tru).",
  items: [
    Q(
      "6 + 2 = 8. What is 2 + 6?",
      8,
      ["dem_thua_1", "lap_lai_tong"],
      { rep: 6 },
      1,
      "Same numbers, same total.",
      "2 + 6 = 8, the same as 6 + 2.",
    ),
    Q(
      "3 + 5 = 8. What is 5 + 3?",
      8,
      ["dem_thieu_1", "lap_lai_tong"],
      { rep: 5 },
      1,
      "Same numbers, same total.",
      "5 + 3 = 8.",
    ),
    Q(
      "4 + 7 = 11. What is 7 + 4?",
      11,
      ["dem_thua_1", "lap_lai_tong"],
      { rep: 7 },
      2,
      "Same numbers, same total.",
      "7 + 4 = 11.",
    ),
    Q(
      "9 + 1 = 10. What is 1 + 9?",
      10,
      ["dem_thieu_1", "lap_lai_tong"],
      { rep: 9 },
      2,
      "Same numbers, same total.",
      "1 + 9 = 10.",
    ),
    Q(
      "2 + 8 + 5 = ?  Add 2 + 8 first.",
      15,
      ["dem_thieu_1", "dem_thua_1"],
      {},
      3,
      "2 + 8 makes 10.",
      "10 + 5 = 15.",
    ),
    Q(
      "7 + 3 + 4 = ?  Make 10 first.",
      14,
      ["dem_thua_1", "dem_thieu_1"],
      {},
      4,
      "7 + 3 makes 10.",
      "10 + 4 = 14.",
    ),
    Q(
      "6 + 5 + 4 = ?  Make 10 first.",
      15,
      ["dem_thieu_1", "dem_thua_1"],
      {},
      4,
      "6 + 4 makes 10.",
      "10 + 5 = 15.",
    ),
    Q(
      "1 + 6 + 9 = ?  Make 10 first.",
      16,
      ["dem_thua_1", "dem_thieu_1"],
      {},
      5,
      "1 + 9 makes 10.",
      "10 + 6 = 16.",
    ),
    {
      q: "Which is the same as 4 + 7?",
      right: "7 + 4",
      wrongs: [
        ["7 - 4", "nham_cong_tru"],
        ["4 + 8", "dem_thua_1"],
      ],
      d: 2,
      hint: "Swap the numbers, keep the plus.",
    },
    {
      q: "Which is the same as 5 + 9?",
      right: "9 + 5",
      wrongs: [
        ["9 - 5", "nham_cong_tru"],
        ["5 + 8", "dem_thieu_1"],
      ],
      d: 3,
      hint: "Swap the numbers, keep the plus.",
    },
    {
      q: "Which is the same as 3 + 8?",
      right: "8 + 3",
      wrongs: [
        ["8 - 3", "nham_cong_tru"],
        ["3 + 9", "dem_thua_1"],
      ],
      d: 3,
      hint: "Swap the numbers, keep the plus.",
    },
    {
      q: "Which is the same as 6 + 2?",
      right: "2 + 6",
      wrongs: [
        ["6 - 2", "nham_cong_tru"],
        ["2 + 5", "dem_thieu_1"],
      ],
      d: 4,
      hint: "Swap the numbers, keep the plus.",
    },
    {
      q: "Which is the same as 1 + 5?",
      right: "5 + 1",
      wrongs: [
        ["5 - 1", "nham_cong_tru"],
        ["1 + 6", "dem_thua_1"],
      ],
      d: 5,
      hint: "Swap the numbers, keep the plus.",
    },
    Q(
      "8 + 0 = 8. What is 0 + 8?",
      8,
      ["dem_thua_1", "dem_thieu_1"],
      {},
      5,
      "Same numbers, same total.",
      "0 + 8 = 8.",
    ),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} swaps the numbers. Tap the answer!",
    "Listen carefully, then choose.",
    "What is the total? Tap it.",
    "Listen again and pick one.",
    "Same numbers, same total. Tap it.",
  ],
  listens: [
    L("Five plus two is seven. What is two plus five?", 7, ["dem_thua_1", "dem_thieu_1"], {}, 1),
    L("Four plus six is ten. What is six plus four?", 10, ["dem_thieu_1", "dem_thua_1"], {}, 1),
    L(
      "Three plus nine is twelve. What is nine plus three?",
      12,
      ["dem_thua_1", "dem_thieu_1"],
      {},
      2,
    ),
    L(
      "Eight plus seven is fifteen. What is seven plus eight?",
      15,
      ["dem_thieu_1", "dem_thua_1"],
      {},
      3,
    ),
    L("one plus four plus nine", 14, ["dem_thua_1", "dem_thieu_1"], {}, 3),
    L("five plus three plus five", 13, ["dem_thieu_1", "dem_thua_1"], {}, 4),
    L("two plus seven plus eight", 17, ["dem_thua_1", "dem_thieu_1"], {}, 5),
    L("six plus six plus four", 16, ["dem_thieu_1", "dem_thua_1"], {}, 5),
  ],
  sorts: [
    {
      q: "Same total as 6 + 3? Sort them.",
      zones: ["Same total", "Different"],
      a: ["3 + 6", "4 + 5"],
      b: ["6 - 3", "6 + 4"],
      d: 3,
      hint: "Work out each total.",
    },
    {
      q: "Same total as 2 + 7? Sort them.",
      zones: ["Same total", "Different"],
      a: ["7 + 2", "5 + 4"],
      b: ["7 - 2", "2 + 8"],
      d: 4,
      hint: "Work out each total.",
    },
  ],
  places: [
    {
      q: "Drag the card that equals 3 + 5.",
      items: [["5 + 3"], ["5 - 3"], ["3 + 6"]],
      zones: [["3 + 5"]],
      key: { 0: [0] },
      d: 2,
      hint: "Swap the numbers, keep the plus.",
      why: "5 + 3 = 3 + 5 = 8.",
    },
    {
      q: "Drag the card that equals 8 + 1.",
      items: [["1 + 8"], ["8 - 1"], ["1 + 7"]],
      zones: [["8 + 1"]],
      key: { 0: [0] },
      d: 3,
      hint: "Swap the numbers, keep the plus.",
      why: "1 + 8 = 8 + 1 = 9.",
    },
    {
      q: "Drag the pair that makes 10 first: 4 + 3 + 6.",
      items: [["4 + 6"], ["4 + 3"], ["3 + 6"]],
      zones: [["make 10"]],
      key: { 0: [0] },
      d: 4,
      hint: "Which two numbers make 10?",
      why: "4 + 6 = 10, then 10 + 3 = 13.",
    },
    {
      q: "Drag the pair that makes 10 first: 5 + 2 + 5.",
      items: [["5 + 5"], ["5 + 2"], ["2 + 5"]],
      zones: [["make 10"]],
      key: { 0: [0] },
      d: 5,
      hint: "Which two numbers make 10?",
      why: "5 + 5 = 10, then 10 + 2 = 12.",
    },
  ],
  reads: [
    "Six plus two is two plus six.",
    "Swap the numbers, the total stays the same.",
    "Make ten first.",
    "Two plus eight plus five is fifteen.",
  ],
  writes: [
    ["Write 3 + 4 = 7 the other way round.", "4 + 3 = 7", ["Đổi chỗ đúng hai số", "Tổng vẫn là 7"]],
    [
      "Solve 7 + 5 + 3 by making 10 first. Show steps.",
      "7 + 3 = 10, 10 + 5 = 15",
      ["Có bước tạo 10", "Kết quả 15"],
    ],
    [
      "Draw 2 red and 5 blue dots. Write two facts.",
      "2 + 5 = 7, 5 + 2 = 7",
      ["Vẽ đúng số chấm", "Hai phép cộng đổi chỗ"],
    ],
  ],
});
