/**
 * Đợt 3, lô G1 — ENL, mạch Reading Foundations: khái niệm chữ in, âm tiết, tách âm, từ nhìn primer,
 * đuôi -s/-ed/-ing, nguyên âm dài – ngắn. Nguồn: chuẩn CCSS / Global Stage 1 Literacy trong bản đồ
 * kỹ năng; câu và từ viết mới, không chép sách Kids A-Z.
 *
 * Trình hiển thị chưa có MINI_STORY, nên bài đọc hiểu đi bằng nghe (listenTarget dài) + câu hỏi in.
 * COUNT_TAP không dùng ở chữ in / âm tiết / tách âm (bỏ khỏi bản đồ kỹ năng như 16 kỹ năng ngữ âm đợt 2): vật hiện trên màn hình chính là đáp án, đếm hình không đo
 * được việc nghe âm (cùng lý do gói ngữ âm đợt 2 bỏ COUNT_TAP).
 *
 *   node scripts/content-gen/enl-dot3-rf.mjs
 */
import { sentencePack } from "./lib-en.mjs";

const base = { dir: "enl", subject: "ENL" };
const CC = (std, topic) => `CCSS ${std} (${topic}) — ENL chưa có giáo trình của trường`;
const GS = (u, topic) =>
  `Global Stage 1 Literacy Book ${u} (${topic}, bảng chương trình) — chưa chụp trang sách`;
const n = (x) => String(x);
const cnt = (ans) =>
  [
    [n(ans - 1), "dem_thieu_1"],
    [n(ans + 1), "dem_thua_1"],
  ].filter(([t]) => +t >= 0);

// ─────────────────────────────────────────────────────────── print concepts ──────────────────
const SENT = [
  ["I see a cat.", 4],
  ["I like my dog.", 4],
  ["Look at me.", 3],
  ["The sun is hot.", 4],
  ["We can run fast.", 4],
  ["My cat is big and fat.", 6],
  ["I see a red bus.", 5],
  ["Mom has a hat.", 4],
];
sentencePack({
  ...base,
  code: "ENL.RF.PRINT_CONCEPTS",
  prefix: "enl-print",
  src: CC("RF.1.1", "print concepts"),
  note: "Câu bắt đầu bằng chữ hoa, kết thúc bằng dấu chấm, đọc từ trái sang phải, đếm từ trong câu. Ô nhiễu đếm hụt/dư một từ (dem_thieu_1/dem_thua_1); ô 'đếm chữ cái' để không mã.",
  items: [
    ...SENT.map(([s, k], i) => ({
      q: `How many words? ${s}`,
      right: n(k),
      wrongs: cnt(k),
      d: 1 + (i % 5),
      hint: "Put a finger on each word.",
    })),
    {
      q: "Which sentence is written correctly?",
      right: "The cat is big.",
      wrongs: [["the cat is big."], ["The cat is big"]],
      d: 2,
      hint: "Capital letter first, full stop at the end.",
    },
    {
      q: "Which sentence is written correctly?",
      right: "I can hop.",
      wrongs: [["i can hop."], ["I can hop"]],
      d: 3,
      hint: "Capital letter first, full stop at the end.",
    },
    {
      q: "What goes at the end of a telling sentence?",
      right: ".",
      wrongs: [["?"], [","]],
      d: 2,
      hint: "A telling sentence stops with a dot.",
    },
    {
      q: "Where do we start reading a line?",
      right: "on the left",
      wrongs: [["on the right"], ["at the bottom"]],
      d: 1,
      hint: "Point to where your finger starts.",
    },
    {
      q: "Which one is a letter, not a word?",
      right: "b",
      wrongs: [["bed"], ["big"]],
      d: 1,
      hint: "A letter is just one.",
    },
    {
      q: "Which one is a word?",
      right: "cat",
      wrongs: [["c"], ["t"]],
      d: 2,
      hint: "A word can be read and has meaning.",
    },
    {
      q: "Which letter should be a capital? my dog is fun.",
      right: "m",
      wrongs: [["d"], ["f"]],
      d: 4,
      hint: "The first letter of a sentence is a capital.",
    },
    {
      q: "How many sentences? I run. I jump.",
      right: "2",
      wrongs: cnt(2),
      d: 5,
      hint: "Count the full stops.",
    },
  ],
  listenPrompts: [
    "Listen. How many words did you hear?",
    "{ban} says a sentence. Count the words!",
    "Listen and count the words.",
    "How many words? Tap the number.",
    "Listen again, count on your fingers.",
    "Count each word you hear.",
  ],
  listens: [
    ["I can see.", 3],
    ["The dog is big.", 4],
    ["We like to play.", 4],
    ["Look at the red bird.", 5],
    ["I am six.", 3],
    ["My mom can sing.", 4],
    ["The cat sat on a mat.", 6],
    ["Go.", 1],
  ].map(([say, k], i) => ({ say, right: n(k), wrongs: cnt(k), d: 1 + (i % 5) })),
  sorts: [
    {
      q: "Letter or word? Sort the cards.",
      zones: ["Letter", "Word"],
      a: ["b", "m"],
      b: ["bed", "mom"],
      d: 1,
      hint: "A letter is just one.",
    },
    {
      q: "Sentence or not a sentence? Sort them.",
      zones: ["Sentence", "Not a sentence"],
      a: ["I see a cat.", "We can hop."],
      b: ["cat see I", "a big"],
      d: 3,
      hint: "A sentence makes sense and ends with a full stop.",
    },
  ],
  reads: [
    "I like my dog.",
    "I see a cat.",
    "The sun is hot.",
    "My cat is big and fat.",
    "Look at me.",
    "We can run fast.",
  ],
  writes: [
    [
      "Write a sentence. Start with a capital, end with a full stop.",
      "I like my dog.",
      ["Chữ hoa đầu câu", "Dấu chấm cuối câu", "Có khoảng cách giữa các từ"],
    ],
    [
      "Copy: The sun is hot. Circle the capital letter.",
      "The sun is hot.",
      ["Chép đúng câu", "Khoanh chữ T"],
    ],
    ["Write your own 3-word sentence.", "I can run.", ["Đúng 3 từ", "Chữ hoa và dấu chấm"]],
  ],
});

// ─────────────────────────────────────────────────────────── syllables ───────────────────────
const SYL = [
  ["cat", "🐈", 1],
  ["apple", "🍎", 2],
  ["banana", "🍌", 3],
  ["elephant", "🐘", 3],
  ["butterfly", "🦋", 3],
  ["pencil", "✏️", 2],
  ["dinosaur", "🦕", 3],
  ["rabbit", "🐇", 2],
  ["dog", "🐕", 1],
  ["tomato", "🍅", 3],
  ["watermelon", "🍉", 4],
  ["computer", "💻", 3],
  ["sun", "☀️", 1],
  ["tiger", "🐯", 2],
  ["umbrella", "☂️", 3],
  ["caterpillar", "🐛", 4],
];
sentencePack({
  ...base,
  code: "ENL.RF.SYLLABLES",
  prefix: "enl-syll",
  src: CC("RF.1.2", "syllables"),
  note: "Vỗ tay đếm âm tiết. Ô nhiễu hụt một (gộp hai âm tiết khi nói nhanh, dem_thieu_1) và dư một (dem_thua_1). Tranh chỉ để gợi từ; từ được đọc to trong câu hỏi.",
  items: SYL.map(([w, e, k], i) => ({
    q: [
      `How many claps in ${w}?`,
      `Clap it out: ${w}. How many claps?`,
      `Say ${w}. How many parts?`,
    ][i % 3],
    pic: e,
    picLabel: w,
    right: n(k),
    wrongs: cnt(k),
    d: Math.min(5, k + (i % 2)),
    hint: "Clap once for each part you say.",
    why: `${w} has ${k} clap${k > 1 ? "s" : ""}.`,
  })),
  listenPrompts: [
    "Listen. How many claps?",
    "{ban} says a word. Clap and tap!",
    "Listen, clap, then choose.",
    "How many parts? Tap the number.",
    "Listen again and clap it out.",
    "Clap the word, then tap.",
  ],
  listens: [
    ["monkey", 2],
    ["hippo", 2],
    ["pizza", 2],
    ["bus", 1],
    ["kangaroo", 3],
    ["crocodile", 3],
    ["helicopter", 4],
    ["fish", 1],
  ].map(([say, k], i) => ({ say, right: n(k), wrongs: cnt(k), d: 1 + (i % 5) })),
  sorts: [
    {
      q: "One clap or two claps? Sort them.",
      zones: ["1 clap", "2 claps"],
      a: ["cat", "dog"],
      b: ["apple", "tiger"],
      d: 2,
      hint: "Clap each word.",
    },
    {
      q: "Two claps or three claps? Sort them.",
      zones: ["2 claps", "3 claps"],
      a: ["pencil", "rabbit"],
      b: ["banana", "tomato"],
      d: 3,
      hint: "Clap each word.",
    },
    {
      q: "Sort the words by claps.",
      zones: ["3 claps", "4 claps"],
      a: ["elephant", "computer"],
      b: ["watermelon", "caterpillar"],
      d: 5,
      hint: "Clap each word slowly.",
    },
  ],
  reads: [
    "cat, apple, banana",
    "dog, tiger, dinosaur",
    "sun, pencil, umbrella",
    "rabbit, elephant, watermelon",
    "I clap for each part.",
  ],
  writes: [
    [
      "Draw something with 2 claps. Write its name.",
      "apple",
      ["Vẽ vật có 2 âm tiết", "Viết tên vật"],
    ],
    [
      "Write your name. Draw a clap for each part.",
      "Chí Thanh: 2 claps",
      ["Viết tên", "Số vỗ tay đúng với tên"],
    ],
    [
      "Draw one thing with 1 clap and one with 3 claps.",
      "cat, banana",
      ["Hai vật", "Đúng 1 và 3 âm tiết"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── segment phonemes ────────────────
const PHO = [
  ["cat", 3, "c-a-t", "c-t"],
  ["ship", 3, "sh-i-p", "s-p"],
  ["fish", 3, "f-i-sh", "f-sh"],
  ["chin", 3, "ch-i-n", "ch-n"],
  ["cup", 3, "c-u-p", "c-a-p"],
  ["frog", 4, "f-r-o-g", "f-o-g"],
  ["hat", 3, "h-a-t", "h-o-t"],
  ["go", 2, "g-o", "g"],
  ["see", 2, "s-ee", "s-e-e"],
  ["the", 2, "th-e", "t-h-e"],
  ["duck", 3, "d-u-ck", "d-u-c-k"],
  ["bell", 3, "b-e-ll", "b-e-l-l"],
  ["milk", 4, "m-i-l-k", "m-i-k"],
  ["lamp", 4, "l-a-m-p", "l-a-p"],
];
sentencePack({
  ...base,
  code: "ENL.RF.SEGMENT_PHONEMES",
  prefix: "enl-segment",
  src: GS("Phonics Review (GS1-LIT.R)", "segmenting sounds"),
  note: "Tách từ thành âm: ship = sh-i-p (3 âm, 4 chữ). Ô 'đếm theo chữ cái' là dem_thua_1 (ship → 4) — đúng lỗi 'tách theo chữ cái với digraph'; ô gộp âm là dem_thieu_1.",
  items: [
    ...PHO.slice(0, 8).map(([w, k], i) => ({
      q: [`How many sounds in ${w}?`, `Say ${w} slowly. How many sounds?`][i % 2],
      right: n(k),
      wrongs: cnt(k),
      d: 1 + (i % 5),
      hint: "sh, ch and th make one sound each.",
    })),
    ...PHO.slice(8).map(([w, , right, wrong], i) => ({
      q: `Which shows the sounds in ${w}?`,
      right,
      wrongs: [[wrong]],
      d: 2 + (i % 4),
      hint: "Say the word very slowly.",
    })),
  ],
  listenPrompts: [
    "Listen. How many sounds?",
    "{ban} says a word. Count the sounds!",
    "Listen, then count the sounds.",
    "How many sounds? Tap the number.",
    "Listen again and stretch the word.",
    "Say it slowly, then tap.",
  ],
  listens: [
    ["dog", 3],
    ["shop", 3],
    ["tree", 3],
    ["me", 2],
    ["stop", 4],
    ["chick", 3],
    ["sun", 3],
    ["nest", 4],
  ].map(([say, k], i) => ({ say, right: n(k), wrongs: cnt(k), d: 1 + (i % 5) })),
  sorts: [
    {
      q: "Three sounds or four sounds? Sort them.",
      zones: ["3 sounds", "4 sounds"],
      a: ["cat", "ship"],
      b: ["frog", "milk"],
      d: 3,
      hint: "sh is one sound.",
    },
    {
      q: "Sort the words by sounds.",
      zones: ["2 sounds", "3 sounds"],
      a: ["go", "the"],
      b: ["chin", "duck"],
      d: 4,
      hint: "th and ck are one sound each.",
    },
  ],
  places: [
    {
      q: "Build pig: drag the sounds in order.",
      items: [["g"], ["p"], ["i"]],
      zones: [["first"], ["middle"], ["last"]],
      key: { 0: [1], 1: [2], 2: [0] },
      d: 2,
      hint: "p-i-g.",
      why: "pig is p-i-g.",
    },
    {
      q: "Build ship: drag the sounds in order.",
      items: [["p"], ["sh"], ["i"]],
      zones: [["first"], ["middle"], ["last"]],
      key: { 0: [1], 1: [2], 2: [0] },
      d: 3,
      hint: "sh is one sound.",
      why: "ship is sh-i-p.",
    },
    {
      q: "Build chop: drag the sounds in order.",
      items: [["o"], ["p"], ["ch"]],
      zones: [["first"], ["middle"], ["last"]],
      key: { 0: [2], 1: [0], 2: [1] },
      d: 4,
      hint: "ch is one sound.",
      why: "chop is ch-o-p.",
    },
    {
      q: "Build bath: drag the sounds in order.",
      items: [["th"], ["b"], ["a"]],
      zones: [["first"], ["middle"], ["last"]],
      key: { 0: [1], 1: [2], 2: [0] },
      d: 5,
      hint: "th is one sound.",
      why: "bath is b-a-th.",
    },
  ],
  reads: ["c-a-t, cat", "sh-i-p, ship", "f-r-o-g, frog", "m-i-l-k, milk"],
  writes: [
    ["Write the sounds in dog, one box each.", "d | o | g", ["Ba ô, mỗi ô một âm", "Đúng d, o, g"]],
    ["Write the sounds in fish, one box each.", "f | i | sh", ["Ba ô", "sh viết chung một ô"]],
    ["Draw a frog. Write its 4 sounds.", "f-r-o-g", ["Có tranh", "Đúng 4 âm"]],
  ],
});

// ─────────────────────────────────────────────────────────── sight words primer ──────────────
sentencePack({
  ...base,
  code: "ENL.RF.SIGHT_WORDS_PRIMER",
  prefix: "enl-primer",
  src: CC("RF.1.3g", "Dolch primer sight words"),
  note: "Từ nhìn Dolch bậc primer (all, are, came, have, into, like, must, new, now, our, out, ran, say, she, so, that, there, they, this, was, went, what, who, will…). Ô nhiễu là cặp con hay lẫn: was/saw, what/that, there/they, went/want, who/how. Bộ mã không có mã từ nhìn nên để trống mã.",
  items: [
    {
      q: "Tap the word: was",
      right: "was",
      wrongs: [["saw"], ["way"]],
      d: 1,
      hint: "Look at the first letter: w.",
    },
    {
      q: "Tap the word: what",
      right: "what",
      wrongs: [["that"], ["want"]],
      d: 1,
      hint: "Look at the first letters: wh.",
    },
    {
      q: "Tap the word: there",
      right: "there",
      wrongs: [["they"], ["three"]],
      d: 2,
      hint: "Look at the end: re.",
    },
    {
      q: "Tap the word: they",
      right: "they",
      wrongs: [["there"], ["then"]],
      d: 2,
      hint: "Look at the end: y.",
    },
    {
      q: "Tap the word: went",
      right: "went",
      wrongs: [["want"], ["new"]],
      d: 2,
      hint: "The middle letter is e.",
    },
    {
      q: "Tap the word: who",
      right: "who",
      wrongs: [["how"], ["now"]],
      d: 3,
      hint: "It starts with wh.",
    },
    {
      q: "Tap the word: came",
      right: "came",
      wrongs: [["come"], ["name"]],
      d: 3,
      hint: "The middle letter is a.",
    },
    {
      q: "Tap the word: into",
      right: "into",
      wrongs: [["onto"], ["in"]],
      d: 3,
      hint: "It starts with i.",
    },
    {
      q: "Which word fits? I ___ a big dog.",
      right: "saw",
      wrongs: [["was"], ["say"]],
      d: 4,
      hint: "Saw means I looked at it.",
    },
    {
      q: "Which word fits? ___ is your hat?",
      right: "Where",
      wrongs: [["There"], ["They"]],
      d: 4,
      hint: "It is a question.",
    },
    {
      q: "Which word fits? We ___ to the park.",
      right: "went",
      wrongs: [["want"], ["what"]],
      d: 5,
      hint: "It already happened.",
    },
    {
      q: "Which word fits? ___ are my friends.",
      right: "They",
      wrongs: [["There"], ["That"]],
      d: 5,
      hint: "It means those people.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the word.",
    "{ban} says a word. Tap it!",
    "Listen carefully, then choose.",
    "Which word did you hear? Tap it.",
    "Listen again and pick one.",
    "Tap the word you heard.",
  ],
  listens: [
    ["saw", ["was", "see"]],
    ["that", ["what", "this"]],
    ["they", ["there", "the"]],
    ["our", ["out", "are"]],
    ["now", ["new", "how"]],
    ["she", ["he", "so"]],
    ["must", ["most", "much"]],
    ["will", ["well", "with"]],
    ["good", ["goes", "gone"]],
    ["into", ["onto", "in"]],
  ].map(([say, w], i) => ({ say, right: say, wrongs: w.map((x) => [x]), d: 1 + (i % 5) })),
  builds: ["They ran out now.", "She will come too.", "What is that?", "We went into our house."],
  sorts: [
    {
      q: "Starts with wh or th? Sort them.",
      zones: ["wh", "th"],
      a: ["what", "who"],
      b: ["that", "there"],
      d: 2,
      hint: "Look at the first two letters.",
    },
    {
      q: "Find the look-alikes. Sort the cards.",
      zones: ["w words", "s words"],
      a: ["was", "went"],
      b: ["saw", "she"],
      d: 3,
      hint: "Look at the first letter.",
    },
  ],
  reads: [
    "They ran out now.",
    "She will come too.",
    "What is that?",
    "There are two cats.",
    "I saw a new bike.",
  ],
  writes: [
    ["Write: was, saw.", "was saw", ["Hai từ đúng chính tả", "Không đảo chữ"]],
    [
      "Write a sentence with they.",
      "They like to play.",
      ["Có từ they", "Câu có chữ hoa và dấu chấm"],
    ],
    ["Write: there, they, their.", "there they their", ["Ba từ đúng chính tả", "Chữ rõ ràng"]],
  ],
});

// ─────────────────────────────────────────────────────────── inflections ─────────────────────
sentencePack({
  ...base,
  code: "ENL.RF.INFLECTIONS_S_ED_ING",
  prefix: "enl-inflect",
  src: "Global Stage 1 Language Book Unit 4 (viết: chính tả động từ đuôi -ing, bảng chương trình) + CCSS RF.1.3f",
  note: "Đuôi -s, -ed, -ing và từ gốc. Ô nhiễu: đánh vần sai -ing (runing → sai_chinh_ta_tu), quên -s số nhiều (thieu_s_so_nhieu, không có dấu chấm cuối), chọn đuôi sai thời.",
  items: [
    {
      q: "What is the base word of playing?",
      right: "play",
      wrongs: [["plays"], ["played"]],
      d: 1,
      hint: "Take off the ending.",
    },
    {
      q: "What is the base word of jumped?",
      right: "jump",
      wrongs: [["jumps"], ["jumping"]],
      d: 1,
      hint: "Take off -ed.",
    },
    {
      q: "What is the base word of looks?",
      right: "look",
      wrongs: [["looked"], ["looking"]],
      d: 2,
      hint: "Take off -s.",
    },
    {
      q: "Which word tells it happened yesterday?",
      right: "jumped",
      wrongs: [["jumps"], ["jumping"]],
      d: 2,
      hint: "-ed tells it already happened.",
    },
    {
      q: "Which word tells it is happening now?",
      right: "reading",
      wrongs: [["reads"], ["read"]],
      d: 2,
      hint: "-ing tells it is happening now.",
    },
    {
      q: "She is ___ fast. (run)",
      right: "running",
      wrongs: [["runing", "sai_chinh_ta_tu"], ["runs"]],
      d: 3,
      hint: "run → double the n, add -ing.",
    },
    {
      q: "He is ___ in the pool. (swim)",
      right: "swimming",
      wrongs: [["swiming", "sai_chinh_ta_tu"], ["swims"]],
      d: 3,
      hint: "swim → double the m, add -ing.",
    },
    {
      q: "Which is right?",
      right: "I have two dogs",
      wrongs: [["I have two dog", "thieu_s_so_nhieu"], ["I have two doging"]],
      d: 3,
      hint: "Two means more than one: add -s.",
    },
    {
      q: "Which is right?",
      right: "Three cats sleep",
      wrongs: [["Three cat sleep"], ["Three cated sleep"]],
      d: 4,
      hint: "More than one: add -s.",
    },
    {
      q: "Yesterday we ___ a cake. (bake)",
      right: "baked",
      wrongs: [["bakeed", "sai_chinh_ta_tu"], ["bakes"]],
      d: 4,
      hint: "bake ends in e: just add -d.",
    },
    {
      q: "The baby is ___. (smile)",
      right: "smiling",
      wrongs: [["smileing", "sai_chinh_ta_tu"], ["smiles"]],
      d: 5,
      hint: "Drop the e, add -ing.",
    },
    {
      q: "Two ___ are in the box. (fox)",
      right: "foxes",
      wrongs: [["foxs", "sai_chinh_ta_tu"], ["fox"]],
      d: 5,
      hint: "x words add -es.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the word.",
    "{ban} says a word. Tap it!",
    "Listen for the ending, then choose.",
    "Which word did you hear? Tap it.",
    "Listen again and pick one.",
    "Listen to the end of the word.",
  ],
  listens: [
    ["jumped", ["jumps", "jumping"]],
    ["playing", ["played", "plays"]],
    ["looks", ["looked", "looking"]],
    ["wanted", ["wants", "wanting"]],
    ["cats", ["cat", "catch"]],
    ["helping", ["helped", "helps"]],
    ["kicked", ["kicks", "kicking"]],
    ["buses", ["bus", "busy"]],
  ].map(([say, w], i) => ({ say, right: say, wrongs: w.map((x) => [x]), d: 1 + (i % 5) })),
  sorts: [
    {
      q: "Happened yesterday or happening now?",
      zones: ["-ed (yesterday)", "-ing (now)"],
      a: ["jumped", "played"],
      b: ["jumping", "playing"],
      d: 2,
      hint: "Look at the ending.",
    },
    {
      q: "One or more than one? Sort them.",
      zones: ["One", "More than one"],
      a: ["dog", "box"],
      b: ["dogs", "boxes"],
      d: 3,
      hint: "-s or -es means more than one.",
    },
    {
      q: "Double the last letter or just add -ing?",
      zones: ["Double it", "Just add -ing"],
      a: ["sitting", "hopping"],
      b: ["reading", "jumping"],
      d: 5,
      hint: "Short words like sit, hop double the last letter.",
    },
  ],
  places: [
    {
      q: "Drag the ending to make jumping.",
      items: [["-ing"], ["-ed"], ["-s"]],
      zones: [["jump___"]],
      key: { 0: [0] },
      d: 2,
      hint: "Happening now.",
      why: "jump + ing = jumping.",
    },
    {
      q: "Drag the ending to make played.",
      items: [["-ed"], ["-ing"], ["-s"]],
      zones: [["play___"]],
      key: { 0: [0] },
      d: 3,
      hint: "It already happened.",
      why: "play + ed = played.",
    },
    {
      q: "Drag the ending to make boxes.",
      items: [["-es"], ["-s"], ["-ing"]],
      zones: [["box___"]],
      key: { 0: [0] },
      d: 4,
      hint: "x words take -es.",
      why: "box + es = boxes.",
    },
  ],
  reads: [
    "She plays.",
    "He jumps.",
    "He jumped.",
    "He is jumping.",
    "We wanted to play.",
    "The dogs are running.",
  ],
  writes: [
    [
      "Add -ing: play, read, jump.",
      "playing, reading, jumping",
      ["Đúng ba từ", "Không nhân đôi chữ thừa"],
    ],
    ["Add -ed: look, help, kick.", "looked, helped, kicked", ["Đúng ba từ", "Chính tả đúng"]],
    [
      "Write: run → running, sit → sitting.",
      "running, sitting",
      ["Nhân đôi n và t", "Chính tả đúng"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── long / short vowels ─────────────
sentencePack({
  ...base,
  code: "ENL.RF.LONG_SHORT_VOWEL_DISTINCTION",
  prefix: "enl-longshort",
  src: GS("Unit 1–3 (GS1-LIT.U1)", "long o, long e, long a"),
  note: "Phân biệt nguyên âm ngắn – dài (cap / cape, bit / bite, hop / hope). Ô nhiễu là chính cặp đó; cặp khác một chữ e mang sai_chinh_ta_tu (lỗi 'nhìn e cuối mà không nghe').",
  items: [
    {
      q: "Does kite have a long i or a short i?",
      right: "long i",
      wrongs: [["short i"]],
      pic: "🪁",
      d: 1,
      hint: "A long vowel says its name.",
    },
    {
      q: "Does cat have a long a or a short a?",
      right: "short a",
      wrongs: [["long a"]],
      pic: "🐈",
      d: 1,
      hint: "A long vowel says its name.",
    },
    {
      q: "Does bone have a long o or a short o?",
      right: "long o",
      wrongs: [["short o"]],
      pic: "🦴",
      d: 2,
      hint: "A long vowel says its name.",
    },
    {
      q: "Does fish have a long i or a short i?",
      right: "short i",
      wrongs: [["long i"]],
      pic: "🐟",
      d: 2,
      hint: "A long vowel says its name.",
    },
    {
      q: "Which word has a long a?",
      right: "cape",
      wrongs: [["cap", "sai_chinh_ta_tu"], ["cat"]],
      d: 2,
      hint: "Long a says ay.",
    },
    {
      q: "Which word has a short o?",
      right: "hop",
      wrongs: [["hope", "sai_chinh_ta_tu"], ["home"]],
      d: 3,
      hint: "Short o, like in dog.",
    },
    {
      q: "Which word has a long i?",
      right: "bite",
      wrongs: [["bit", "sai_chinh_ta_tu"], ["big"]],
      d: 3,
      hint: "Long i says eye.",
    },
    {
      q: "Which word has a short u?",
      right: "cub",
      wrongs: [["cube", "sai_chinh_ta_tu"], ["cute"]],
      d: 3,
      hint: "Short u, like in sun.",
    },
    {
      q: "Which word has a long e?",
      right: "tree",
      wrongs: [["ten"], ["bed"]],
      d: 4,
      hint: "Long e says ee.",
    },
    {
      q: "Which word has a short e?",
      right: "pet",
      wrongs: [["seed"], ["tree"]],
      d: 4,
      hint: "Short e, like in bed.",
    },
    {
      q: "Which word has a long o?",
      right: "note",
      wrongs: [["not", "sai_chinh_ta_tu"], ["pot"]],
      d: 5,
      hint: "Long o says oh.",
    },
    {
      q: "Which word has a short a?",
      right: "mad",
      wrongs: [["made", "sai_chinh_ta_tu"], ["rain"]],
      d: 5,
      hint: "Short a, like in cat.",
    },
    {
      q: "Does rain have a long a or a short a?",
      right: "long a",
      wrongs: [["short a"]],
      pic: "🌧️",
      d: 4,
      hint: "ai says the name of a.",
    },
    {
      q: "Does sun have a long u or a short u?",
      right: "short u",
      wrongs: [["long u"]],
      pic: "☀️",
      d: 5,
      hint: "A long vowel says its name.",
    },
  ],
  listenPrompts: [
    "Listen. Long vowel or short vowel?",
    "{ban} says a word. Long or short?",
    "Listen to the middle sound, then choose.",
    "Long or short? Tap it.",
    "Listen again and pick one.",
    "Does the vowel say its name?",
  ],
  listens: [
    ["cake", "long"],
    ["hat", "short"],
    ["bike", "long"],
    ["pig", "short"],
    ["rope", "long"],
    ["dog", "short"],
    ["feet", "long"],
    ["bus", "short"],
    ["cute", "long"],
    ["bed", "short"],
  ].map(([say, kind], i) => ({
    say,
    right: `${kind} vowel`,
    wrongs: [[kind === "long" ? "short vowel" : "long vowel"]],
    d: 1 + (i % 5),
  })),
  sorts: [
    {
      q: "Short vowel or long vowel? Sort them.",
      zones: ["Short vowel", "Long vowel"],
      a: ["cap", "kit"],
      b: ["cape", "kite"],
      d: 2,
      hint: "Say each word out loud.",
    },
    {
      q: "Sort the words by vowel sound.",
      zones: ["Short vowel", "Long vowel"],
      a: ["hop", "bed"],
      b: ["hope", "tree"],
      d: 3,
      hint: "Does the vowel say its name?",
    },
    {
      q: "Which ones have a long vowel?",
      zones: ["Short vowel", "Long vowel"],
      a: ["sun", "fish"],
      b: ["rain", "bone"],
      d: 4,
      hint: "Does the vowel say its name?",
    },
  ],
  reads: ["cap, cape", "kit, kite", "hop, hope", "cub, cube", "The kite is in the tree."],
  writes: [
    [
      "Write a short vowel word and a long vowel word.",
      "cat, cake",
      ["Một từ nguyên âm ngắn", "Một từ nguyên âm dài"],
    ],
    ["Add e to make a new word: pin → ___", "pine", ["Viết pine", "Đọc đúng âm dài"]],
    ["Draw a kite and a kit. Label them.", "kite, kit", ["Hai tranh", "Nhãn đúng"]],
  ],
});
