/**
 * Pha 6c, lô A2 — ENL: 6 kỹ năng trống của tuần 13–18. Nguồn: CCSS ELA lớp 1 (chuẩn ghi trong bản đồ
 * kỹ năng); hai cấp đọc trôi chảy dùng tiếp "sách nhỏ" viết mới kiểu pha 6b (không chép Raz-Kids).
 *
 *   node scripts/content-gen/enl-dot4.mjs
 */
import { sentencePack } from "./lib-en.mjs";

const base = { dir: "enl", subject: "ENL" };
const CC = (std, topic) => `CCSS ${std} (${topic}) — ENL chưa có giáo trình của trường`;
const RAZ = (lv) =>
  `Bài viết mới theo đặc điểm cấp ${lv} của Kids A-Z (CCSS RF.1.4) — không chép sách Raz-Kids`;
const P = (e, w) => ({ e, w });
const DROP = "doc_bo_tu_tieng_anh";

// ─────────────────────────────────────────────────────────── adjectives ──────────────────────
sentencePack({
  ...base,
  code: "ENL.L.ADJECTIVES",
  prefix: "enl-adj",
  src: CC("L.1.1f", "using frequently occurring adjectives"),
  note: "Tính từ mô tả, đặt trước danh từ (a big dog). Ô nhiễu: đặt sau danh từ (doc_bo_tu_tieng_anh khi câu đúng rơi tính từ), nhầm tính từ với động từ.",
  items: [
    {
      q: "Which word describes the dog?",
      right: "big",
      wrongs: [["run"], ["dog"]],
      pic: "🐕",
      d: 1,
      hint: "An adjective tells what something is like.",
    },
    {
      q: "Which is a complete description?",
      right: "a big dog",
      wrongs: [["a dog big"], ["dog big a"]],
      d: 1,
      hint: "The adjective comes before the noun.",
    },
    {
      q: "Choose the adjective: a ___ apple.",
      right: "red",
      wrongs: [["eat"], ["apple"]],
      pic: "🍎",
      d: 2,
      hint: "Red describes the apple.",
    },
    {
      q: "Which word tells how the boy feels?",
      right: "happy",
      wrongs: [["run"], ["boy"]],
      pic: "😊",
      d: 2,
      hint: "Happy is a feeling word.",
    },
    {
      q: "Which is right?",
      right: "The small cat sleeps.",
      wrongs: [["The cat small sleeps."], ["The cat sleeps small."]],
      d: 3,
      hint: "Small comes right before cat.",
    },
    {
      q: "Which word describes size?",
      right: "small",
      wrongs: [["jump"], ["cat"]],
      d: 2,
      hint: "Small tells you how big something is.",
    },
    {
      q: "Choose the adjective: a ___ ball.",
      right: "round",
      wrongs: [["bounce"], ["ball"]],
      pic: "⚽",
      d: 3,
      hint: "Round describes its shape.",
    },
    {
      q: "Which sentence uses an adjective correctly?",
      right: "I have a fast car.",
      wrongs: [["I have a car fast."], ["I have a fast."]],
      d: 3,
      hint: "Adjective, then noun.",
    },
    {
      q: "Which word tells how the soup tastes?",
      right: "yummy",
      wrongs: [["eat"], ["soup"]],
      d: 4,
      hint: "Yummy describes taste.",
    },
    {
      q: "Which is a complete description?",
      right: "a tall tree",
      wrongs: [["a tree tall"], ["tree a tall"]],
      d: 4,
      hint: "Adjective before noun.",
    },
    {
      q: "Which word describes colour?",
      right: "purple",
      wrongs: [["run"], ["flower"]],
      pic: "🌸",
      d: 3,
      hint: "Purple is a colour.",
    },
    {
      q: "Which sentence has two adjectives?",
      right: "I have a big, red kite.",
      wrongs: [["I have a kite big red."], ["I have a kite."]],
      d: 5,
      hint: "Look for two describing words before kite.",
    },
    {
      q: "Which word tells how the ice feels?",
      right: "cold",
      wrongs: [["melt"], ["ice"]],
      pic: "🧊",
      d: 1,
      hint: "Cold is a feeling of temperature.",
    },
    {
      q: "Choose the adjective: a ___ box.",
      right: "heavy",
      wrongs: [["lift"], ["box"]],
      d: 4,
      hint: "Heavy describes weight.",
    },
    {
      q: "Which sentence is correct?",
      right: "I have a green shirt.",
      wrongs: [["I have a shirt green."], ["I have a shirt."]],
      d: 3,
      hint: "Adjective comes before the noun.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the adjective.",
    "{ban} describes something. Tap the word!",
    "Listen carefully, then choose.",
    "Which word describes it? Tap it.",
    "Listen again and pick one.",
    "Listen for the describing word.",
  ],
  listens: [
    {
      say: "The big elephant walks slowly.",
      q: "Which word describes the elephant?",
      right: "big",
      wrongs: [["walks"], ["elephant"]],
      d: 1,
    },
    {
      say: "I have a soft blanket.",
      q: "Which word describes the blanket?",
      right: "soft",
      wrongs: [["have"], ["blanket"]],
      d: 2,
    },
    {
      say: "The tall giraffe eats leaves.",
      q: "Which word describes the giraffe?",
      right: "tall",
      wrongs: [["eats"], ["leaves"]],
      d: 2,
    },
    {
      say: "She has a shiny new bike.",
      q: "Which words describe the bike?",
      right: "shiny, new",
      wrongs: [["has, bike"], ["she, a"]],
      d: 4,
    },
    {
      say: "The cold wind blew hard.",
      q: "Which word describes the wind?",
      right: "cold",
      wrongs: [["blew"], ["hard"]],
      d: 3,
    },
    {
      say: "We saw a funny clown at the park.",
      q: "Which word describes the clown?",
      right: "funny",
      wrongs: [["saw"], ["park"]],
      d: 2,
    },
  ],
  builds: [
    "I have a big dog.",
    "She has a red apple.",
    "The small cat sleeps.",
    "He has a fast car.",
    "I see a tall tree.",
    "I have a green shirt.",
  ],
  sorts: [
    {
      q: "Adjective or not? Sort the words.",
      zones: ["Adjective", "Not an adjective"],
      a: ["big", "happy"],
      b: ["run", "dog"],
      d: 2,
      hint: "Adjectives describe things.",
    },
    {
      q: "Sort the words by what they describe.",
      zones: ["Size", "Colour"],
      a: ["big", "small"],
      b: ["red", "blue"],
      d: 3,
      hint: "Size or colour?",
    },
  ],
  reads: [
    "I have a big dog.",
    "She has a red apple.",
    "The small cat sleeps.",
    "He has a fast car.",
    "I see a tall tree.",
  ],
  writes: [
    [
      "Draw an animal. Write: a big ___ or a small ___.",
      "a big elephant",
      ["Có tranh", "Tính từ trước danh từ"],
    ],
    [
      "Draw your favourite toy. Write one adjective for it.",
      "a soft teddy bear",
      ["Có tranh", "Một tính từ đúng chỗ"],
    ],
    ["Write a sentence with two adjectives.", "I have a big, red ball.", ["Hai tính từ", "Câu đủ"]],
  ],
});

// ─────────────────────────────────────────────────────────── nouns and verbs ─────────────────
sentencePack({
  ...base,
  code: "ENL.L.NOUNS_VERBS",
  prefix: "enl-nounverb",
  src: CC("L.1.1", "nouns and verbs"),
  note: "Phân biệt danh từ (người/vật) và động từ (hành động); dùng đúng số ít/nhiều ngôi thứ ba (He runs. They run.). Ô nhiễu: coi mọi từ là danh từ, quên s ở ngôi thứ ba (doc_bo_tu_tieng_anh khi câu đúng rơi -s).",
  items: [
    {
      q: "Which word is a noun (a person or thing)?",
      right: "dog",
      wrongs: [["run"], ["jump"]],
      d: 1,
      hint: "A noun names a person, animal or thing.",
    },
    {
      q: "Which word is a verb (an action)?",
      right: "jump",
      wrongs: [["cat"], ["ball"]],
      d: 1,
      hint: "A verb is something you do.",
    },
    {
      q: "Which word is a noun?",
      right: "teacher",
      wrongs: [["read"], ["write"]],
      d: 2,
      hint: "A noun names a person.",
    },
    {
      q: "Which word is a verb?",
      right: "swim",
      wrongs: [["fish"], ["water"]],
      d: 2,
      hint: "Swim is an action.",
    },
    {
      q: "Which is right for he?",
      right: "He runs.",
      wrongs: [["He run."], ["He running."]],
      d: 3,
      hint: "He/she/it needs -s.",
    },
    {
      q: "Which is right for they?",
      right: "They run.",
      wrongs: [["They runs."], ["They running."]],
      d: 3,
      hint: "They does not take -s.",
    },
    {
      q: "Which is right for she?",
      right: "She jumps.",
      wrongs: [["She jump."], ["She jumping."]],
      d: 3,
      hint: "He/she/it needs -s.",
    },
    {
      q: "Which word names a thing, not an action?",
      right: "book",
      wrongs: [["read"], ["write"]],
      d: 2,
      hint: "Book is a thing.",
    },
    {
      q: "Which is right for we?",
      right: "We swim.",
      wrongs: [["We swims."], ["We swimming."]],
      d: 4,
      hint: "We does not take -s.",
    },
    {
      q: "Which is right for it?",
      right: "It barks.",
      wrongs: [["It bark."], ["It barking."]],
      d: 4,
      hint: "He/she/it needs -s.",
    },
    {
      q: "Which sentence has both a noun and a verb underlined correctly?",
      right: "The dog barks.",
      wrongs: [["The barks dog."], ["Dog the barks."]],
      d: 5,
      hint: "Noun, then verb.",
    },
    {
      q: "Which word is a verb?",
      right: "sing",
      wrongs: [["song"], ["singer"]],
      d: 5,
      hint: "Sing is the action.",
    },
    {
      q: "Which word is a noun?",
      right: "ball",
      wrongs: [["kick"], ["throw"]],
      d: 1,
      hint: "Ball is a thing.",
    },
    {
      q: "Which word is a verb?",
      right: "eat",
      wrongs: [["food"], ["plate"]],
      d: 1,
      hint: "Eat is an action.",
    },
    {
      q: "Which is right for the baby?",
      right: "The baby cries.",
      wrongs: [["The baby cry."], ["The baby crying."]],
      d: 4,
      hint: "He/she/it (the baby) needs -s.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the noun or verb.",
    "{ban} says a sentence. Tap the action word!",
    "Listen carefully, then choose.",
    "Noun or verb? Tap it.",
    "Listen again and pick one.",
    "Listen for the naming or doing word.",
  ],
  listens: [
    {
      say: "The cat runs fast.",
      q: "Which word is the verb?",
      right: "runs",
      wrongs: [["cat"], ["fast"]],
      d: 2,
    },
    {
      say: "My sister reads books.",
      q: "Which word is the noun?",
      right: "books",
      wrongs: [["reads"], ["my"]],
      d: 2,
    },
    {
      say: "The bird flies high.",
      q: "Which word is the verb?",
      right: "flies",
      wrongs: [["bird"], ["high"]],
      d: 3,
    },
    {
      say: "He eats an apple.",
      q: "Which word is the noun?",
      right: "apple",
      wrongs: [["eats"], ["he"]],
      d: 3,
    },
    {
      say: "They play soccer every day.",
      q: "Which word is the verb?",
      right: "play",
      wrongs: [["soccer"], ["day"]],
      d: 4,
    },
    {
      say: "The baby sleeps in the crib.",
      q: "Which word is the noun?",
      right: "crib",
      wrongs: [["sleeps"], ["baby"]],
      d: 3,
    },
  ],
  builds: [
    "The dog barks.",
    "She reads a book.",
    "They play soccer.",
    "He eats an apple.",
    "The bird flies high.",
    "The baby cries.",
  ],
  sorts: [
    {
      q: "Noun or verb? Sort the words.",
      zones: ["Noun", "Verb"],
      a: ["dog", "book"],
      b: ["run", "jump"],
      d: 2,
      hint: "Person/thing or action?",
    },
    {
      q: "Sort the words: noun or verb?",
      zones: ["Noun", "Verb"],
      a: ["teacher", "ball"],
      b: ["read", "swim"],
      d: 3,
      hint: "Person/thing or action?",
    },
    {
      q: "He/she/it + s, or not? Sort the verbs.",
      zones: ["Add -s (he/she/it)", "No -s (they/we)"],
      a: ["runs", "jumps"],
      b: ["run", "jump"],
      d: 4,
      hint: "Who is doing it?",
    },
  ],
  reads: [
    "The dog runs fast.",
    "She reads a book.",
    "They play outside.",
    "He swims every day.",
    "The bird sings.",
  ],
  writes: [
    ["Write one noun and one verb from a picture.", "dog, run", ["Một danh từ", "Một động từ"]],
    ["Write a sentence with he and the right verb.", "He runs fast.", ["Đúng -s với he"]],
    [
      "Draw two friends. Write a sentence with they.",
      "They play together.",
      ["Đúng dạng they, không -s"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── retell ──────────────────────────
const GOLDI =
  "Goldilocks walked into the bears' house. She ate the little bear's porridge. She sat in the little bear's chair and it broke. Then she fell asleep in the little bear's bed. The three bears came home and found her! Goldilocks woke up and ran away.";
const TORTOISE =
  "A hare laughed at a slow tortoise, so they had a race. The hare ran fast, then stopped to nap. The tortoise walked slowly but never stopped. The tortoise passed the sleeping hare and won the race.";
sentencePack({
  ...base,
  code: "ENL.RL.RETELL",
  prefix: "enl-retell",
  src: CC("RL.1.2", "retelling stories"),
  note: "Kể lại truyện bằng 3–4 câu có mở đầu – giữa – kết thúc, dùng tên nhân vật. Ô nhiễu: chỉ kể một chi tiết, lẫn thứ tự.",
  items: [
    {
      q: "Which is the BEGINNING of Goldilocks?",
      right: "Goldilocks walked into the bears' house.",
      wrongs: [["The three bears came home."], ["Goldilocks ran away."]],
      d: 1,
      hint: "What happens first?",
    },
    {
      q: "Which is the MIDDLE of Goldilocks?",
      right: "She ate the porridge and broke the chair.",
      wrongs: [["Goldilocks walked into the house."], ["She ran away."]],
      d: 2,
      hint: "What happens after the beginning?",
    },
    {
      q: "Which is the END of Goldilocks?",
      right: "Goldilocks woke up and ran away.",
      wrongs: [["Goldilocks walked into the house."], ["She ate the porridge."]],
      d: 2,
      hint: "What happens last?",
    },
    {
      q: "A good retelling names the ___.",
      right: "characters",
      wrongs: [["colours"], ["weather"]],
      d: 3,
      hint: "Who is in the story?",
    },
    {
      q: "Which retelling has the right order?",
      right: "First she ate, then she sat, then she slept.",
      wrongs: [["First she slept, then she ate."], ["She ran away, then she walked in."]],
      d: 4,
      hint: "Beginning, middle, end.",
    },
    {
      q: "Which is the BEGINNING of the Tortoise story?",
      right: "A hare laughed at a slow tortoise.",
      wrongs: [["The tortoise won the race."], ["The hare took a nap."]],
      d: 1,
      hint: "What happens first?",
    },
    {
      q: "Which is the END of the Tortoise story?",
      right: "The tortoise won the race.",
      wrongs: [["They had a race."], ["The hare laughed."]],
      d: 2,
      hint: "What happens last?",
    },
    {
      q: "Which retelling only gives one detail (too short)?",
      right: "Goldilocks ate porridge.",
      wrongs: [
        ["Goldilocks walked in, ate porridge, and ran away."],
        ["First she ate, then she slept, then she ran."],
      ],
      d: 5,
      hint: "A good retelling has 3-4 events.",
    },
    {
      q: "Which sentence uses a character's name?",
      right: "Goldilocks sat in the chair.",
      wrongs: [["She sat in the chair."], ["Someone sat down."]],
      d: 3,
      hint: "Look for a name, not just 'she'.",
    },
    {
      q: "Why did the hare lose the race?",
      right: "He stopped to nap.",
      wrongs: [["He ran too fast."], ["He never stopped."]],
      d: 4,
      hint: "Remember the middle of the story.",
    },
    {
      q: "Which detail belongs in a retelling of Goldilocks?",
      right: "She sat in the little bear's chair.",
      wrongs: [["It was raining outside."], ["The bears went shopping."]],
      d: 3,
      hint: "Only use events from the story.",
    },
    {
      q: "Why did the three bears come home?",
      right: "They had been out for a walk.",
      wrongs: [["They found Goldilocks first."], ["They never left home."]],
      d: 4,
      hint: "Remember the beginning of the story.",
    },
    {
      q: "Which is the best one-sentence summary of Goldilocks?",
      right: "Goldilocks went into the bears' house and got caught.",
      wrongs: [["Goldilocks liked porridge."], ["The bears live in the woods."]],
      d: 5,
      hint: "A summary covers the whole story, briefly.",
    },
    {
      q: "What lesson does the Tortoise and Hare story teach?",
      right: "Slow and steady wins the race.",
      wrongs: [["Fast animals always win."], ["Napping is a good idea."]],
      d: 5,
      hint: "Think about why the tortoise won.",
    },
    {
      q: "Which word tells you a story is finished?",
      right: "the end",
      wrongs: [["once upon a time"], ["one day"]],
      d: 1,
      hint: "Stories that start with 'once upon a time' finish with...?",
    },
  ],
  listenPrompts: [
    "Listen to the story, then answer.",
    "{ban} tells a story. Tap the answer!",
    "Listen to the whole story first.",
    "What happened? Tap it.",
    "Listen again and pick one.",
    "Think about beginning, middle, end.",
  ],
  listens: [
    {
      say: GOLDI,
      q: "What happened at the beginning?",
      right: "Goldilocks walked into the house.",
      wrongs: [["The bears came home."], ["She ran away."]],
      d: 2,
    },
    {
      say: GOLDI,
      q: "What happened in the middle?",
      right: "She ate porridge and broke the chair.",
      wrongs: [["She walked into the house."], ["The bears found her."]],
      d: 3,
    },
    {
      say: GOLDI,
      q: "What happened at the end?",
      right: "She woke up and ran away.",
      wrongs: [["She walked in."], ["She ate porridge."]],
      d: 3,
    },
    {
      say: TORTOISE,
      q: "Who won the race?",
      right: "the tortoise",
      wrongs: [["the hare"], ["nobody"]],
      d: 2,
    },
    {
      say: TORTOISE,
      q: "Why did the hare lose?",
      right: "He stopped to nap.",
      wrongs: [["He ran too slowly."], ["He got lost."]],
      d: 3,
    },
    {
      say: GOLDI,
      q: "Whose chair broke?",
      right: "the little bear's chair",
      wrongs: [["the big bear's chair"], ["Goldilocks's chair"]],
      d: 4,
    },
    {
      say: TORTOISE,
      q: "Who did the hare laugh at first?",
      right: "the tortoise",
      wrongs: [["the bears"], ["Goldilocks"]],
      d: 2,
    },
  ],
  places: [
    {
      q: "Put the Goldilocks story in order.",
      items: [
        ["She woke up and ran away."],
        ["Goldilocks walked in."],
        ["She ate porridge and broke a chair."],
      ],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [1], 1: [2], 2: [0] },
      d: 3,
      hint: "Walked in, ate and broke, ran away.",
      why: "Beginning, middle, then end.",
    },
    {
      q: "Put the Tortoise and Hare story in order.",
      items: [["The tortoise won."], ["They had a race."], ["The hare took a nap."]],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [1], 1: [2], 2: [0] },
      d: 4,
      hint: "Race started, hare napped, tortoise won.",
      why: "Beginning, middle, then end.",
    },
    {
      q: "Put the events in order: Goldilocks falls asleep.",
      items: [
        ["The bears come home."],
        ["She falls asleep in the bed."],
        ["She sits in the chair and it breaks."],
      ],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [2], 1: [1], 2: [0] },
      d: 4,
      hint: "Chair breaks, then she sleeps, then bears come home.",
      why: "Beginning, middle, then end.",
    },
  ],
  reads: [
    "Goldilocks walked into the house.",
    "She ate the porridge.",
    "She woke up and ran away.",
    "A hare and a tortoise had a race.",
    "The tortoise won the race.",
    "Slow and steady wins the race.",
    "The three bears came home.",
  ],
  writes: [
    [
      "Retell a story you know in 3 sentences.",
      "First... Then... At the end...",
      ["Có mở đầu, giữa, kết thúc", "Có tên nhân vật"],
    ],
    [
      "Draw the end of Goldilocks. Write one sentence.",
      "Goldilocks ran away.",
      ["Có tranh", "Đúng chi tiết kết thúc"],
    ],
    [
      "Draw the Tortoise and Hare. Write who won and why.",
      "The tortoise won because he never stopped.",
      ["Có tranh", "Nêu đúng lý do"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── fluency level E ─────────────────
function fluencyPack({ code, prefix, level, note, pages, drops, builds, writes }) {
  sentencePack({
    ...base,
    code,
    prefix,
    src: RAZ(level),
    note,
    items: pages.slice(0, 12).map(([s, e], i) => ({
      q: [
        "Which sentence matches the picture?",
        "Read and pick the sentence for the picture.",
        "Tap the sentence that tells the picture.",
      ][i % 3],
      pic: e,
      right: s,
      wrongs: [[pages[(i + 1) % pages.length][0]], [pages[(i + 5) % pages.length][0]]],
      d: 1 + (i % 5),
      hint: "Look at the picture, then read each sentence.",
      why: `The picture shows: ${s}`,
    })),
    listenPrompts: [
      "Listen, then tap the sentence you heard.",
      "{ban} reads a page. Tap it!",
      "Listen carefully, then choose.",
      "Which sentence did you hear? Tap it.",
      "Listen to every word, then pick.",
      "Listen again and pick one.",
    ],
    listens: drops.map(([say, dropped, swap], i) => ({
      say,
      right: say,
      wrongs: [[dropped, DROP], [swap]],
      d: 1 + (i % 5),
    })),
    builds,
    reads: pages.map(([s]) => s),
    writes,
  });
}
fluencyPack({
  code: "ENL.RF.FLUENCY_LEVEL_E",
  prefix: "enl-fle",
  level: "E",
  note: "Cấp E: đoạn ngắn 3–4 câu, có digraph và blend. Sách nhỏ viết mới: 'The Best Trip', 'A Snack for Frog'.",
  pages: [
    ["We packed our bags. Then we got in the truck.", "🚚"],
    ["We drove past green hills and a big lake.", "🏞️"],
    ["At last, we saw the beach. The sand felt warm.", "🏖️"],
    ["We swam in the cold waves. It was so much fun.", "🌊"],
    ["Dad grilled fish for lunch. It smelled so good.", "🐟"],
    ["We saw crabs and shells on the sand.", "🦀"],
    ["Frog was hungry. He looked in his little kitchen.", "🐸"],
    ["He found bread, cheese, and a plum.", "🧀"],
    ["Frog made a big snack and put it on a plate.", "🍽️"],
    ["Toad came by. Frog shared his snack with Toad.", "🐸"],
    ["They ate the snack together on the porch.", "🏡"],
    ["Frog and Toad smiled. It was a good day.", "😊"],
    ["The truck stopped at a rest stop.", "🛑"],
    ["Frog washed the plate when they finished.", "🧼"],
  ],
  drops: [
    ["We packed our bags.", "We packed bags.", "We unpacked our bags."],
    ["At last, we saw the beach.", "At last, we the beach.", "At last, we left the beach."],
    ["Frog was hungry.", "Frog hungry.", "Frog was sleepy."],
    [
      "He found bread, cheese, and a plum.",
      "He found bread and a plum.",
      "He lost bread, cheese, and a plum.",
    ],
    ["Toad came by.", "Toad by.", "Toad ran away."],
    ["They ate the snack together.", "They ate snack together.", "They hid the snack together."],
  ],
  builds: [
    "We packed our bags.",
    "Frog was hungry.",
    "They ate the snack together.",
    "The sand felt warm.",
  ],
  writes: [
    [
      "Draw a trip you took. Write two sentences.",
      "We drove to the beach. We swam in the sea.",
      ["Có tranh", "Hai câu đủ ý"],
    ],
    [
      "Draw a snack you like. Write two sentences.",
      "I like cheese. I share it with my friend.",
      ["Có tranh", "Hai câu đủ ý"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── nouns/verbs support: fluency F ──
fluencyPack({
  code: "ENL.RF.FLUENCY_LEVEL_F",
  prefix: "enl-flf",
  level: "F",
  note: "Cấp F: truyện có mở đầu – kết thúc, 30–60 từ/trang. Sách nhỏ viết mới: 'The New Puppy', 'Rainy Day Fort'.",
  pages: [
    [
      "Mia had wanted a puppy for a very long time. On her birthday, Dad brought home a small brown puppy with floppy ears.",
      "🐶",
    ],
    ["Mia named the puppy Buddy. Buddy liked to chase his tail and chew on old shoes.", "👟"],
    ["Every morning, Mia took Buddy for a walk around the block before school.", "🚶"],
    ["One day, Buddy ran after a squirrel and pulled the leash right out of Mia's hand!", "🐿️"],
    ["Mia chased Buddy all the way to the park, calling his name the whole time.", "🏃"],
    ["At last, Buddy stopped at a bench to sniff a sandwich someone had dropped.", "🥪"],
    ['Mia caught up and held the leash tight. "Silly Buddy," she laughed, out of breath.', "😅"],
    ["They walked home together, and Buddy fell asleep in his bed that night.", "😴"],
    ["It was raining hard outside, so Ben and his sister could not go to the park.", "🌧️"],
    ['"Let\'s build a fort!" said Ben. They pulled all the blankets off their beds.', "🛏️"],
    ["They stacked pillows and chairs and draped blankets over the top.", "🪑"],
    ["Inside the fort, they read books with a flashlight and ate crackers.", "🔦"],
    ["When the rain stopped, they were sad to leave their cosy little fort.", "🌈"],
    ['"We can build it again next rainy day," Ben\'s sister said with a smile.', "😊"],
  ],
  drops: [
    ["Mia named the puppy Buddy.", "Mia named puppy Buddy.", "Mia lost the puppy Buddy."],
    ["Buddy ran after a squirrel.", "Buddy ran a squirrel.", "Buddy hid from a squirrel."],
    ["Mia chased Buddy to the park.", "Mia chased Buddy park.", "Mia followed Buddy home."],
    ["Let's build a fort!", "Let's a fort!", "Let's break the fort!"],
    [
      "They stacked pillows and chairs.",
      "They stacked pillows chairs.",
      "They threw pillows and chairs.",
    ],
    [
      "They read books with a flashlight.",
      "They read books flashlight.",
      "They wrote books with a flashlight.",
    ],
  ],
  builds: [
    "Mia had wanted a puppy.",
    "Buddy chased a squirrel.",
    "Let's build a fort!",
    "They read books with a flashlight.",
  ],
  writes: [
    [
      "Draw a pet you have or want. Write 2-3 sentences about it.",
      "I have a dog. He likes to run. He sleeps a lot.",
      ["Có tranh", "Hai đến ba câu"],
    ],
    [
      "Draw a fort you would build. Write 2-3 sentences.",
      "I would use blankets. I would read inside. It would be cosy.",
      ["Có tranh", "Hai đến ba câu"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── sequence events ─────────────────
const HEN =
  "The Little Red Hen found some wheat seeds. She asked her friends to help plant them, but they all said no. She planted the seeds herself. The wheat grew. She asked her friends to help cut it, bake it, but they said no every time. She baked bread all by herself and ate it herself too.";
sentencePack({
  ...base,
  code: "ENL.RL.SEQUENCE_EVENTS",
  prefix: "enl-sequence",
  src: CC("RL.1.2", "describing the sequence of events"),
  note: "Xếp 3–4 sự kiện theo first, next, then, last. Ô nhiễu: đảo hai sự kiện giữa, dùng 'last' cho sự kiện đầu.",
  items: [
    {
      q: "What happened FIRST in The Little Red Hen?",
      right: "She found wheat seeds.",
      wrongs: [["She baked bread."], ["She ate the bread."]],
      d: 1,
      hint: "First means the very beginning.",
    },
    {
      q: "What happened LAST in The Little Red Hen?",
      right: "She ate the bread herself.",
      wrongs: [["She found seeds."], ["She planted seeds."]],
      d: 1,
      hint: "Last means the very end.",
    },
    {
      q: "Which word means 'at the very beginning'?",
      right: "first",
      wrongs: [["last"], ["then"]],
      d: 2,
      hint: "First comes before next, then, last.",
    },
    {
      q: "Which word means 'at the very end'?",
      right: "last",
      wrongs: [["first"], ["next"]],
      d: 2,
      hint: "Last comes after everything else.",
    },
    {
      q: "Which comes after 'first'?",
      right: "next",
      wrongs: [["last"], ["yesterday"]],
      d: 3,
      hint: "First, next, then, last.",
    },
    {
      q: "Which comes right before 'last'?",
      right: "then",
      wrongs: [["first"], ["next"]],
      d: 3,
      hint: "First, next, then, last.",
    },
    {
      q: '"First she planted seeds. ___ the wheat grew."',
      right: "Next",
      wrongs: [["Last"], ["Yesterday"]],
      d: 3,
      hint: "Next tells what happens after first.",
    },
    {
      q: "Which retelling has the right order?",
      right: "First she planted, then it grew, last she baked bread.",
      wrongs: [
        ["First she baked bread, then she planted."],
        ["Last she planted, first she baked."],
      ],
      d: 4,
      hint: "Planting comes before baking.",
    },
    {
      q: "In a story, 'last' can be used for which event?",
      right: "the final event",
      wrongs: [["the first event"], ["any event"]],
      d: 4,
      hint: "Last is only for the end.",
    },
    {
      q: "Which sentence correctly uses 'then'?",
      right: "First we ate, then we played.",
      wrongs: [["Then we ate, first we played."], ["We then, first ate."]],
      d: 5,
      hint: "First comes before then.",
    },
    {
      q: '"___ she planted seeds. Next the wheat grew."',
      right: "First",
      wrongs: [["Last"], ["Then"]],
      d: 2,
      hint: "This is the very first event.",
    },
    {
      q: "Which word tells you an event happens in the middle?",
      right: "next",
      wrongs: [["first"], ["last"]],
      d: 3,
      hint: "Next is not the beginning or the end.",
    },
    {
      q: "In The Little Red Hen, what happened right before she baked bread?",
      right: "The wheat grew.",
      wrongs: [["She found seeds."], ["She ate the bread."]],
      d: 4,
      hint: "Think about what comes right before baking.",
    },
    {
      q: "Which is the correct order of four steps?",
      right: "first, next, then, last",
      wrongs: [["last, first, next, then"], ["then, first, last, next"]],
      d: 5,
      hint: "This is the standard order.",
    },
    {
      q: "Which word signals the very last event?",
      right: "last",
      wrongs: [["first"], ["next"]],
      d: 1,
      hint: "Last always ends the list.",
    },
    {
      q: '"First we ate. ___ we played games."',
      right: "Then",
      wrongs: [["First"], ["Yesterday"]],
      d: 3,
      hint: "Then comes after first.",
    },
  ],
  listenPrompts: [
    "Listen to the story, then answer.",
    "{ban} tells a story. Tap the answer!",
    "Listen to the whole story first.",
    "What happened? Tap it.",
    "Listen again and pick one.",
    "Think about the order of events.",
  ],
  listens: [
    {
      say: HEN,
      q: "What happened first?",
      right: "She found wheat seeds.",
      wrongs: [["She baked bread."], ["The wheat grew."]],
      d: 2,
    },
    {
      say: HEN,
      q: "What happened next, after finding the seeds?",
      right: "She asked her friends to help plant.",
      wrongs: [["She ate the bread."], ["She baked the bread."]],
      d: 3,
    },
    {
      say: HEN,
      q: "What happened last?",
      right: "She ate the bread by herself.",
      wrongs: [["She found the seeds."], ["She planted the seeds."]],
      d: 3,
    },
    {
      say: "First I woke up. Next I got dressed. Then I ate breakfast. Last I went to school.",
      q: "What happened last?",
      right: "went to school",
      wrongs: [["woke up"], ["got dressed"]],
      d: 2,
    },
    {
      say: "First I woke up. Next I got dressed. Then I ate breakfast. Last I went to school.",
      q: "What happened first?",
      right: "woke up",
      wrongs: [["got dressed"], ["went to school"]],
      d: 2,
    },
    {
      say: HEN,
      q: "Did her friends help her plant the seeds?",
      right: "no, they said no",
      wrongs: [["yes, all of them"], ["only one friend helped"]],
      d: 4,
    },
  ],
  places: [
    {
      q: "Put The Little Red Hen in order.",
      items: [["She ate the bread."], ["She found seeds."], ["The wheat grew."]],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [1], 1: [2], 2: [0] },
      d: 3,
      hint: "Seeds, then growing, then eating.",
      why: "First seeds, next growing, last eating.",
    },
    {
      q: "Put a morning routine in order.",
      items: [["eat breakfast"], ["wake up"], ["get dressed"]],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [1], 1: [2], 2: [0] },
      d: 2,
      hint: "What do you do right after waking up?",
      why: "Wake up, get dressed, eat breakfast.",
    },
    {
      q: "Put planting a seed in order.",
      items: [["it grows into a plant"], ["plant the seed"], ["water it"]],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [1], 1: [2], 2: [0] },
      d: 4,
      hint: "What happens right after planting?",
      why: "Plant, water, then it grows.",
    },
    {
      q: "Put making a sandwich in order.",
      items: [["eat the sandwich"], ["put bread on a plate"], ["add cheese and ham"]],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [2], 1: [0], 2: [1] },
      d: 3,
      hint: "Bread first, then fillings, then eating.",
      why: "Plate, then fillings, then eating.",
    },
  ],
  reads: [
    "First she found seeds.",
    "Next she planted them.",
    "Then the wheat grew.",
    "Last she baked bread.",
    "First, next, then, last.",
    "First I wake up.",
    "Last I go to school.",
  ],
  writes: [
    [
      "Draw your morning. Write: First..., Next..., Last...",
      "First I wake up. Next I eat. Last I go to school.",
      ["Ba sự kiện đúng thứ tự", "Dùng đúng first/next/last"],
    ],
    [
      "Retell a story using first, next, then, last.",
      "First... Next... Then... Last...",
      ["Đủ bốn từ nối", "Đúng thứ tự truyện"],
    ],
    [
      "Draw how to make a sandwich. Write the steps in order.",
      "First bread. Next fillings. Last eat it.",
      ["Ba bước đúng thứ tự", "Dùng từ nối"],
    ],
  ],
});
