/**
 * Pha 6c, lô A4 — English Science: 9 kỹ năng trống của tuần 13–18 (thực vật, quan sát-đo đạc, động
 * vật). Trường chưa có sách English Science — nguồn NGSS ghi thẳng vào sourceRef, không giả vờ bám
 * sách. Khoa học lớp 1 không có mã lỗi trong bộ mã (validator chỉ cảnh báo), nên lỗi thường gặp nằm
 * ở ô nhiễu: nhầm root/stem, nghĩ hoa làm thức ăn, nghĩ hạt cần ánh sáng để nảy mầm, xếp dolphin vào
 * cá, nghĩ mọi con vật có lông, nối con non theo màu thay vì theo loài.
 *
 *   node scripts/content-gen/esci-dot4.mjs
 */
import { sentencePack } from "./lib-en.mjs";

const base = { dir: "esci", subject: "ESCI" };
const w = (list) => list.map((x) => (Array.isArray(x) ? x : [x]));
const I = (q, right, wrongs, d, extra = {}) => ({
  q,
  right,
  wrongs: w(wrongs),
  d,
  hint: extra.hint ?? "Think about what you see outside every day.",
  ...extra,
});
const L = (say, right, wrongs, d, extra = {}) => ({ say, right, wrongs: w(wrongs), d, ...extra });
const NGSS = (std, topic) => `NGSS ${std} (${topic}) — chưa có sách English Science của trường`;

// ─────────────────────────────────────────────────────────── plant parts ──────────────────────
sentencePack({
  ...base,
  code: "ESCI.LS.PLANT_PARTS",
  prefix: "esci-plantpart",
  src: NGSS("1-LS1-1", "plant structure and function"),
  note: "Roots, stem, leaves, flower, seed và chức năng của từng bộ phận. Ô nhiễu nhắm lỗi nhầm stem/roots và nghĩ hoa làm thức ăn.",
  items: [
    I("Which part holds the plant in the soil?", "roots", ["stem", "leaves"], 1, { pic: "🌱" }),
    I("Which part carries water up to the leaves?", "stem", ["roots", "flower"], 1),
    I("Which part makes food from sunlight?", "leaves", ["roots", "seed"], 2),
    I("Which part grows into a new plant?", "seed", ["flower", "stem"], 1, { pic: "🌰" }),
    I("Which part attracts bees to make new seeds?", "flower", ["leaves", "roots"], 2, {
      pic: "🌸",
    }),
    I(
      "What happens if a plant has no roots?",
      "It cannot take in water.",
      ["It grows faster.", "It makes more flowers."],
      3,
    ),
    I(
      "What happens if a plant has no leaves?",
      "It cannot make food.",
      ["It grows taller.", "It makes more roots."],
      3,
    ),
    I("Which part is usually underground?", "roots", ["flower", "leaves"], 1),
    I("Which part holds the plant up straight?", "stem", ["seed", "flower"], 2),
    I(
      "Do flowers make food for the plant?",
      "no, leaves do",
      ["yes, flowers do", "no, roots do"],
      3,
    ),
    I("Which part comes from a flower after it is pollinated?", "seed", ["stem", "leaves"], 3),
    I("Which part takes in water and nutrients from soil?", "roots", ["flower", "stem"], 1),
    I("A cactus has thick, green ___ instead of a normal stem.", "stem", ["roots", "seed"], 4, {
      hint: "Cacti store water in this part.",
    }),
    I(
      "Which two parts work together to bring water to the leaves?",
      "roots and stem",
      ["flower and seed", "leaves and flower"],
      4,
    ),
    I(
      "Why do plants need leaves?",
      "to make food using sunlight",
      ["to hold the plant in soil", "to make new seeds only"],
      3,
    ),
    I("Which part usually grows above the ground?", "stem", ["roots", "soil"], 2),
    I("Which part is often colourful to attract insects?", "flower", ["roots", "stem"], 2),
    I("If you pull a plant out, which part is covered in soil?", "roots", ["flower", "leaves"], 1),
  ],
  listenPrompts: [
    "Listen, then tap the plant part.",
    "{ban} talks about a plant. Tap it!",
    "Listen carefully, then choose.",
    "Which part is it? Tap it.",
    "Listen again and pick one.",
    "Listen for the plant word.",
  ],
  listens: [
    L("This part holds the plant in the soil.", "roots", ["stem", "flower"], 1),
    L("This part carries water up to the leaves.", "stem", ["roots", "seed"], 2),
    L("This part makes food using sunlight.", "leaves", ["roots", "flower"], 2),
    L("This part grows into a new plant.", "seed", ["stem", "leaves"], 1),
    L("This part attracts bees.", "flower", ["roots", "stem"], 2),
    L("This part is usually found underground.", "roots", ["flower", "leaves"], 3),
    L("This part stands up tall and straight.", "stem", ["seed", "flower"], 2),
    L("This part becomes a seed after pollination.", "flower", ["roots", "stem"], 3),
  ],
  builds: [],
  sorts: [
    {
      q: "Sort the plant parts: underground or above ground?",
      zones: ["Underground", "Above ground"],
      a: ["roots"],
      b: ["stem", "leaves", "flower"],
      d: 2,
      hint: "Which part is buried in the soil?",
    },
    {
      q: "Sort by job: makes food, or grows new plants?",
      zones: ["Makes food", "Grows new plants"],
      a: ["leaves"],
      b: ["seed", "flower"],
      d: 4,
      hint: "Which job uses sunlight?",
    },
  ],
  places: [
    {
      q: "Drag each label to the right plant part.",
      items: [
        [null, "🌱"],
        [null, "🌸"],
        [null, "🌰"],
      ],
      zones: [["roots and stem"], ["flower"], ["seed"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 3,
      hint: "Think about where each part grows.",
      why: "Roots/stem, flower, and seed each look different.",
    },
  ],
  reads: [
    "Roots hold the plant in the soil.",
    "The stem carries water to the leaves.",
    "Leaves make food from sunlight.",
    "The flower makes new seeds.",
  ],
  writes: [
    [
      "Draw a plant. Label roots, stem, leaves, and flower.",
      "roots, stem, leaves, flower",
      ["Có tranh cây", "Ghi đủ bốn nhãn"],
    ],
    [
      "Draw the part of a plant that makes food. Write its name.",
      "leaves",
      ["Vẽ đúng lá", "Ghi đúng tên"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── plant vocab ──────────────────────
sentencePack({
  ...base,
  code: "ESCI.VOC.PLANT_WORDS",
  prefix: "esci-plantvoc",
  src: NGSS("1-LS1-1", "plant vocabulary"),
  note: "Từ vựng root, stem, leaf, flower, seed, fruit, soil, sunlight, grow, sprout. Ô nhiễu nhắm nhầm stem/root, seed/fruit.",
  items: [
    I("Which word means the part underground?", "root", ["stem", "fruit"], 1, { pic: "🌱" }),
    I("Which word means the tall middle part?", "stem", ["root", "seed"], 1),
    I("Which word means a flat, green part?", "leaf", ["fruit", "soil"], 1, { pic: "🍃" }),
    I("Which word names the colourful part that attracts bees?", "flower", ["soil", "root"], 2, {
      pic: "🌸",
    }),
    I("Which word means what grows into a new plant?", "seed", ["fruit", "leaf"], 2, { pic: "🌰" }),
    I("Which word names the part with seeds inside, like an apple?", "fruit", ["seed", "root"], 3, {
      pic: "🍎",
    }),
    I("Which word means the dirt a plant grows in?", "soil", ["sunlight", "stem"], 1, {
      pic: "🟤",
    }),
    I("Which word means the light plants need to grow?", "sunlight", ["soil", "seed"], 1, {
      pic: "☀️",
    }),
    I("Which word means to get bigger?", "grow", ["sprout", "soil"], 2),
    I("Which word means a seed just starting to grow?", "sprout", ["fruit", "root"], 3, {
      pic: "🌱",
    }),
    I("'Plants need sunlight and ___ to grow.'", "water", ["fruit", "flower"], 2),
    I("'A seed can ___ into a small plant.'", "sprout", ["soil", "fruit"], 3),
    I("Which word is NOT a plant part?", "sunlight", ["root", "stem"], 3, {
      hint: "Sunlight helps plants but is not part of the plant.",
    }),
    I("Which is bigger: a seed or a fruit?", "fruit", ["seed", "they are the same"], 4),
    I("Which word means what a seed does when it starts to grow?", "sprout", ["grow", "soil"], 3),
    I("'The apple ___ has seeds inside it.'", "fruit", ["root", "soil"], 2),
    I("Which word names the part that turns into fruit?", "flower", ["root", "soil"], 3),
    I(
      "In plants, which two words are often mixed up?",
      "sprout and root",
      ["leaf and flower", "fruit and soil"],
      4,
    ),
  ],
  listenPrompts: [
    "Listen, then tap the word.",
    "{ban} says a plant word. Tap it!",
    "Listen carefully, then choose.",
    "Which word is it? Tap it.",
    "Listen again and pick one.",
    "Listen for the plant word.",
  ],
  listens: [
    L("root", "root", ["stem", "fruit"], 1),
    L("stem", "stem", ["root", "leaf"], 1),
    L("leaf", "leaf", ["fruit", "soil"], 1),
    L("flower", "flower", ["soil", "root"], 2),
    L("seed", "seed", ["fruit", "leaf"], 2),
    L("sprout", "sprout", ["fruit", "root"], 3),
    L("sunlight", "sunlight", ["soil", "seed"], 2),
    L("fruit", "fruit", ["seed", "root"], 3),
    L("soil", "soil", ["sunlight", "leaf"], 1),
  ],
  builds: [],
  sorts: [
    {
      q: "Sort the words: plant part, or not a plant part?",
      zones: ["Plant part", "Not a plant part"],
      a: ["root", "stem", "leaf", "flower"],
      b: ["sunlight", "soil"],
      d: 3,
      hint: "Sunlight and soil help plants but are not parts of the plant.",
    },
  ],
  places: [
    {
      q: "Match each picture to its word.",
      items: [
        [null, "🌱"],
        [null, "🌸"],
        [null, "🍎"],
      ],
      zones: [["root"], ["flower"], ["fruit"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 2,
      hint: "Think about where each picture grows.",
      why: "Root underground, flower colourful, fruit has seeds inside.",
    },
  ],
  reads: [
    "Plants need sunlight and water to grow.",
    "A seed can sprout into a small plant.",
    "The root grows underground.",
    "A fruit has seeds inside it.",
  ],
  writes: [
    [
      "Draw a plant growing from a seed. Label two parts.",
      "seed, sprout",
      ["Có tranh", "Hai nhãn đúng"],
    ],
    ["Write two things a plant needs to grow.", "sunlight and water", ["Hai điều đúng"]],
  ],
});

// ─────────────────────────────────────────────────────────── record & draw ────────────────────
sentencePack({
  ...base,
  code: "ESCI.INQ.RECORD_DRAW",
  prefix: "esci-record",
  src: NGSS("K-2-ETS1-1", "recording observations"),
  note: "Ghi chép quan sát bằng hình vẽ có nhãn và bảng. Ô nhiễu nhắm lỗi vẽ theo tưởng tượng, quên ghi ngày, không có nhãn.",
  items: [
    I(
      "A good science drawing should have...",
      "labels for each part",
      ["only bright colours", "no writing at all"],
      1,
    ),
    I(
      "Why do we write the date on an observation?",
      "to know when we saw it",
      ["to make the drawing pretty", "it is not needed"],
      3,
    ),
    I(
      "You draw a bean plant on day 1 and 5. What differs?",
      "the height of the plant",
      ["the colour of the paper", "nothing should change"],
      3,
    ),
    I(
      "Which is a good way to record how tall a plant is?",
      "measure and write the number",
      ["guess and say 'big'", "draw it any size"],
      3,
    ),
    I(
      "A table with ticks helps you...",
      "compare things quickly",
      ["draw better pictures", "avoid writing numbers"],
      4,
    ),
    I(
      "Should you draw what you imagine or what you see?",
      "what you see",
      ["what you imagine", "either one is fine"],
      2,
    ),
    I(
      "What should you do first before drawing a plant?",
      "look at it carefully",
      ["draw from memory", "guess its colour"],
      2,
    ),
    I(
      "A chart tracking plant growth needs a column for...",
      "the day and the height",
      ["only the colour", "only a smiley face"],
      4,
    ),
    I(
      "If you forget to write the date, what happens?",
      "you cannot compare days",
      ["nothing changes", "the drawing looks better"],
      4,
    ),
    I(
      "Which tool helps you record height accurately?",
      "a ruler",
      ["your imagination", "a guess"],
      2,
    ),
    I(
      "What is the purpose of a science journal?",
      "to record what you observe over time",
      ["to draw cartoons", "to write stories"],
      3,
    ),
    I(
      "A good label on a drawing tells you...",
      "the name of the part",
      ["the drawer's mood", "nothing useful"],
      2,
    ),
    I(
      "Why measure with numbers instead of drawing 'big' or 'small'?",
      "numbers can be compared exactly",
      ["numbers are prettier", "size words are always exact"],
      4,
    ),
    I(
      "You guessed the colour instead of looking. Is that good science?",
      "no, you should observe carefully",
      ["yes, guessing is fine", "yes, colour does not matter"],
      3,
    ),
    I(
      "What makes two observation drawings easy to compare?",
      "same labels and same units",
      ["different colours each time", "no labels at all"],
      4,
    ),
    I(
      "Why record observations over several days instead of just once?",
      "to see how things change over time",
      ["one day tells you everything", "it is not useful"],
      4,
    ),
    I(
      "Which is the most careful way to check a measurement?",
      "measure it again to be sure",
      ["guess and move on", "ask a friend to guess"],
      3,
    ),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} talks about recording. Tap it!",
    "Listen carefully, then choose.",
    "Which is right? Tap it.",
    "Listen again and pick one.",
    "Think, then tap.",
  ],
  listens: [
    L("A science drawing should have labels for each part.", "true", ["false"], 2),
    L("You should draw what you imagine, not what you see.", "false", ["true"], 2),
    L("Writing the date helps you compare different days.", "true", ["false"], 3),
    L("A ruler helps you measure height accurately.", "true", ["false"], 2),
    L("A chart with ticks helps you compare things quickly.", "true", ["false"], 4),
    L("Recording over several days helps you see change over time.", "true", ["false"], 3),
    L("Guessing a measurement is just as good as measuring it.", "false", ["true"], 3),
    L("A good drawing has no labels at all.", "false", ["true"], 2),
    L("Measuring again helps you check your work.", "true", ["false"], 3),
  ],
  builds: [],
  sorts: [
    {
      q: "Sort the drawing habits: good or not good?",
      zones: ["Good", "Not good"],
      a: ["labels each part", "writes the date"],
      b: ["draws from imagination", "skips the date"],
      d: 3,
      hint: "A good record shows what you really see.",
    },
  ],
  places: [
    {
      q: "Order the steps to record a plant's growth.",
      items: [
        ["Write the height and date."],
        ["Look at the plant carefully."],
        ["Measure the plant with a ruler."],
      ],
      zones: [["first"], ["next"], ["last"]],
      key: { 0: [2], 1: [0], 2: [1] },
      d: 4,
      hint: "Look first, then measure, then write it down.",
      why: "Look, measure, then record.",
    },
  ],
  reads: [
    "A good drawing has labels.",
    "Write the date every time.",
    "Measure with a ruler, not a guess.",
    "Draw what you see, not what you imagine.",
  ],
  writes: [
    [
      "Draw a bean plant on day 1 and 5. Label the height.",
      "day 1: short, day 5: taller",
      ["Hai tranh khác chiều cao", "Có ghi ngày"],
    ],
    ["Draw a leaf you found. Label its parts.", "leaf, stem", ["Có tranh lá", "Có nhãn"]],
    [
      "Make a simple table: day and height. Fill in 2 rows.",
      "day 1: 2cm, day 2: 3cm",
      ["Có hai cột", "Có số đo"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── seed to plant ────────────────────
sentencePack({
  ...base,
  code: "ESCI.LS.SEED_TO_PLANT",
  prefix: "esci-seedgrow",
  src: NGSS("1-LS3-1", "plant life cycle"),
  note: "Thứ tự seed → sprout → seedling → plant → flower/fruit; hạt cần nước và hơi ấm, không nhất thiết cần ánh sáng để nảy mầm. Ô nhiễu nhắm đảo thứ tự và nghĩ hạt cần ánh sáng để nảy mầm.",
  items: [
    I("What comes first in a plant's life?", "seed", ["flower", "fruit"], 1, { pic: "🌰" }),
    I(
      "What does a seed need to sprout?",
      "water and warmth",
      ["sunlight only", "nothing at all"],
      2,
    ),
    I(
      "Does a seed need sunlight to start sprouting?",
      "no, it needs water and warmth",
      ["yes, sunlight only", "yes, and nothing else"],
      3,
    ),
    I("What comes right after 'seed'?", "sprout", ["flower", "fruit"], 1),
    I("What comes right after 'sprout'?", "seedling", ["seed", "fruit"], 2),
    I("What comes right after 'seedling'?", "plant", ["seed", "sprout"], 2),
    I("What usually comes last in the life cycle?", "flower or fruit", ["seed", "sprout"], 2),
    I(
      "A tiny green sprout with its first leaves is called a...",
      "seedling",
      ["sprout", "fruit"],
      3,
    ),
    I(
      "Once a plant is fully grown, what might it make?",
      "flowers and seeds",
      ["only roots", "only soil"],
      3,
    ),
    I(
      "Which needs to happen before a seed can sprout?",
      "it gets water and warmth",
      ["it gets picked up", "it is painted"],
      2,
    ),
    I(
      "Why do farmers water their seeds?",
      "seeds need water to sprout",
      ["to make seeds a different colour", "seeds do not need water"],
      3,
    ),
    I(
      "A bean seed sits in a dry, cold place. What happens?",
      "it will not sprout",
      ["it sprouts quickly", "it turns into a flower"],
      4,
    ),
    I("What is the very first stage of a plant's life?", "seed", ["seedling", "flower"], 1),
    I("Which comes before 'seedling' but after 'seed'?", "sprout", ["plant", "flower"], 2),
    I(
      "What does a young seedling need to keep growing?",
      "water and sunlight",
      ["only darkness", "nothing at all"],
      3,
    ),
    I(
      "Can a seed sprout in the dark with water and warmth?",
      "yes, it can",
      ["no, it needs light first", "no, seeds never sprout in the dark"],
      4,
    ),
    I(
      "After seed, sprout, seedling, plant, what comes next?",
      "flower or fruit",
      ["seed again", "nothing, it stops"],
      3,
    ),
    I(
      "A seed planted in icy soil with no warmth. What happens?",
      "it will not sprout well",
      ["it sprouts extra fast", "it turns straight into a flower"],
      5,
    ),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} talks about a seed. Tap it!",
    "Listen carefully, then choose.",
    "What comes next? Tap it.",
    "Listen again and pick one.",
    "Think about the life cycle, then tap.",
  ],
  listens: [
    L("First is a seed. What comes next?", "sprout", ["flower", "fruit"], 1),
    L("After sprout comes what?", "seedling", ["seed", "fruit"], 2),
    L("A seed needs water and warmth to do what?", "sprout", ["fly", "sing"], 2),
    L("Does a seed need sunlight to sprout?", "no", ["yes"], 3),
    L("What comes after seedling?", "plant", ["seed", "sprout"], 2),
    L("What is the very first stage of a plant's life?", "seed", ["seedling", "flower"], 1),
    L("What might a fully grown plant make?", "flowers or fruit", ["only roots", "only soil"], 3),
  ],
  builds: [],
  sorts: [
    {
      q: "Sort what a seed needs to sprout: needed, or not needed?",
      zones: ["Needed", "Not needed"],
      a: ["water", "warmth"],
      b: ["sunlight", "soil colour"],
      d: 4,
      hint: "A seed can sprout in the dark, but not without water.",
    },
  ],
  places: [
    {
      q: "Put the plant life cycle in order.",
      items: [["plant"], ["seed"], ["seedling"], ["sprout"]],
      zones: [["1st"], ["2nd"], ["3rd"], ["4th"]],
      key: { 0: [3], 1: [0], 2: [2], 3: [1] },
      d: 3,
      hint: "Seed, sprout, seedling, plant.",
      why: "Seed comes first, then sprout, then seedling, then plant.",
    },
    {
      q: "Put the life cycle in order, starting from a flower.",
      items: [["seed"], ["flower"], ["sprout"]],
      zones: [["1st"], ["2nd"], ["3rd"]],
      key: { 0: [1], 1: [2], 2: [0] },
      d: 4,
      hint: "A flower makes seeds, and a seed sprouts.",
      why: "Flower makes seed, seed sprouts, and the cycle starts again.",
    },
  ],
  reads: [
    "A seed needs water and warmth to sprout.",
    "First a seed, then a sprout.",
    "A seedling grows into a full plant.",
    "A grown plant can make flowers and seeds.",
    "A seed does not need sunlight to sprout.",
  ],
  writes: [
    [
      "Draw the four stages: seed, sprout, seedling, plant.",
      "seed, sprout, seedling, plant",
      ["Đủ bốn giai đoạn", "Đúng thứ tự"],
    ],
    ["Draw what a seed needs to grow. Label it.", "water, warmth", ["Có tranh", "Có nhãn đúng"]],
  ],
});

// ─────────────────────────────────────────────────────────── measure & compare ────────────────
sentencePack({
  ...base,
  code: "ESCI.INQ.MEASURE_COMPARE",
  prefix: "esci-measure",
  src: NGSS("K-2-ETS1-1", "measuring and comparing"),
  note: "Dùng thước, cân đơn giản, cốc đong để so sánh và ghi số. Ô nhiễu nhắm đo không cùng mốc và so sánh bằng mắt rồi ghi số bừa.",
  items: [
    I(
      "One plant is 5 cubes tall, another is 8. Which is taller?",
      "the 8-cube plant",
      ["the 5-cube plant", "they are the same"],
      1,
    ),
    I("What tool measures how long something is?", "a ruler", ["a clock", "a cup"], 1, {
      pic: "📏",
    }),
    I("What tool measures how heavy something is?", "a scale", ["a ruler", "a clock"], 2, {
      pic: "⚖️",
    }),
    I("What tool measures how much liquid there is?", "a measuring cup", ["a ruler", "a scale"], 2),
    I(
      "Why must you start measuring from the same spot each time?",
      "to compare fairly",
      ["it looks neater", "it does not matter"],
      3,
    ),
    I(
      "You measure at the soil, then the pot rim. Is that fair?",
      "no, it is not fair",
      ["yes, it is fine", "it does not matter"],
      4,
    ),
    I(
      "A 6-apple bag and a 4-apple bag. Which is heavier?",
      "the bag with 6 apples",
      ["the bag with 4 apples", "they are the same"],
      2,
    ),
    I(
      "What should you do instead of just guessing a number?",
      "measure it",
      ["guess and write anything", "skip measuring"],
      3,
    ),
    I(
      "Two cups of water: one looks fuller. What should you do?",
      "measure to check",
      ["just guess which is more", "ignore it"],
      3,
    ),
    I(
      "Plant A grew 3cm, Plant B grew 5cm. Which grew more?",
      "Plant B",
      ["Plant A", "they grew the same"],
      2,
    ),
    I(
      "Why compare with numbers instead of just looking?",
      "numbers are more accurate",
      ["looking is always accurate", "numbers do not matter"],
      4,
    ),
    I(
      "A pencil is 15cm, a crayon 8cm. Which is longer?",
      "the pencil",
      ["the crayon", "they are equal"],
      2,
    ),
    I(
      "One cup has 3 blocks of water, another 6. Which has more?",
      "the cup with 6 blocks",
      ["the cup with 3 blocks", "they are the same"],
      2,
    ),
    I(
      "You measure a table twice and get different numbers. What went wrong?",
      "you did not start from the same spot",
      ["the table changed size", "nothing went wrong"],
      4,
    ),
    I(
      "Why write down your measurement instead of just remembering it?",
      "so you do not forget or mix it up",
      ["writing takes too long", "it does not matter"],
      3,
    ),
    I(
      "Two bags: 7 marbles and 9 marbles. Which bag is heavier?",
      "probably the 9-marble bag",
      ["the 7-marble bag", "they must weigh the same"],
      3,
    ),
    I(
      "Which is the fairest way to compare two plants' height?",
      "measure both with the same ruler",
      ["guess by looking", "measure one with a ruler, one by eye"],
      4,
    ),
    I(
      "A rock feels heavy. How can you know exactly how heavy?",
      "weigh it on a scale",
      ["just guess a number", "compare it to a feather"],
      3,
    ),
    I(
      "Which tool would you use to compare two bottles of juice?",
      "a measuring cup",
      ["a ruler", "a scale"],
      2,
    ),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} compares two things. Tap it!",
    "Listen carefully, then choose.",
    "Which is right? Tap it.",
    "Listen again and pick one.",
    "Think, then tap.",
  ],
  listens: [
    L(
      "One plant is 5 cubes tall. Another is 8 cubes tall. Which is taller?",
      "the 8-cube plant",
      ["the 5-cube plant", "they are the same"],
      2,
    ),
    L("A ruler measures how long something is.", "true", ["false"], 1),
    L("A scale measures how heavy something is.", "true", ["false"], 2),
    L("You should start measuring from a different spot each time.", "false", ["true"], 3),
    L(
      "Plant A grew 3 centimetres, Plant B grew 5. Which grew more?",
      "Plant B",
      ["Plant A", "same"],
      3,
    ),
    L("A measuring cup measures how much liquid there is.", "true", ["false"], 2),
    L("Guessing is just as fair as measuring.", "false", ["true"], 3),
  ],
  builds: [],
  sorts: [
    {
      q: "Sort the ways of measuring: fair, or not fair?",
      zones: ["Fair", "Not fair"],
      a: ["measure from the same spot every time", "use a ruler and record numbers"],
      b: ["guess by looking", "measure from different spots"],
      d: 4,
      hint: "A fair measurement uses the same tool and the same starting point.",
    },
  ],
  places: [
    {
      q: "Match each tool to what it measures.",
      items: [
        [null, "📏"],
        [null, "⚖️"],
      ],
      zones: [["length"], ["weight"]],
      key: { 0: [0], 1: [1] },
      d: 2,
      hint: "One measures how long, one measures how heavy.",
      why: "Ruler for length, scale for weight.",
    },
  ],
  reads: [
    "Use a ruler to measure length.",
    "Use a scale to measure weight.",
    "Always measure from the same spot.",
    "Numbers are more accurate than guessing.",
    "A measuring cup shows how much liquid there is.",
  ],
  writes: [
    [
      "Measure two objects at home. Write which is longer.",
      "the spoon is longer than the fork",
      ["Có hai vật", "So sánh đúng"],
    ],
    ["Draw a ruler measuring a pencil. Write the length.", "10 cm", ["Có tranh thước", "Có số đo"]],
  ],
});

// ─────────────────────────────────────── animal body parts help survival ──────────────────────
sentencePack({
  ...base,
  code: "ESCI.LS.ANIMAL_BODY_PARTS_SURVIVE",
  prefix: "esci-bodyparts",
  src: NGSS("1-LS1-1", "body parts and survival"),
  note: "Nối bộ phận (beak, claws, fur, fins, shell, wings) với chức năng giúp con vật sống sót. Ô nhiễu nhắm lỗi nói bộ phận mà không nói chức năng, nghĩ mọi con vật đều có lông.",
  items: [
    I(
      "How does a bird's beak help it?",
      "it helps it eat",
      ["it helps it swim", "it helps it hear"],
      1,
      { pic: "🦜" },
    ),
    I(
      "How do a cat's claws help it?",
      "they help it climb and grab",
      ["they help it fly", "they help it breathe underwater"],
      1,
      { pic: "🐱" },
    ),
    I(
      "How does a fish's fins help it?",
      "they help it swim",
      ["they help it fly", "they help it dig"],
      1,
      { pic: "🐟" },
    ),
    I(
      "How does a turtle's shell help it?",
      "it protects its body",
      ["it helps it fly", "it helps it hear"],
      2,
      { pic: "🐢" },
    ),
    I(
      "How does a bird's wings help it?",
      "they help it fly",
      ["they help it swim", "they help it dig"],
      1,
      { pic: "🦅" },
    ),
    I(
      "Do all animals have fur?",
      "no, only some animals do",
      ["yes, all animals do", "only fish have fur"],
      3,
    ),
    I(
      "How does thick fur help a bear?",
      "it helps keep it warm",
      ["it helps it fly", "it helps it breathe underwater"],
      2,
      { pic: "🐻" },
    ),
    I(
      "A rabbit has strong back legs. How does that help it?",
      "it helps it hop away fast",
      ["it helps it swim", "it helps it dig for food"],
      3,
    ),
    I(
      "A duck has webbed feet. How does that help it?",
      "it helps it swim",
      ["it helps it climb trees", "it helps it dig burrows"],
      3,
    ),
    I(
      "A woodpecker has a strong, pointy beak. How does that help it?",
      "it helps it peck into wood for food",
      ["it helps it swim fast", "it helps it fly higher"],
      4,
    ),
    I(
      "An owl has sharp claws called talons. How do they help it?",
      "they help it catch prey",
      ["they help it swim", "they help it sing"],
      4,
    ),
    I(
      "A camel has humps that store fat. How does that help it?",
      "it helps it survive without food for a while",
      ["it helps it fly", "it helps it swim"],
      4,
    ),
    I(
      "A skunk sprays a bad smell. How does that help it?",
      "it scares predators away",
      ["it helps it fly", "it helps it swim"],
      4,
    ),
    I(
      "A chameleon changes colour. How does that help it?",
      "it hides from predators",
      ["it helps it fly", "it helps it dig"],
      4,
    ),
    I(
      "Why do some birds have long legs, like a flamingo?",
      "to wade in water and reach food",
      ["to fly higher", "to keep them warm"],
      4,
    ),
    I(
      "A porcupine has sharp quills. How do they help it?",
      "they protect it from predators",
      ["they help it swim", "they help it fly"],
      3,
    ),
    I(
      "An elephant has a long trunk. How does it help?",
      "it grabs food and drinks water",
      ["it helps it fly", "it helps it swim fast"],
      3,
    ),
    I(
      "A giraffe has a very long neck. How does that help it?",
      "it reaches leaves high in trees",
      ["it helps it swim", "it helps it dig burrows"],
      3,
    ),
  ],
  listenPrompts: [
    "Listen, then tap the answer.",
    "{ban} talks about an animal part. Tap it!",
    "Listen carefully, then choose.",
    "How does it help? Tap it.",
    "Listen again and pick one.",
    "Think about survival, then tap.",
  ],
  listens: [
    L("A bird's beak helps it do what?", "eat", ["swim", "hear"], 1),
    L("A fish's fins help it do what?", "swim", ["fly", "dig"], 1),
    L("A turtle's shell helps it do what?", "protect its body", ["fly", "hear better"], 2),
    L("Thick fur helps a bear do what?", "stay warm", ["fly", "breathe underwater"], 2),
    L("A duck's webbed feet help it do what?", "swim", ["climb trees", "dig"], 3),
    L("Sharp quills help a porcupine do what?", "stay protected", ["swim", "fly"], 3),
    L(
      "A long trunk helps an elephant do what?",
      "grab food and drink water",
      ["fly", "swim fast"],
      3,
    ),
  ],
  builds: [],
  sorts: [
    {
      q: "Sort the parts: for moving, or for protecting?",
      zones: ["For moving", "For protecting"],
      a: ["wings", "fins", "claws"],
      b: ["shell", "fur"],
      d: 4,
      hint: "Some parts help an animal go places, others keep it safe.",
    },
  ],
  places: [
    {
      q: "Match each body part to what it helps the animal do.",
      items: [
        [null, "🦜"],
        [null, "🐢"],
        [null, "🐻"],
      ],
      zones: [["eat"], ["protect its body"], ["stay warm"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 3,
      hint: "Beak for eating, shell for protecting, fur for warmth.",
      why: "Beak-eat, shell-protect, fur-warmth.",
    },
    {
      q: "Match each animal to how it survives.",
      items: [
        [null, "🦔"],
        [null, "🐘"],
      ],
      zones: [["sharp quills protect it"], ["a trunk grabs food and water"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "Think about what each body part does.",
      why: "Porcupine-quills protect, elephant-trunk grabs.",
    },
  ],
  reads: [
    "A bird's beak helps it eat.",
    "A turtle's shell protects its body.",
    "Thick fur keeps an animal warm.",
    "Fins help a fish swim.",
    "Sharp quills protect a porcupine.",
  ],
  writes: [
    [
      "Draw an animal and one body part that helps it survive.",
      "a bird's wings help it fly",
      ["Có tranh động vật", "Nêu đúng chức năng"],
    ],
    [
      "Draw two animals with different body parts. Label the parts.",
      "fins, wings",
      ["Hai con vật", "Hai nhãn đúng"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── animal groups ────────────────────
sentencePack({
  ...base,
  code: "ESCI.LS.ANIMAL_GROUPS",
  prefix: "esci-animalgroup",
  src: NGSS("1-LS1-1", "classifying animals"),
  note: "Phân loại mammals, birds, fish, reptiles, amphibians, insects theo đặc điểm. Ô nhiễu nhắm lỗi thật (xếp dolphin vào fish, penguin không bay được vẫn là chim, spider không phải insect).",
  items: [
    I("A dog has fur and feeds babies milk. What group?", "mammal", ["bird", "fish"], 1, {
      pic: "🐶",
    }),
    I("An eagle has feathers and wings. What group is it?", "bird", ["mammal", "reptile"], 1, {
      pic: "🦅",
    }),
    I(
      "A shark has scales, gills, and lives in water. What group?",
      "fish",
      ["mammal", "amphibian"],
      2,
      { pic: "🦈" },
    ),
    I(
      "A snake has dry scales and lays eggs. What group is it?",
      "reptile",
      ["amphibian", "insect"],
      2,
      { pic: "🐍" },
    ),
    I("A frog lives in water, then on land. What group?", "amphibian", ["reptile", "fish"], 3, {
      pic: "🐸",
    }),
    I("An ant has six legs, three body parts. What group?", "insect", ["mammal", "reptile"], 2, {
      pic: "🐜",
    }),
    I("Is a dolphin a fish?", "no, it is a mammal", ["yes, it is a fish", "it is a bird"], 4),
    I(
      "Is a penguin still a bird, even though it cannot fly?",
      "yes, it is a bird",
      ["no, it is a fish", "no, it is a mammal"],
      4,
    ),
    I(
      "Is a spider an insect?",
      "no, spiders have 8 legs, not 6",
      ["yes, it is an insect", "it is a bird"],
      5,
    ),
    I("Which group has feathers?", "birds", ["mammals", "fish"], 1),
    I("Which group has fur or hair and feeds babies milk?", "mammals", ["birds", "insects"], 1),
    I("Which group has 6 legs?", "insects", ["mammals", "reptiles"], 2),
    I("Which group breathes with gills and lives fully in water?", "fish", ["mammals", "birds"], 2),
    I(
      "Which group has dry, waterproof scales and lays eggs on land?",
      "reptiles",
      ["amphibians", "fish"],
      3,
    ),
    I(
      "A whale lives in the sea, breathes air, feeds milk. What group?",
      "mammal",
      ["fish", "amphibian"],
      5,
    ),
    I(
      "Is a bat a bird because it flies?",
      "no, it is a mammal with fur",
      ["yes, it is a bird", "no, it is an insect"],
      5,
    ),
    I(
      "Which group starts in water, then lives on land as adults?",
      "amphibians",
      ["reptiles", "fish"],
      4,
    ),
    I("Which group usually has three body parts and six legs?", "insects", ["mammals", "birds"], 2),
  ],
  listenPrompts: [
    "Listen, then tap the animal group.",
    "{ban} describes an animal. Tap the group!",
    "Listen carefully, then choose.",
    "Which group is it? Tap it.",
    "Listen again and pick one.",
    "Think about the clues, then tap.",
  ],
  listens: [
    L("It has fur and feeds its babies milk. What group?", "mammal", ["bird", "fish"], 1),
    L("It has feathers and wings. What group?", "bird", ["mammal", "reptile"], 1),
    L("It has scales, gills, and lives in water. What group?", "fish", ["amphibian", "mammal"], 2),
    L("It has six legs and three body parts. What group?", "insect", ["reptile", "mammal"], 2),
    L("Is a dolphin a fish or a mammal?", "mammal", ["fish"], 4),
    L("It has dry scales and lays eggs on land. What group?", "reptile", ["amphibian", "fish"], 3),
    L(
      "It starts in water, then lives on land as an adult. What group?",
      "amphibian",
      ["reptile", "fish"],
      3,
    ),
  ],
  builds: [],
  sorts: [
    {
      q: "Sort the animals: mammal or bird?",
      zones: ["Mammal", "Bird"],
      a: ["dog", "cat"],
      b: ["eagle", "duck"],
      d: 2,
      hint: "Fur and milk means mammal; feathers means bird.",
    },
    {
      q: "Sort the animals: fish or reptile?",
      zones: ["Fish", "Reptile"],
      a: ["shark", "tuna"],
      b: ["snake", "lizard"],
      d: 3,
      hint: "Fish live fully in water with gills; reptiles have dry scales.",
    },
  ],
  places: [
    {
      q: "Drag each animal to its group.",
      items: [
        [null, "🐶"],
        [null, "🦅"],
        [null, "🐜"],
      ],
      zones: [["mammal"], ["bird"], ["insect"]],
      key: { 0: [0], 1: [1], 2: [2] },
      d: 3,
      hint: "Fur, feathers, or six legs?",
      why: "Dog-mammal, eagle-bird, ant-insect.",
    },
  ],
  reads: [
    "Mammals have fur and feed their babies milk.",
    "Birds have feathers and most can fly.",
    "Fish live in water and have gills.",
    "Insects have six legs.",
    "Reptiles have dry, waterproof scales.",
  ],
  writes: [
    [
      "Draw one animal from each group: mammal, bird, fish.",
      "dog, eagle, shark",
      ["Ba nhóm đúng", "Có tranh"],
    ],
    ["Draw an insect. Label its legs.", "ant, 6 legs", ["Có tranh côn trùng", "Ghi đúng số chân"]],
  ],
});

// ─────────────────────────────────────────────────────────── animal vocab ─────────────────────
sentencePack({
  ...base,
  code: "ESCI.VOC.ANIMAL_WORDS",
  prefix: "esci-animalvoc",
  src: NGSS("1-LS1-1", "animal vocabulary"),
  note: "Từ vựng fur, feathers, scales, wings, fins, beak, claws, mammal, bird, fish, insect, puppy, kitten, chick, calf. Ô nhiễu nhắm nhầm fin/wing, scales/shell.",
  items: [
    I("Which word means the soft covering on a cat?", "fur", ["feathers", "scales"], 1, {
      pic: "🐱",
    }),
    I("Which word means the covering on a bird?", "feathers", ["fur", "fins"], 1, { pic: "🦜" }),
    I("Which word means the covering on a fish or snake?", "scales", ["feathers", "fur"], 1, {
      pic: "🐍",
    }),
    I("Which word means the part a bird flies with?", "wings", ["fins", "claws"], 2),
    I("Which word means the part a fish swims with?", "fins", ["wings", "beak"], 2),
    I("Which word means a bird's mouth part?", "beak", ["fins", "fur"], 1, { pic: "🦆" }),
    I("Which word means sharp nails on an animal's feet?", "claws", ["scales", "wings"], 2),
    I(
      "Which word means an animal with fur that feeds milk to babies?",
      "mammal",
      ["insect", "fish"],
      3,
    ),
    I("Which word means a baby dog?", "puppy", ["kitten", "chick"], 1, { pic: "🐶" }),
    I("Which word means a baby cat?", "kitten", ["puppy", "calf"], 1, { pic: "🐱" }),
    I("Which word means a baby chicken?", "chick", ["calf", "kitten"], 2, { pic: "🐤" }),
    I("Which word means a baby cow?", "calf", ["chick", "puppy"], 2, { pic: "🐮" }),
    I(
      "A fin and a wing both help an animal move, but where?",
      "fins in water, wings in air",
      ["they are the same thing", "fins in air, wings in water"],
      4,
    ),
    I(
      "Are scales and a shell the same thing?",
      "no, a shell is hard and separate",
      ["yes, they are the same", "scales are always soft"],
      4,
    ),
    I("Which word means a baby duck?", "duckling", ["kitten", "calf"], 3, { pic: "🦆" }),
    I("Which word means a group of animals with feathers?", "bird", ["mammal", "insect"], 2),
    I("Which word means a group of animals with six legs?", "insect", ["mammal", "bird"], 2),
    I(
      "Which word means animals that live in water and have gills?",
      "fish",
      ["mammal", "insect"],
      2,
    ),
  ],
  listenPrompts: [
    "Listen, then tap the word.",
    "{ban} says an animal word. Tap it!",
    "Listen carefully, then choose.",
    "Which word is it? Tap it.",
    "Listen again and pick one.",
    "Listen for the animal word.",
  ],
  listens: [
    L("fur", "fur", ["feathers", "scales"], 1),
    L("feathers", "feathers", ["fur", "fins"], 1),
    L("scales", "scales", ["feathers", "fur"], 1),
    L("wings", "wings", ["fins", "claws"], 2),
    L("fins", "fins", ["wings", "beak"], 2),
    L("puppy", "puppy", ["kitten", "chick"], 1),
    L("calf", "calf", ["chick", "kitten"], 2),
    L("claws", "claws", ["scales", "wings"], 2),
  ],
  builds: [],
  sorts: [
    {
      q: "Sort the words: covering, or body part for moving?",
      zones: ["Covering", "For moving"],
      a: ["fur", "feathers", "scales"],
      b: ["wings", "fins", "claws"],
      d: 3,
      hint: "Which words describe the outside skin/coat?",
    },
    {
      q: "Sort the baby animal words to their parent.",
      zones: ["Dog family", "Cat family", "Chicken family", "Cow family"],
      a: ["puppy"],
      b: ["kitten"],
      d: 3,
      hint: "Match each baby word to its parent animal.",
    },
  ],
  places: [
    {
      q: "Match each baby animal word to its picture.",
      items: [
        [null, "🐶"],
        [null, "🐱"],
        [null, "🐤"],
        [null, "🐮"],
      ],
      zones: [["puppy"], ["kitten"], ["chick"], ["calf"]],
      key: { 0: [0], 1: [1], 2: [2], 3: [3] },
      d: 2,
      hint: "Think about which baby belongs to which animal.",
      why: "Puppy-dog, kitten-cat, chick-chicken, calf-cow.",
    },
  ],
  reads: [
    "A cat has soft fur.",
    "A bird has feathers and a beak.",
    "A fish has scales and fins.",
    "A puppy is a baby dog.",
  ],
  writes: [
    [
      "Draw an animal covering: fur, feathers, or scales. Label it.",
      "fur",
      ["Có tranh", "Ghi đúng từ"],
    ],
    [
      "Draw a baby animal and its parent. Label both.",
      "puppy, dog",
      ["Hai tranh", "Hai nhãn đúng"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── parents & offspring ──────────────
sentencePack({
  ...base,
  code: "ESCI.LS.PARENTS_OFFSPRING",
  prefix: "esci-offspring",
  src: NGSS("1-LS3-1", "young animals resemble parents"),
  note: "Con non giống bố mẹ nhưng không giống hệt; nối baby animals với parents. Ô nhiễu nhắm lỗi nối theo màu thay vì theo loài.",
  items: [
    I("Which baby belongs to the dog?", "puppy", ["kitten", "chick"], 1, { pic: "🐶" }),
    I("Which baby belongs to the cat?", "kitten", ["puppy", "calf"], 1, { pic: "🐱" }),
    I("Which baby belongs to the cow?", "calf", ["chick", "kitten"], 2, { pic: "🐮" }),
    I("Which baby belongs to the hen?", "chick", ["calf", "puppy"], 2, { pic: "🐔" }),
    I("Which baby belongs to the duck?", "duckling", ["kitten", "calf"], 2, { pic: "🦆" }),
    I(
      "Does a baby duck look exactly the same as its parent?",
      "no, it looks similar but not exactly the same",
      ["yes, exactly the same", "no, it looks nothing alike"],
      3,
    ),
    I(
      "A black cat has an orange kitten. Is that still her baby?",
      "yes, colour can be a bit different",
      ["no, it must be the same colour", "no, it must belong to another cat"],
      4,
    ),
    I(
      "Do baby animals usually look somewhat like their parents?",
      "yes, somewhat like them",
      ["no, never alike", "yes, always exactly alike"],
      3,
    ),
    I("Which word describes a baby horse?", "foal", ["calf", "chick"], 4),
    I("Which word describes a baby sheep?", "lamb", ["kitten", "calf"], 3),
    I(
      "Two brown dogs have puppies. What colour might the puppies be?",
      "brown, or a similar colour",
      ["always bright green", "always white with stripes"],
      4,
    ),
    I(
      "How can you tell a puppy belongs to a certain dog?",
      "it looks similar to that dog",
      ["by its favourite toy", "by the colour of the leash"],
      3,
    ),
    I("Which word describes a baby pig?", "piglet", ["calf", "chick"], 4),
    I("Which word describes a baby goat?", "kid", ["lamb", "foal"], 4),
    I(
      "A white hen lays a brown egg. What colour is the chick?",
      "brown, white, or a mix",
      ["always bright blue", "always green with spots"],
      5,
    ),
    I(
      "Do all puppies from the same parents look exactly the same?",
      "no, they can look a little different",
      ["yes, always exactly the same", "no, they look nothing alike"],
      4,
    ),
    I(
      "Why might two puppies from the same mother look slightly different?",
      "each baby can have small differences",
      ["puppies never have differences", "they must have different mothers"],
      5,
    ),
  ],
  listenPrompts: [
    "Listen, then tap the baby animal.",
    "{ban} names an animal. Tap its baby!",
    "Listen carefully, then choose.",
    "Which baby is it? Tap it.",
    "Listen again and pick one.",
    "Think about the parent, then tap.",
  ],
  listens: [
    L("Which baby belongs to the dog?", "puppy", ["kitten", "chick"], 1),
    L("Which baby belongs to the cat?", "kitten", ["puppy", "calf"], 1),
    L("Which baby belongs to the cow?", "calf", ["chick", "kitten"], 2),
    L("Which baby belongs to the hen?", "chick", ["calf", "puppy"], 2),
    L("Which baby belongs to the duck?", "duckling", ["kitten", "calf"], 3),
    L("Which word describes a baby pig?", "piglet", ["calf", "chick"], 4),
    L("Which word describes a baby sheep?", "lamb", ["kitten", "calf"], 3),
  ],
  builds: [],
  sorts: [
    {
      q: "Sort each baby animal to its parent's family.",
      zones: ["Dog family", "Cat family"],
      a: ["puppy"],
      b: ["kitten"],
      d: 1,
      hint: "Match the baby word to the right parent.",
    },
  ],
  places: [
    {
      q: "Match each baby animal to its parent.",
      items: [
        [null, "🐶"],
        [null, "🐱"],
        [null, "🐮"],
        [null, "🐔"],
      ],
      zones: [["puppy"], ["kitten"], ["calf"], ["chick"]],
      key: { 0: [0], 1: [1], 2: [2], 3: [3] },
      d: 2,
      hint: "Think about which baby belongs to which parent.",
      why: "Puppy-dog, kitten-cat, calf-cow, chick-hen.",
    },
    {
      q: "Match each parent to its baby, even with different colours.",
      items: [["black cat with an orange kitten"], ["brown dog with a black puppy"]],
      zones: [["still her kitten"], ["still his puppy"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "Colour can differ, but the baby still belongs to that parent.",
      why: "Offspring can look a bit different in colour.",
    },
  ],
  reads: [
    "A puppy is a baby dog.",
    "A kitten is a baby cat.",
    "A calf is a baby cow.",
    "Baby animals look similar to their parents.",
    "A piglet is a baby pig.",
    "A lamb is a baby sheep.",
  ],
  writes: [
    [
      "Draw a parent animal and its baby. Label both.",
      "hen, chick",
      ["Hai tranh", "Hai nhãn đúng"],
    ],
    [
      "Draw a puppy that looks different from its parent. Explain why.",
      "same family, different colour",
      ["Có tranh", "Giải thích hợp lý"],
    ],
  ],
});
