/**
 * Pha 6c, lô A1 — ESL: 10 kỹ năng trống của tuần 13–18 (2/12 kỹ năng của danh sách gốc bị bỏ:
 * VOC.WEATHER và VOC.DAYS_OF_WEEK đã "Ngừng dùng 11/09/2026" trong chính mô tả kỹ năng — Global
 * Stage 1 không dạy hai chủ đề này; DB có bị seed ảnh cũ bật nhầm `isActive`, đã sửa trực tiếp
 * bằng script riêng, không sinh bài cho hai kỹ năng đó).
 *
 * Từ vựng CLOTHES và BEDROOM_FURNITURE lấy đúng danh sách Global Stage 1 Language Book Unit 5
 * "Where Are My Shoes?" (docs/09 §4b.1) — khác nhẹ so với ví dụ trong mô tả kỹ năng (mô tả cũ đoán
 * trước khi có bảng chương trình); dùng danh sách thật của sách. Unit 6 "Look What I Can Do" cho
 * ACTIVITIES_GO_PLAY_DO. BLENDS_FINAL/INITIAL, PLURAL_S, PLAYGROUND không có trong bảng Global Stage
 * → CCSS/Kids A-Z, ghi rõ "chưa có sách".
 *
 *   node scripts/content-gen/esl-dot4.mjs
 */
import { sentencePack, vocabPack } from "./lib-en.mjs";

const base = { dir: "esl", subject: "ESL" };
const LB5 =
  "Global Stage 1 Language Book Unit 5 Where Are My Shoes? (GS1-LB.U5, bảng chương trình) — chưa chụp trang sách";
const LB6 =
  "Global Stage 1 Language Book Unit 6 Look What I Can Do (GS1-LB.U6, bảng chương trình) — chưa chụp trang sách";
const CC = (std, topic) => `CCSS ${std} (${topic}) — ESL chưa có giáo trình của trường`;
const P = (e, w) => ({ e, w });
const DROP = "doc_bo_tu_tieng_anh";
const SP = "sai_chinh_ta_tu";

// ─────────────────────────────────────────────────────────── final blends ────────────────────
sentencePack({
  ...base,
  code: "ESL.PH.BLENDS_FINAL",
  prefix: "esl-blendfin",
  src: "Chuẩn đọc Kids A-Z / CCSS RF.1.3a (final consonant blends) — Global Stage 1 chỉ dạy blend đầu, chưa có sách cho blend cuối",
  note: "Đọc từ kết thúc bằng hai phụ âm (-nd, -st, -mp, -nk). Ô nhiễu: bỏ phụ âm cuối cùng (hand → han, sai_chinh_ta_tu — đúng lỗi 'bỏ âm cuối cùng'), đổi nguyên âm (nham_nguyen_am_ngan).",
  items: [
    {
      q: "Which is the whole word?",
      right: "hand",
      wrongs: [
        ["han", SP],
        ["hend", "nham_nguyen_am_ngan"],
      ],
      pic: "✋",
      d: 1,
      hint: "Say all four sounds: h-a-n-d.",
    },
    {
      q: "Which is the whole word?",
      right: "nest",
      wrongs: [
        ["nes", SP],
        ["nast", "nham_nguyen_am_ngan"],
      ],
      pic: "🪺",
      d: 1,
      hint: "Say all four sounds: n-e-s-t.",
    },
    {
      q: "Which is the whole word?",
      right: "jump",
      wrongs: [
        ["jum", SP],
        ["jamp", "nham_nguyen_am_ngan"],
      ],
      pic: "🏃",
      d: 2,
      hint: "Don't drop the last sound.",
    },
    {
      q: "Which is the whole word?",
      right: "pink",
      wrongs: [
        ["pin", SP],
        ["ponk", "nham_nguyen_am_ngan"],
      ],
      pic: "🩷",
      d: 2,
      hint: "Don't drop the last sound.",
    },
    {
      q: "Which is the whole word?",
      right: "milk",
      wrongs: [
        ["mik", SP],
        ["melk", "nham_nguyen_am_ngan"],
      ],
      pic: "🥛",
      d: 2,
      hint: "Say all the sounds: m-i-l-k.",
    },
    {
      q: "Which is the whole word?",
      right: "lamp",
      wrongs: [
        ["lam", SP],
        ["limp", "nham_nguyen_am_ngan"],
      ],
      pic: "💡",
      d: 3,
      hint: "Don't drop the last sound.",
    },
    {
      q: "Which is the whole word?",
      right: "tent",
      wrongs: [
        ["ten", SP],
        ["tint", "nham_nguyen_am_ngan"],
      ],
      pic: "⛺",
      d: 3,
      hint: "Say all four sounds: t-e-n-t.",
    },
    {
      q: "Which is the whole word?",
      right: "desk",
      wrongs: [
        ["des", SP],
        ["disk", "nham_nguyen_am_ngan"],
      ],
      pic: "🪑",
      d: 3,
      hint: "Don't drop the last sound.",
    },
    {
      q: "Which is the whole word?",
      right: "band",
      wrongs: [
        ["ban", SP],
        ["bend", "nham_nguyen_am_ngan"],
      ],
      pic: "🎸",
      d: 4,
      hint: "Say all four sounds: b-a-n-d.",
    },
    {
      q: "Which is the whole word?",
      right: "fist",
      wrongs: [
        ["fis", SP],
        ["fast", "nham_nguyen_am_ngan"],
      ],
      pic: "✊",
      d: 4,
      hint: "Don't drop the last sound.",
    },
    {
      q: "Which is the whole word?",
      right: "sink",
      wrongs: [
        ["sik", SP],
        ["sank", "nham_nguyen_am_ngan"],
      ],
      pic: "🚰",
      d: 4,
      hint: "Say all four sounds: s-i-n-k.",
    },
    {
      q: "Which is the whole word?",
      right: "wind",
      wrongs: [
        ["win", SP],
        ["wend", "nham_nguyen_am_ngan"],
      ],
      pic: "🌬️",
      d: 5,
      hint: "Say all four sounds: w-i-n-d.",
    },
    {
      q: "Which is the whole word?",
      right: "vest",
      wrongs: [
        ["ves", SP],
        ["vast", "nham_nguyen_am_ngan"],
      ],
      pic: "🦺",
      d: 5,
      hint: "Say all four sounds: v-e-s-t.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the whole word.",
    "{ban} says a word. Tap it!",
    "Listen for every sound, then choose.",
    "Which spelling matches? Tap it.",
    "Listen again and pick one.",
    "Say the sounds, then tap.",
  ],
  listens: [
    ["hand", "han", "hend"],
    ["jump", "jum", "jamp"],
    ["pink", "pin", "ponk"],
    ["nest", "nes", "nast"],
    ["milk", "mik", "melk"],
    ["lamp", "lam", "limp"],
    ["tent", "ten", "tint"],
    ["band", "ban", "bend"],
    ["sink", "sik", "sank"],
    ["desk", "des", "disk"],
    ["wind", "win", "wend"],
    ["fist", "fis", "fast"],
  ].map(([w, drop, vw], i) => ({
    say: w,
    right: w,
    wrongs: [
      [drop, SP],
      [vw, "nham_nguyen_am_ngan"],
    ],
    d: 1 + (i % 5),
  })),
  sorts: [
    {
      q: "Ends in -nd or -st? Sort them.",
      zones: ["-nd", "-st"],
      a: ["hand", "band"],
      b: ["nest", "fist"],
      d: 3,
      hint: "Say the last two sounds.",
    },
    {
      q: "Ends in -mp or -nk? Sort them.",
      zones: ["-mp", "-nk"],
      a: ["jump", "lamp"],
      b: ["pink", "sink"],
      d: 4,
      hint: "Say the last two sounds.",
    },
  ],
  places: [
    {
      q: "Build hand: drag the sounds in order.",
      items: [["d"], ["h"], ["a"], ["n"]],
      zones: [["1"], ["2"], ["3"], ["4"]],
      key: { 0: [1], 1: [2], 2: [3], 3: [0] },
      d: 3,
      hint: "h-a-n-d.",
      why: "hand is h-a-n-d.",
    },
    {
      q: "Build milk: drag the sounds in order.",
      items: [["k"], ["m"], ["l"], ["i"]],
      zones: [["1"], ["2"], ["3"], ["4"]],
      key: { 0: [1], 1: [3], 2: [2], 3: [0] },
      d: 4,
      hint: "m-i-l-k.",
      why: "milk is m-i-l-k.",
    },
  ],
  reads: [
    "I hold his hand.",
    "The bird made a nest.",
    "I can jump high.",
    "My shirt is pink.",
    "I drink milk.",
    "Turn on the lamp.",
  ],
  writes: [
    ["Draw a hand. Write: hand.", "hand", ["Vẽ bàn tay", "Viết đủ 4 chữ h-a-n-d"]],
    ["Draw a tent. Write: tent.", "tent", ["Vẽ lều", "Viết đủ 4 chữ t-e-n-t"]],
    ["Write: jump, milk, desk.", "jump milk desk", ["Ba từ đúng chính tả", "Không bỏ âm cuối"]],
  ],
});

// ─────────────────────────────────────────────────────────── possessive my/your/his/her ──────
sentencePack({
  ...base,
  code: "ESL.GR.POSSESSIVE_MY_YOUR",
  prefix: "esl-poss",
  src: LB5,
  note: "my/your/his/her theo đúng người. Dữ kiện giới tính/người nói cho trong ngoặc tiếng Việt để câu có một đáp án; ô nhiễu là nhầm his/her theo giới tính hoặc dùng 'me' thay 'my' — đúng hai lỗi của mô tả kỹ năng.",
  items: [
    {
      q: "Point to yourself. '___ name is Sam.'",
      right: "My",
      wrongs: [["Me"], ["Your"]],
      d: 1,
      hint: "You are talking about yourself.",
    },
    {
      q: "Talking to a friend: '___ bag is red.' (túi của bạn ấy)",
      right: "Your",
      wrongs: [["My"], ["His"]],
      d: 1,
      hint: "You are talking to them.",
    },
    {
      q: "This is Tom (a boy). '___ dad is a doctor.'",
      right: "His",
      wrongs: [["Her"], ["My"]],
      d: 2,
      hint: "Tom is a boy.",
    },
    {
      q: "This is Mai (a girl). '___ dad is a doctor.'",
      right: "Her",
      wrongs: [["His"], ["My"]],
      d: 2,
      hint: "Mai is a girl.",
    },
    {
      q: "Which is right?",
      right: "This is my mom.",
      wrongs: [["This is me mom."], ["This is I mom."]],
      d: 2,
      hint: "My, not me, before a noun.",
    },
    {
      q: "Which is right?",
      right: "Is this your book?",
      wrongs: [["Is this you book?"], ["Is this you're book?"]],
      d: 3,
      hint: "Your shows ownership.",
    },
    {
      q: "Ben (a boy) lost ___ shoe.",
      right: "his",
      wrongs: [["her"], ["its"]],
      d: 3,
      hint: "Ben is a boy.",
    },
    {
      q: "Ann (a girl) lost ___ shoe.",
      right: "her",
      wrongs: [["his"], ["its"]],
      d: 3,
      hint: "Ann is a girl.",
    },
    {
      q: "Talking about a dog: '___ tail is short.'",
      right: "Its",
      wrongs: [["His"], ["Her"]],
      d: 4,
      hint: "A dog is not he or she here — use its.",
    },
    {
      q: "Which is right?",
      right: "His name is Tom.",
      wrongs: [["He's name is Tom."], ["Him name is Tom."]],
      d: 4,
      hint: "His shows ownership of the name.",
    },
    {
      q: "Which is right?",
      right: "Her cat is white.",
      wrongs: [["She cat is white."], ["Hers cat is white."]],
      d: 5,
      hint: "Her comes before the noun.",
    },
    {
      q: "Talking to two friends: '___ team is great!'",
      right: "Your",
      wrongs: [["My"], ["Their"]],
      d: 5,
      hint: "You are talking to them.",
    },
    {
      q: "This is Lily (a girl). '___ hat is blue.'",
      right: "Her",
      wrongs: [["His"], ["Its"]],
      d: 3,
      hint: "Lily is a girl.",
    },
    {
      q: "Talking about a bird: '___ wings are small.'",
      right: "Its",
      wrongs: [["His"], ["Her"]],
      d: 4,
      hint: "A bird is not he or she here.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the word.",
    "{ban} says a sentence. Tap the missing word!",
    "Listen carefully, then choose.",
    "Which word fits? Tap it.",
    "Listen again and pick one.",
    "Think about who owns it.",
  ],
  listens: [
    {
      say: "This is my sister.",
      q: "Who is talking?",
      right: "the speaker, about their own sister",
      wrongs: [["a friend, about your sister"], ["a stranger"]],
      d: 3,
    },
    {
      say: "Tom lost his hat.",
      q: "Whose hat?",
      right: "Tom's (a boy)",
      wrongs: [["a girl's"], ["the speaker's"]],
      d: 2,
    },
    {
      say: "Mai found her pencil.",
      q: "Whose pencil?",
      right: "Mai's (a girl)",
      wrongs: [["a boy's"], ["the speaker's"]],
      d: 2,
    },
    {
      say: "Is this your bag?",
      q: "Who is being asked?",
      right: "you, the listener",
      wrongs: [["the speaker"], ["a third person"]],
      d: 3,
    },
    {
      say: "The cat licked its paw.",
      q: "Whose paw?",
      right: "the cat's",
      wrongs: [["his"], ["her"]],
      d: 4,
    },
    {
      say: "My brother and I share a room.",
      q: "Whose room?",
      right: "the speaker and their brother's",
      wrongs: [["your room"], ["his room only"]],
      d: 5,
    },
  ],
  builds: [
    "This is my mom.",
    "Is this your book?",
    "His name is Tom.",
    "Her cat is white.",
    "Its tail is short.",
  ],
  sorts: [
    {
      q: "For a boy or a girl? Sort the words.",
      zones: ["For a boy (his)", "For a girl (her)"],
      a: ["his hat", "his dad"],
      b: ["her hat", "her mom"],
      d: 3,
      hint: "his = he, her = she.",
    },
    {
      q: "About me or about you? Sort them.",
      zones: ["My", "Your"],
      a: ["my name", "my bag"],
      b: ["your turn", "your shoes"],
      d: 2,
      hint: "my = about me, your = about you.",
    },
  ],
  reads: [
    "This is my mom.",
    "Is this your bag?",
    "His name is Tom.",
    "Her cat is white.",
    "The dog licked its paw.",
  ],
  writes: [
    [
      "Draw your family. Write: This is my ___.",
      "This is my dad.",
      ["Có tranh", "Câu đúng mẫu This is my ___"],
    ],
    [
      "Draw a boy and write about him using his.",
      "His name is Tom.",
      ["Có tranh bé trai", "Dùng đúng his"],
    ],
    [
      "Draw a girl and write about her using her.",
      "Her bag is pink.",
      ["Có tranh bé gái", "Dùng đúng her"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── there is / there are ────────────
sentencePack({
  ...base,
  code: "ESL.GR.THERE_IS_ARE",
  prefix: "esl-thereis",
  src: LB5,
  note: "There is (một) / There are (nhiều). Ô nhiễu đúng ba lỗi của mô tả kỹ năng: is dùng cho số nhiều, are dùng cho số ít, dùng 'have' thay 'there is/are'.",
  items: [
    {
      q: "One bed in the room. Which is right?",
      right: "There is a bed.",
      wrongs: [["There are a bed."], ["The room have a bed."]],
      pic: "🛏️",
      d: 1,
      hint: "One thing: use is.",
    },
    {
      q: "Two chairs in the room. Which is right?",
      right: "There are two chairs.",
      wrongs: [["There is two chairs."], ["The room have two chairs."]],
      pic: ["🪑", 2],
      d: 1,
      hint: "More than one: use are.",
    },
    {
      q: "One lamp on the desk. Which is right?",
      right: "There is a lamp on the desk.",
      wrongs: [["There are a lamp on the desk."], ["It have a lamp."]],
      pic: "💡",
      d: 2,
      hint: "One thing: use is.",
    },
    {
      q: "Three pictures on the wall. Which is right?",
      right: "There are three pictures.",
      wrongs: [["There is three pictures."], ["The wall have three pictures."]],
      pic: ["🖼️", 3],
      d: 2,
      hint: "More than one: use are.",
    },
    {
      q: "How do you ask about one thing?",
      right: "Is there a rug?",
      wrongs: [["Are there a rug?"], ["Have a rug?"]],
      d: 3,
      hint: "One thing: use is.",
    },
    {
      q: "How do you ask about many things?",
      right: "Are there books?",
      wrongs: [["Is there books?"], ["Have books?"]],
      d: 3,
      hint: "More than one: use are.",
    },
    {
      q: "No chairs in the room. Which is right?",
      right: "There isn't a chair.",
      wrongs: [["There aren't a chair."], ["The room no have chair."]],
      d: 4,
      hint: "One thing, none of it: isn't.",
    },
    {
      q: "No pictures on the wall. Which is right?",
      right: "There aren't any pictures.",
      wrongs: [["There isn't any pictures."], ["The wall no have pictures."]],
      d: 4,
      hint: "More than one, none: aren't.",
    },
    {
      q: "One closet, two windows. Which sentence fits the closet?",
      right: "There is one closet.",
      wrongs: [["There are one closet."], ["It have one closet."]],
      d: 4,
      hint: "One thing: use is.",
    },
    {
      q: "One table and four chairs. Which is right?",
      right: "There is a table and there are four chairs.",
      wrongs: [
        ["There is a table and four chairs is there."],
        ["There are a table and four chairs."],
      ],
      d: 5,
      hint: "Match is/are to each thing.",
    },
    {
      q: "Two beds in the room. Which is right?",
      right: "There are two beds.",
      wrongs: [["There is two beds."], ["The room have two beds."]],
      pic: ["🛏️", 2],
      d: 2,
      hint: "More than one: use are.",
    },
    {
      q: "One rug on the floor. Which is right?",
      right: "There is a rug.",
      wrongs: [["There are a rug."], ["It have a rug."]],
      pic: "🟫",
      d: 2,
      hint: "One thing: use is.",
    },
    {
      q: "Five books on the desk. Which is right?",
      right: "There are five books.",
      wrongs: [["There is five books."], ["The desk have five books."]],
      pic: ["📚", 5],
      d: 3,
      hint: "More than one: use are.",
    },
    {
      q: "One clock on the wall. Which is right?",
      right: "There is one clock.",
      wrongs: [["There are one clock."], ["The wall have a clock."]],
      pic: "🕐",
      d: 3,
      hint: "One thing: use is.",
    },
    {
      q: "Which question asks about the rug?",
      right: "Is there a rug?",
      wrongs: [["Are there a rug?"], ["Does there a rug?"]],
      d: 4,
      hint: "Rug is one thing.",
    },
    {
      q: "Which question asks about the books?",
      right: "Are there books?",
      wrongs: [["Is there books?"], ["Does there books?"]],
      d: 4,
      hint: "Books is more than one.",
    },
  ],
  listenPrompts: [
    "Listen, then tap what's in the room.",
    "{ban} describes a room. Tap the true sentence!",
    "Listen carefully, then choose.",
    "What is true? Tap it.",
    "Listen again and pick one.",
    "Listen for is or are.",
  ],
  listens: [
    {
      say: "There is a bed and a desk in my room.",
      q: "What is in the room?",
      right: "a bed and a desk",
      wrongs: [["two beds"], ["a chair only"]],
      d: 2,
    },
    {
      say: "There are three chairs at the table.",
      q: "How many chairs?",
      right: "three",
      wrongs: [["one"], ["two"]],
      d: 2,
    },
    {
      say: "There isn't a TV in my bedroom.",
      q: "Is there a TV?",
      right: "No",
      wrongs: [["Yes"]],
      d: 3,
    },
    {
      say: "There is one lamp and there are two pictures.",
      q: "How many lamps?",
      right: "one",
      wrongs: [["two"], ["none"]],
      d: 4,
    },
    {
      say: "Is there a rug on the floor?",
      q: "What kind of question is this?",
      right: "asking about one thing",
      wrongs: [["asking about many things"], ["not a question"]],
      d: 3,
    },
    {
      say: "There are five books on the desk.",
      q: "How many books?",
      right: "five",
      wrongs: [["one"], ["four"]],
      d: 3,
    },
    {
      say: "There isn't a clock on the wall.",
      q: "Is there a clock?",
      right: "No",
      wrongs: [["Yes"]],
      d: 4,
    },
  ],
  builds: [
    "There is a bed.",
    "There are two chairs.",
    "Is there a lamp?",
    "There aren't any pictures.",
  ],
  places: [
    {
      q: "One thing or many things? Drag the sign.",
      items: [["is"], ["are"]],
      zones: [["one bed"], ["two beds"]],
      key: { 0: [0], 1: [1] },
      d: 2,
      hint: "One thing uses is.",
      why: "is for one, are for many.",
    },
    {
      q: "Drag is or are to each picture.",
      items: [["is"], ["are"]],
      zones: [["one chair"], ["two chairs"]],
      key: { 0: [0], 1: [1] },
      d: 3,
      hint: "Count the chairs.",
      why: "One chair: is. Two chairs: are.",
    },
    {
      q: "Drag is or are: one rug, five books.",
      items: [["is"], ["are"]],
      zones: [["one rug"], ["five books"]],
      key: { 0: [0], 1: [1] },
      d: 4,
      hint: "Count each thing.",
      why: "One rug: is. Five books: are.",
    },
  ],
  reads: [
    "There is a bed in my room.",
    "There are two windows.",
    "Is there a lamp?",
    "There isn't a TV here.",
    "There are four chairs.",
    "There is one rug on the floor.",
  ],
  writes: [
    [
      "Draw your bedroom. Write: There is a ___.",
      "There is a bed.",
      ["Có tranh", "Câu There is a … đúng mẫu"],
    ],
    [
      "Draw two things in your room. Write: There are ___.",
      "There are two chairs.",
      ["Có tranh hai vật", "Câu There are … đúng mẫu"],
    ],
    [
      "Draw your desk. Write one is-sentence and one are-sentence.",
      "There is a lamp. There are two books.",
      ["Một câu is", "Một câu are"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── whose / possessive 's ───────────
sentencePack({
  ...base,
  code: "ESL.GR.WHOSE_POSSESSIVE",
  prefix: "esl-whose",
  src: LB5,
  note: "Whose…? và sở hữu cách 's theo đúng Global Stage 1 Unit 5. Ô nhiễu: đặt 's sai chỗ ('hat Nam' thay 'Nam's hat'), nhầm whose với who's, quên 's.",
  items: [
    {
      q: "Which asks about ownership?",
      right: "Whose shoes are these?",
      wrongs: [["Who's coming?"], ["Where are the shoes?"]],
      d: 1,
      hint: "Whose asks who owns something.",
    },
    {
      q: "These are Mai's shoes. Which is right?",
      right: "They're Mai's.",
      wrongs: [["They're shoes Mai."], ["They're Mai."]],
      d: 2,
      hint: "Add 's to the owner's name.",
    },
    {
      q: "Which shows Nam owns the hat?",
      right: "Nam's hat",
      wrongs: [["hat Nam"], ["Nam hat's"]],
      d: 2,
      hint: "The owner's name comes first, with 's.",
    },
    {
      q: "Which is right?",
      right: "This is Tom's bag.",
      wrongs: [["This is bag of Tom."], ["This is Toms bag."]],
      d: 3,
      hint: "Owner + 's + thing.",
    },
    {
      q: "Which question asks who owns the ball?",
      right: "Whose ball is this?",
      wrongs: [["Who's ball is this?"], ["Who ball is this?"]],
      d: 3,
      hint: "Whose, not who's, asks about ownership.",
    },
    {
      q: "Which is right?",
      right: "Whose is this pen?",
      wrongs: [["Who's is this pen?"], ["Whose this pen is?"]],
      d: 4,
      hint: "Whose asks about ownership.",
    },
    {
      q: "Which means 'who is'?",
      right: "Who's",
      wrongs: [["Whose"]],
      d: 4,
      hint: "Who's is short for who is.",
    },
    {
      q: "Which means 'belongs to who'?",
      right: "Whose",
      wrongs: [["Who's"]],
      d: 4,
      hint: "Whose asks about ownership.",
    },
    {
      q: "These shoes belong to my sister. Which is right?",
      right: "They're my sister's shoes.",
      wrongs: [["They're my sister shoes."], ["They're shoes my sister's."]],
      d: 5,
      hint: "Add 's to sister.",
    },
    {
      q: "Which is right for a bag that belongs to the boys?",
      right: "the boys' bag",
      wrongs: [["the boy's bag"], ["the boys bag"]],
      d: 5,
      hint: "More than one owner: apostrophe after the s.",
    },
    {
      q: "Which shows Ana owns the kite?",
      right: "Ana's kite",
      wrongs: [["kite Ana"], ["Ana kite's"]],
      d: 2,
      hint: "Owner's name first, then 's.",
    },
    {
      q: "This coat belongs to my mom. Which is right?",
      right: "It's my mom's coat.",
      wrongs: [["It's my mom coat."], ["It's coat my mom's."]],
      d: 3,
      hint: "Add 's to mom.",
    },
    {
      q: "Which question fits a lost umbrella?",
      right: "Whose umbrella is this?",
      wrongs: [["Who's umbrella is this?"], ["Where is this umbrella?"]],
      d: 3,
      hint: "Whose asks about ownership.",
    },
    {
      q: "Which is right?",
      right: "That is the cat's bowl.",
      wrongs: [["That is cat's the bowl."], ["That is the cats bowl."]],
      d: 4,
      hint: "Owner + 's + thing.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the owner.",
    "{ban} asks whose it is. Tap the answer!",
    "Listen carefully, then choose.",
    "Whose is it? Tap it.",
    "Listen again and pick one.",
    "Listen for the name and 's.",
  ],
  listens: [
    {
      say: "Whose shoes are these? They're Mai's.",
      q: "Whose shoes?",
      right: "Mai's",
      wrongs: [["Tom's"], ["the speaker's"]],
      d: 2,
    },
    {
      say: "This is Nam's hat.",
      q: "Whose hat?",
      right: "Nam's",
      wrongs: [["the speaker's"], ["Mai's"]],
      d: 2,
    },
    {
      say: "Whose is this pen? It's my dad's.",
      q: "Whose pen?",
      right: "the speaker's dad's",
      wrongs: [["the speaker's"], ["a friend's"]],
      d: 3,
    },
    {
      say: "Who's coming to the party?",
      q: "What does 'who's' mean here?",
      right: "who is",
      wrongs: [["whose"], ["who was"]],
      d: 4,
    },
    {
      say: "These are the twins' toys.",
      q: "Whose toys?",
      right: "the twins'",
      wrongs: [["one twin's"], ["the speaker's"]],
      d: 5,
    },
    {
      say: "That is Ana's kite.",
      q: "Whose kite?",
      right: "Ana's",
      wrongs: [["the speaker's"], ["Nam's"]],
      d: 2,
    },
    {
      say: "It's my mom's coat.",
      q: "Whose coat?",
      right: "my mom's",
      wrongs: [["my dad's"], ["the speaker's"]],
      d: 3,
    },
  ],
  builds: ["Whose shoes are these?", "They're Mai's.", "This is Tom's bag.", "Whose is this pen?"],
  sorts: [
    {
      q: "Whose or Who's? Sort the sentences.",
      zones: ["Whose (ownership)", "Who's (who is)"],
      a: ["Whose bag is this?", "Whose shoes are these?"],
      b: ["Who's at the door?", "Who's your teacher?"],
      d: 4,
      hint: "Ownership or 'who is'?",
    },
    {
      q: "One owner or many owners? Sort the words.",
      zones: ["One owner", "Many owners"],
      a: ["Tom's", "Mai's"],
      b: ["the boys'", "the twins'"],
      d: 5,
      hint: "Look for the apostrophe's position.",
    },
  ],
  places: [
    {
      q: "Build: the cat's bowl.",
      items: [["bowl"], ["cat's"], ["the"]],
      zones: [["1"], ["2"], ["3"]],
      key: { 0: [2], 1: [1], 2: [0] },
      d: 3,
      hint: "the + owner's + thing.",
      why: "the cat's bowl.",
    },
  ],
  reads: [
    "Whose shoes are these?",
    "They're Mai's.",
    "This is Tom's bag.",
    "Whose is this pen?",
    "It's my dad's.",
  ],
  writes: [
    ["Draw your shoes. Write: They're ___'s.", "They're Sam's.", ["Có tranh", "Viết đúng 's"]],
    [
      "Draw a friend's toy. Write whose it is.",
      "It's Nam's car.",
      ["Có tranh", "Câu có 's đúng chỗ"],
    ],
  ],
});

// ─────────────────────────────────────────────────────────── bedroom furniture ───────────────
vocabPack({
  ...base,
  code: "ESL.VOC.BEDROOM_FURNITURE",
  prefix: "esl-bedroom",
  src: LB5,
  noun: "thing in a bedroom",
  note: "Mười từ đồ đạc phòng ngủ đúng Global Stage 1 Language Book Unit 5 'Where Are My Shoes?' (docs/09 §4b.1): bed, rug, lamp, table, chair, desk, closet, wall, picture, floor.",
  words: [
    ["bed", "🛏️"],
    ["rug", "🟫"],
    ["lamp", "💡"],
    ["table", "🛋️"],
    ["chair", "🪑"],
    ["desk", "🗄️"],
    ["closet", "🚪"],
    ["wall", "🧱"],
    ["picture", "🖼️"],
    ["floor", "⬜"],
  ],
  counts: [
    ["chairs", "🪑", 4],
    ["pictures", "🖼️", 3],
    ["lamps", "💡", 2],
    ["beds", "🛏️", 5],
  ],
  sentences: [
    "The lamp is on the desk.",
    "My bed is soft.",
    "There is a rug on the floor.",
    "The picture is on the wall.",
  ],
  writes: [
    ["Draw your bedroom. Write: There is a ___.", "There is a bed."],
    ["Write three things in a bedroom.", "bed, lamp, desk"],
    ["Draw a lamp on a desk. Label both.", "lamp, desk"],
  ],
});

// ─────────────────────────────────────────────────────────── clothes ─────────────────────────
vocabPack({
  ...base,
  code: "ESL.VOC.CLOTHES",
  prefix: "esl-clothes",
  src: LB5,
  noun: "piece of clothing",
  note: "Từ vựng đúng Global Stage 1 Language Book Unit 5 (docs/09 §4b.1): pants, glasses, shirt, skirt, jacket, sweater, shorts, hat, boots, sneakers — khác nhẹ so với ví dụ trong mô tả kỹ năng cũ (đoán trước khi có bảng chương trình).",
  words: [
    ["shirt", "👕"],
    ["pants", "👖"],
    ["skirt", "👗"],
    ["jacket", "🧥"],
    ["sweater", "🧶"],
    ["shorts", "🩳"],
    ["hat", "🎩"],
    ["boots", "🥾"],
    ["sneakers", "👟"],
    ["glasses", "👓"],
  ],
  counts: [
    ["hats", "🎩", 3],
    ["boots", "🥾", 4],
    ["sneakers", "👟", 2],
  ],
  sentences: [
    "He's wearing a hat.",
    "She's wearing a red skirt.",
    "I have new sneakers.",
    "Put on your jacket.",
  ],
  writes: [
    ["Draw yourself. Write what you are wearing.", "I am wearing a shirt."],
    ["Write three clothes you wear to school.", "shirt, pants, sneakers"],
  ],
});

// ─────────────────────────────────────────────────────────── plural -s / -es ─────────────────
sentencePack({
  ...base,
  code: "ESL.GR.PLURAL_S",
  prefix: "esl-plurals",
  src: CC("L.1.1c", "regular plural nouns"),
  note: "Thêm -s (cats) hoặc -es (boxes, buses) khi có nhiều hơn một. Ô nhiễu: quên s (thieu_s_so_nhieu, không có dấu chấm cuối), thêm s vào câu số ít.",
  items: [
    {
      q: "Two ___ (dog).",
      right: "dogs",
      wrongs: [["dog", "thieu_s_so_nhieu"], ["doges"]],
      pic: ["🐕", 2],
      d: 1,
      hint: "Add -s for more than one.",
    },
    {
      q: "Three ___ (pen).",
      right: "pens",
      wrongs: [["pen", "thieu_s_so_nhieu"], ["penes"]],
      pic: ["🖊️", 3],
      d: 1,
      hint: "Add -s for more than one.",
    },
    {
      q: "Three ___ (box).",
      right: "boxes",
      wrongs: [["box", "thieu_s_so_nhieu"], ["boxs"]],
      pic: ["📦", 3],
      d: 2,
      hint: "Words ending in x add -es.",
    },
    {
      q: "Two ___ (bus).",
      right: "buses",
      wrongs: [["bus", "thieu_s_so_nhieu"], ["buss"]],
      pic: ["🚌", 2],
      d: 2,
      hint: "Words ending in s add -es.",
    },
    {
      q: "One ___ (cat).",
      right: "cat",
      wrongs: [["cats"], ["cates"]],
      pic: "🐈",
      d: 2,
      hint: "One thing has no -s.",
    },
    {
      q: "Four ___ (chair).",
      right: "chairs",
      wrongs: [["chair", "thieu_s_so_nhieu"], ["chaires"]],
      pic: ["🪑", 4],
      d: 3,
      hint: "Add -s for more than one.",
    },
    {
      q: "Two ___ (dish).",
      right: "dishes",
      wrongs: [["dish", "thieu_s_so_nhieu"], ["dishs"]],
      pic: ["🍽️", 2],
      d: 3,
      hint: "Words ending in sh add -es.",
    },
    {
      q: "Five ___ (apple).",
      right: "apples",
      wrongs: [["apple", "thieu_s_so_nhieu"], ["applies"]],
      pic: ["🍎", 5],
      d: 3,
      hint: "Add -s for more than one.",
    },
    {
      q: "Which is right?",
      right: "I have two cats",
      wrongs: [["I have two cat", "thieu_s_so_nhieu"], ["I have two catss"]],
      d: 4,
      hint: "Two means more than one.",
    },
    {
      q: "Which is right?",
      right: "Three watches",
      wrongs: [["Three watch", "thieu_s_so_nhieu"], ["Three watchs"]],
      d: 4,
      hint: "Words ending in ch add -es.",
    },
    {
      q: "Which is right?",
      right: "One box, two boxes",
      wrongs: [["One box, two box"], ["One boxs, two boxes"]],
      d: 5,
      hint: "Only the plural gets -es.",
    },
    {
      q: "Which needs -es, not -s?",
      right: "brush",
      wrongs: [["cat"], ["pen"]],
      d: 5,
      hint: "Words ending in sh, ch, x, s add -es.",
    },
    {
      q: "Six ___ (fox).",
      right: "foxes",
      wrongs: [["fox", "thieu_s_so_nhieu"], ["foxs"]],
      pic: ["🦊", 6],
      d: 3,
      hint: "Words ending in x add -es.",
    },
    {
      q: "Two ___ (kite).",
      right: "kites",
      wrongs: [["kite", "thieu_s_so_nhieu"], ["kitees"]],
      pic: ["🪁", 2],
      d: 2,
      hint: "Add -s for more than one.",
    },
    {
      q: "Which is right?",
      right: "Five foxes",
      wrongs: [["Five fox", "thieu_s_so_nhieu"], ["Five foxs"]],
      d: 4,
      hint: "Words ending in x add -es.",
    },
    {
      q: "Which is right?",
      right: "Two brushes",
      wrongs: [["Two brush", "thieu_s_so_nhieu"], ["Two brushs"]],
      d: 5,
      hint: "Words ending in sh add -es.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the right word.",
    "{ban} counts something. Tap the word!",
    "Listen carefully, then choose.",
    "One or many? Tap the word.",
    "Listen again and pick one.",
    "Listen for the ending sound.",
  ],
  listens: [
    { say: "two dogs", right: "dogs", wrongs: [["dog", "thieu_s_so_nhieu"], ["doges"]], d: 1 },
    { say: "three boxes", right: "boxes", wrongs: [["box", "thieu_s_so_nhieu"], ["boxs"]], d: 2 },
    { say: "one cat", right: "cat", wrongs: [["cats"], ["cates"]], d: 2 },
    { say: "four buses", right: "buses", wrongs: [["bus", "thieu_s_so_nhieu"], ["buss"]], d: 3 },
    { say: "five pens", right: "pens", wrongs: [["pen", "thieu_s_so_nhieu"], ["penes"]], d: 3 },
    { say: "two dishes", right: "dishes", wrongs: [["dish", "thieu_s_so_nhieu"], ["dishs"]], d: 4 },
  ],
  sorts: [
    {
      q: "Add -s or -es? Sort the words.",
      zones: ["Add -s", "Add -es"],
      a: ["cat", "pen"],
      b: ["box", "bus"],
      d: 3,
      hint: "Words ending in x, s, sh, ch add -es.",
    },
    {
      q: "One or many? Sort the words.",
      zones: ["One", "Many"],
      a: ["dog", "box"],
      b: ["dogs", "boxes"],
      d: 2,
      hint: "Look for the -s or -es.",
    },
  ],
  places: [
    {
      q: "Drag the right plural for box.",
      items: [["boxes"], ["boxs"], ["box"]],
      zones: [["plural"]],
      key: { 0: [0] },
      d: 3,
      hint: "Words ending in x add -es.",
      why: "box + es = boxes.",
    },
    {
      q: "Drag the right plural for cat.",
      items: [["cats"], ["cates"], ["cat"]],
      zones: [["plural"]],
      key: { 0: [0] },
      d: 2,
      hint: "Just add -s.",
      why: "cat + s = cats.",
    },
  ],
  counts: [
    ["dogs", "🐕", 4, "How many dogs? Tap each one, then say dogs."],
    ["boxes", "📦", 3, "How many boxes? Tap each one, then say boxes."],
  ],
  reads: ["I have two cats.", "There are three boxes.", "She has five pens.", "We have two buses."],
  writes: [
    ["Write the plural: one cat, two ___.", "cats", ["Thêm đúng -s"]],
    ["Write the plural: one box, two ___.", "boxes", ["Thêm đúng -es"]],
    ["Draw 3 pens and write: three pens.", "three pens", ["Có tranh 3 cái bút", "Viết đúng pens"]],
  ],
});

// ─────────────────────────────────────────────────────────── initial blends ──────────────────
sentencePack({
  ...base,
  code: "ESL.PH.BLENDS_INITIAL",
  prefix: "esl-blendinit",
  src: "Global Stage 1 Literacy Book Unit 6-8 (blend đầu pr/pl, fl/fr, sl/st, bảng chương trình) — chưa chụp trang sách",
  note: "Đọc từ bắt đầu bằng hai phụ âm liền nhau. Ô nhiễu: bỏ phụ âm thứ hai (fog thay frog, sai_chinh_ta_tu — đúng lỗi 'bỏ phụ âm thứ hai').",
  items: [
    {
      q: "Which is the whole word?",
      right: "frog",
      wrongs: [
        ["fog", SP],
        ["frag", "nham_nguyen_am_ngan"],
      ],
      pic: "🐸",
      d: 1,
      hint: "Say both sounds: f-r.",
    },
    {
      q: "Which is the whole word?",
      right: "black",
      wrongs: [
        ["back", SP],
        ["block", "nham_nguyen_am_ngan"],
      ],
      pic: "⬛",
      d: 1,
      hint: "Say both sounds: b-l.",
    },
    {
      q: "Which is the whole word?",
      right: "clock",
      wrongs: [
        ["cock", SP],
        ["click", "nham_nguyen_am_ngan"],
      ],
      pic: "🕐",
      d: 2,
      hint: "Say both sounds: c-l.",
    },
    {
      q: "Which is the whole word?",
      right: "star",
      wrongs: [
        ["tar", SP],
        ["stir", "nham_nguyen_am_ngan"],
      ],
      pic: "⭐",
      d: 2,
      hint: "Say both sounds: s-t.",
    },
    {
      q: "Which is the whole word?",
      right: "swim",
      wrongs: [
        ["wim", SP],
        ["swam", "nham_nguyen_am_ngan"],
      ],
      pic: "🏊",
      d: 2,
      hint: "Say both sounds: s-w.",
    },
    {
      q: "Which is the whole word?",
      right: "tree",
      wrongs: [["tee", SP], ["try"]],
      pic: "🌳",
      d: 3,
      hint: "Say both sounds: t-r.",
    },
    {
      q: "Which is the whole word?",
      right: "drum",
      wrongs: [
        ["dum", SP],
        ["dram", "nham_nguyen_am_ngan"],
      ],
      pic: "🥁",
      d: 3,
      hint: "Say both sounds: d-r.",
    },
    {
      q: "Which is the whole word?",
      right: "plant",
      wrongs: [
        ["pant", SP],
        ["plent", "nham_nguyen_am_ngan"],
      ],
      pic: "🌱",
      d: 3,
      hint: "Say both sounds: p-l.",
    },
    {
      q: "Which is the whole word?",
      right: "glue",
      wrongs: [["gue", SP], ["gloo"]],
      pic: "🧴",
      d: 4,
      hint: "Say both sounds: g-l.",
    },
    {
      q: "Which is the whole word?",
      right: "brush",
      wrongs: [
        ["bush", SP],
        ["brash", "nham_nguyen_am_ngan"],
      ],
      pic: "🖌️",
      d: 4,
      hint: "Say both sounds: b-r.",
    },
    {
      q: "Which is the whole word?",
      right: "flag",
      wrongs: [
        ["fag", SP],
        ["flog", "nham_nguyen_am_ngan"],
      ],
      pic: "🚩",
      d: 2,
      hint: "Say both sounds: f-l.",
    },
    {
      q: "Which is the whole word?",
      right: "slide",
      wrongs: [["side", SP], ["sload"]],
      pic: "🛝",
      d: 3,
      hint: "Say both sounds: s-l.",
    },
    {
      q: "Which is the whole word?",
      right: "crab",
      wrongs: [
        ["cab", SP],
        ["creb", "nham_nguyen_am_ngan"],
      ],
      pic: "🦀",
      d: 3,
      hint: "Say both sounds: c-r.",
    },
    {
      q: "Which is the whole word?",
      right: "grape",
      wrongs: [["gape", SP], ["grepe"]],
      pic: "🍇",
      d: 4,
      hint: "Say both sounds: g-r.",
    },
    {
      q: "Which is the whole word?",
      right: "smile",
      wrongs: [
        ["mile", SP],
        ["smole", "nham_nguyen_am_ngan"],
      ],
      pic: "😊",
      d: 4,
      hint: "Say both sounds: s-m.",
    },
    {
      q: "Which is the whole word?",
      right: "snail",
      wrongs: [["nail", SP], ["snale"]],
      pic: "🐌",
      d: 5,
      hint: "Say both sounds: s-n.",
    },
    {
      q: "Which is the whole word?",
      right: "spoon",
      wrongs: [["poon", SP], ["spain"]],
      pic: "🥄",
      d: 5,
      hint: "Say both sounds: s-p.",
    },
  ],
  listenPrompts: [
    "Listen, then tap the whole word.",
    "{ban} says a word. Tap it!",
    "Listen for both sounds, then choose.",
    "Which spelling matches? Tap it.",
    "Listen again and pick one.",
    "Say the first two sounds, then tap.",
  ],
  listens: [
    ["frog", "fog", "frag"],
    ["black", "back", "block"],
    ["clock", "cock", "click"],
    ["star", "tar", "stir"],
    ["swim", "wim", "swam"],
    ["drum", "dum", "dram"],
    ["plant", "pant", "plent"],
    ["brush", "bush", "brash"],
    ["flag", "fag", "flog"],
    ["crab", "cab", "creb"],
    ["grape", "gape", "grepe"],
    ["smile", "mile", "smole"],
  ].map(([w, drop, vw], i) => ({
    say: w,
    right: w,
    wrongs: [
      [drop, SP],
      [vw, "nham_nguyen_am_ngan"],
    ],
    d: 1 + (i % 5),
  })),
  sorts: [
    {
      q: "Starts with bl or cl? Sort them.",
      zones: ["bl", "cl"],
      a: ["black", "blue"],
      b: ["clock", "clap"],
      d: 3,
      hint: "Say the first two sounds.",
    },
    {
      q: "Starts with fr or st? Sort them.",
      zones: ["fr", "st"],
      a: ["frog", "fruit"],
      b: ["star", "stop"],
      d: 4,
      hint: "Say the first two sounds.",
    },
  ],
  places: [
    {
      q: "Build frog: drag the sounds in order.",
      items: [["o"], ["f"], ["g"], ["r"]],
      zones: [["1"], ["2"], ["3"], ["4"]],
      key: { 0: [1], 1: [3], 2: [0], 3: [2] },
      d: 4,
      hint: "f-r-o-g.",
      why: "frog is f-r-o-g.",
    },
  ],
  reads: [
    "The frog is green.",
    "I see a black cat.",
    "Look at the clock.",
    "I can see a star.",
    "I like to swim.",
  ],
  writes: [
    ["Draw a frog. Write: frog.", "frog", ["Vẽ con ếch", "Viết đủ f-r-o-g"]],
    ["Write: black, clock, star.", "black clock star", ["Ba từ đúng chính tả"]],
  ],
});

// ─────────────────────────────────────────────────────────── go / play / do activities ───────
vocabPack({
  ...base,
  code: "ESL.VOC.ACTIVITIES_GO_PLAY_DO",
  prefix: "esl-goplaydo",
  src: LB6,
  noun: "activity",
  note: "Cụm hoạt động đúng Global Stage 1 Language Book Unit 6 'Look What I Can Do' (docs/09 §4b.1): go swimming, go horseback riding, go surfing, play tennis, play basketball, play soccer, do karate, do yoga, do ballet.",
  words: [
    ["go swimming", "🏊"],
    ["go surfing", "🏄"],
    ["play tennis", "🎾"],
    ["play basketball", "🏀"],
    ["play soccer", "⚽"],
    ["do karate", "🥋"],
    ["do yoga", "🧘"],
    ["do ballet", "🩰"],
    ["go horseback riding", "🐎"],
  ],
  groups: [
    ["go + -ing", ["go swimming", "go surfing", "go horseback riding"]],
    ["play + sport", ["play tennis", "play basketball", "play soccer"]],
  ],
  counts: [
    ["tennis balls", "🎾", 4],
    ["basketballs", "🏀", 3],
  ],
  sentences: [
    "I do karate.",
    "She plays soccer.",
    "We go swimming on Sunday.",
    "He does yoga every morning.",
    "They play basketball after school.",
  ],
  writes: [
    ["Draw an activity you like. Write: I ___.", "I play soccer."],
    ["Write three activities with go, play, do.", "go swimming, play tennis, do yoga"],
  ],
});

// ─────────────────────────────────────────────────────────── playground ──────────────────────
vocabPack({
  ...base,
  code: "ESL.VOC.PLAYGROUND",
  prefix: "esl-playground",
  src: CC("SL.1", "playground vocabulary") + "; Global Stage 1 chưa có chủ đề riêng cho sân chơi",
  note: "Từ vựng sân chơi và hoạt động ngoài trời. Không thuộc unit cụ thể nào của Global Stage 1 — ghi rõ chưa có sách.",
  words: [
    ["slide", "🛝"],
    ["swing", "🎠"],
    ["seesaw", "⚖️"],
    ["sandbox", "🏖️"],
    ["ball", "⚽"],
    ["kite", "🪁"],
    ["ride a bike", "🚲"],
    ["fly a kite", "🪁"],
  ],
  counts: [
    ["balls", "⚽", 3],
    ["kites", "🪁", 4],
  ],
  sentences: [
    "Let's play on the slide!",
    "I like the swing.",
    "He can ride a bike.",
    "She flies a kite.",
  ],
  writes: [
    ["Draw your favourite playground thing. Write its name.", "slide"],
    ["Write: Let's play!", "Let's play!"],
  ],
});
