/**
 * `pnpm art:emoji` — the pictures behind every emoji an exercise uses.
 *
 * A text emoji is drawn by the device's own emoji font; Windows' Segoe UI Emoji fills about half of
 * its em box, so a "92px" ship shows up the size of a thumbnail (owner, pha 10b). Instead, each emoji
 * used in content/ is copied as an SVG from Google's Noto Color Emoji (Apache-2.0, via
 * @iconify-json/noto) into content/art/emoji/<codepoints>.svg, and the renderer draws an <img>.
 *
 * Writes apps/web/components/kid/exercise/emoji-set.ts, the list of emoji that have a picture, so
 * an emoji without one still falls back to text instead of a broken image.
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

const require = createRequire(import.meta.url);
const root = process.cwd();
const out = join(root, "content", "art", "emoji");
const setFile = join(root, "apps", "web", "components", "kid", "exercise", "emoji-set.ts");

const noto = require("@iconify-json/noto/icons.json");
const chars = require("@iconify-json/noto/chars.json");

/** Codepoints joined by "-", lower case, without the FE0F presentation selector. */
export function emojiKey(value) {
  return [...value]
    .map((ch) => ch.codePointAt(0).toString(16))
    .filter((cp) => cp !== "fe0f")
    .join("-");
}

const found = new Set();
function scan(node) {
  if (!node || typeof node !== "object") return;
  if (node.kind === "emoji" && typeof node.value === "string") found.add(node.value);
  for (const v of Object.values(node)) scan(v);
}
function walk(dir) {
  if (!existsSync(dir)) return;
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) walk(p);
    else if (f.endsWith(".json")) scan(JSON.parse(readFileSync(p, "utf8")));
  }
}
walk(join(root, "content", "exercises"));
walk(join(root, "content", "lessons"));

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
const written = [];
const missing = [];
for (const value of [...found].sort()) {
  const key = emojiKey(value);
  const withFe0f = [...value].map((ch) => ch.codePointAt(0).toString(16)).join("-");
  const padded = key
    .split("-")
    .map((cp) => cp.padStart(4, "0"))
    .join("-");
  const name = chars[key] ?? chars[withFe0f] ?? chars[`${key}-fe0f`] ?? chars[padded];
  const icon = name ? noto.icons[name] : undefined;
  if (!icon) {
    missing.push(value);
    continue;
  }
  const w = icon.width ?? noto.width ?? 128;
  const h = icon.height ?? noto.height ?? 128;
  writeFileSync(
    join(out, `${key}.svg`),
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}"><title>${name}</title>${icon.body}</svg>\n`,
  );
  written.push(key);
}
writeFileSync(
  join(out, "LICENSE.md"),
  "# Emoji pictures\n\nFrom Noto Color Emoji by Google (https://github.com/googlefonts/noto-emoji), Apache License 2.0,\nextracted with `pnpm art:emoji` from the @iconify-json/noto package.\n",
);
// one key per line, so the generated file is already in the formatter's shape
const lines = written.map((k) => `  "${k}",`).join("\n");
writeFileSync(
  setFile,
  `// Generated by scripts/emoji-vendor.mjs (pnpm art:emoji) — do not edit.\n// Emoji keys (codepoints, no FE0F) that have a picture in content/art/emoji/.\nexport const EMOJI_PICTURES: ReadonlySet<string> = new Set([\n${lines}\n]);\n`,
);
console.log(
  `art:emoji — ${written.length} pictures, ${missing.length} without one${missing.length ? `: ${missing.join(" ")}` : ""}`,
);
